/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.HahnSeries.SupportSupremum
public import Mathlib.RingTheory.Ideal.Span

/-!
# The ideal generated by negative monomials

For a coefficient field `K`, `HahnSeries.Nonpositive.negativeMonomialIdeal K` is the ideal
generated by the monomials `t^x` with `x < 0` in the nonpositive real Hahn-series ring. This is
Berarducci's ideal `J`, used as the cited prerequisite for LM24, Proposition 3.5.1. The paper's
description “generated by the monomials” is represented literally by `Ideal.span`.

Membership has the intrinsic characterization

```
b ∈ negativeMonomialIdeal K ↔ supportSup b < 0.
```

The reverse implication factors `b` as the monomial at its support supremum times its normalized
translate. This characterization also records an important boundary: a series may have zero
constant coefficient and support supremum zero, and therefore need not belong to `J`.

This module defines `J` and proves its membership API. Berarducci, Corollary 9.8 proves primeness
over a characteristic-zero field; that theorem is formalized in
`ConwayRefinement.HahnSeries.OrdinalValue.Statements.ProductValue`. The definition and the
lemmas below remain valid over any field.

The definition uses `Ideal.span`; the intrinsic membership theorem is the main interface for
working with the ideal.
-/

universe v

public noncomputable section

namespace HahnSeries.Nonpositive

variable {K : Type v} [Field K]

/-- The coefficient-one monomials at strictly negative real exponents. -/
def negativeMonomials (K : Type v) [Field K] : Set (Nonpositive ℝ K) :=
  Set.range fun x : Set.Iio (0 : ℝ) => single x 1 x.2.le

/-- The ideal generated by the strictly negative monomials in the nonpositive real Hahn ring. -/
def negativeMonomialIdeal (K : Type v) [Field K] : Ideal (Nonpositive ℝ K) :=
  Ideal.span (negativeMonomials K)

theorem negativeMonomialIdeal_def :
    negativeMonomialIdeal K = Ideal.span (negativeMonomials K) :=
  (rfl)

theorem mem_negativeMonomials_iff {m : Nonpositive ℝ K} :
    m ∈ negativeMonomials K ↔ ∃ x : Set.Iio (0 : ℝ), single x.1 1 x.2.le = m :=
  (Iff.rfl)

/-- A coefficient-one monomial at a strictly negative exponent belongs to the negative-monomial
ideal. -/
theorem single_one_mem_negativeMonomialIdeal {x : ℝ} (hx : x < 0) :
    single x (1 : K) hx.le ∈ negativeMonomialIdeal K := by
  apply Ideal.subset_span
  exact ⟨⟨x, hx⟩, rfl⟩

private def supportSupLTZeroIdeal (K : Type v) [Field K] :
    Ideal (Nonpositive ℝ K) where
  carrier := {b | supportSup b < 0}
  zero_mem' := by simp
  add_mem' := by
    intro b c hb hc
    exact (supportSup_add_le b c).trans_lt (max_lt hb hc)
  smul_mem' := by
    intro b c hc
    change supportSup (b * c) < 0
    calc
      supportSup (b * c) ≤ supportSup b + supportSup c :=
        supportSup_mul_le b c
      _ ≤ 0 + supportSup c := by
        simpa [add_comm] using
          (add_le_add_right (supportSup_le_zero b) (supportSup c))
      _ = supportSup c := zero_add _
      _ < 0 := hc

private theorem negativeMonomialIdeal_le_supportSupLTZeroIdeal :
    negativeMonomialIdeal K ≤ supportSupLTZeroIdeal K := by
  rw [negativeMonomialIdeal, Ideal.span_le]
  rintro _ ⟨x, rfl⟩
  change supportSup (single (x : ℝ) (1 : K) x.2.le) < 0
  rw [supportSup_single one_ne_zero]
  exact WithBot.coe_lt_coe.mpr x.2

private theorem mem_negativeMonomialIdeal_of_supportSup_lt_zero
    {b : Nonpositive ℝ K} (hb : supportSup b < 0) :
    b ∈ negativeMonomialIdeal K := by
  by_cases hbzero : b = 0
  · rw [hbzero]
    exact (negativeMonomialIdeal K).zero_mem
  have hsup : sSup (b : K⟦ℝ⟧).support < 0 := by
    rw [supportSup_of_ne hbzero] at hb
    exact WithBot.coe_lt_coe.mp hb
  have hgenerator :
      single (sSup (b : K⟦ℝ⟧).support) (1 : K) hsup.le ∈
        negativeMonomialIdeal K :=
    single_one_mem_negativeMonomialIdeal hsup
  have hfactor :
      single (sSup (b : K⟦ℝ⟧).support) (1 : K) hsup.le * normalize b = b := by
    apply Subtype.ext
    simpa only [Subring.coe_mul, coe_single,
      HahnSeries.single_one_mul_eq_translate] using
        translate_csSup_normalize b
  rw [← hfactor]
  exact Ideal.mul_mem_right (normalize b) (negativeMonomialIdeal K) hgenerator

/-- A nonpositive real Hahn series belongs to the negative-monomial ideal exactly when its
support supremum is strictly negative. -/
theorem mem_negativeMonomialIdeal_iff_supportSup_lt_zero
    {b : Nonpositive ℝ K} :
    b ∈ negativeMonomialIdeal K ↔ supportSup b < 0 := by
  constructor
  · exact fun hb => negativeMonomialIdeal_le_supportSupLTZeroIdeal hb
  · exact mem_negativeMonomialIdeal_of_supportSup_lt_zero

/-- A series with support supremum zero does not belong to the negative-monomial ideal. -/
theorem not_mem_negativeMonomialIdeal_of_supportSup_eq_zero
    {b : Nonpositive ℝ K} (hb : supportSup b = 0) :
    b ∉ negativeMonomialIdeal K := by
  rw [mem_negativeMonomialIdeal_iff_supportSup_lt_zero, hb]
  exact lt_irrefl 0

/-- The negative-monomial ideal is proper. This does not assert that it is prime. -/
theorem negativeMonomialIdeal_ne_top : negativeMonomialIdeal K ≠ ⊤ := by
  intro htop
  have hone : (1 : Nonpositive ℝ K) ∈ negativeMonomialIdeal K := by
    rw [htop]
    trivial
  rw [mem_negativeMonomialIdeal_iff_supportSup_lt_zero] at hone
  have honeEq : single 0 (1 : K) le_rfl = (1 : Nonpositive ℝ K) := by
    apply Subtype.ext
    simp
  rw [← honeEq, supportSup_single one_ne_zero] at hone
  exact (lt_irrefl (0 : WithBot ℝ)) hone

end HahnSeries.Nonpositive
