/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module


public import ConwayRefinement.Algebra.MvPolynomial.Components
public import ConwayRefinement.Algebra.GradedRing.HomogeneousSpan

/-!
# The part at or above a degree of an element of a homogeneous ideal

The part `P_{≥τ}` at or above a degree `τ` of an element `P` of the ideal generated by finitely
many homogeneous polynomials lies in that ideal: `componentsGE wt τ P` is the sum of the
homogeneous components of `P` of degree at least `τ`, and each homogeneous component of an element
of a homogeneous ideal lies in the ideal.
-/

universe u v w

open Finsupp DirectSum

public section

namespace MvPolynomial

variable {σ : Type u} {K : Type v} [Field K] (wt : σ → NatOrdinal)

/-- The part at or above `τ` is the sum of the homogeneous components of degree at least `τ`. -/
theorem componentsGE_eq_sum_weightedHomogeneousComponent (τ : NatOrdinal) (P : MvPolynomial σ K) :
    componentsGE wt τ P =
      ∑ e ∈ (P.support.image (Finsupp.weight wt)).filter fun e ↦ τ ≤ e,
        weightedHomogeneousComponent wt e P := by
  classical
  ext d
  rw [coeff_componentsGE, coeff_sum]
  simp only [coeff_weightedHomogeneousComponent]
  split_ifs with hτ
  · by_cases hd : d ∈ P.support
    · rw [Finset.sum_eq_single (Finsupp.weight wt d)]
      · rw [if_pos rfl]
      · intro e _ he
        rw [if_neg (Ne.symm he)]
      · intro h
        exact absurd (Finset.mem_filter.mpr ⟨Finset.mem_image_of_mem _ hd, hτ⟩) h
    · rw [notMem_support_iff.mp hd]
      exact (Finset.sum_eq_zero fun e _ ↦ by split_ifs <;> rfl).symm
  · refine (Finset.sum_eq_zero fun e he ↦ ?_).symm
    rw [if_neg]
    rintro rfl
    exact hτ (Finset.mem_filter.mp he).2

/-- A homogeneous component of an element of the ideal generated by homogeneous polynomials lies in
the ideal. -/
theorem weightedHomogeneousComponent_mem_span {ι : Type w} [Finite ι] {q : ι → MvPolynomial σ K}
    {c : ι → NatOrdinal} (hq : ∀ j, IsWeightedHomogeneous wt (q j) (c j)) {P : MvPolynomial σ K}
    (hP : P ∈ Ideal.span (Set.range q)) (e : NatOrdinal) :
    weightedHomogeneousComponent wt e P ∈ Ideal.span (Set.range q) := by
  classical
  cases nonempty_fintype ι
  letI := weightedGradedAlgebra K wt
  obtain ⟨u, -, -, hsum⟩ := OrdinalGraded.exists_decompose_eq_sum_mul_of_mem_span
    (𝒜 := weightedHomogeneousSubmodule K wt)
    (fun j ↦ (mem_weightedHomogeneousSubmodule _ _ _ _).mpr (hq j)) hP e
  have hdec : (decompose (weightedHomogeneousSubmodule K wt) P e : MvPolynomial σ K) =
      weightedHomogeneousComponent wt e P := by
    rw [← decompose'_apply]
    rfl
  rw [← hdec, hsum]
  exact Ideal.sum_mem _ fun j _ ↦ Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨j, rfl⟩)

/-- The part at or above a degree `τ` of an element of the ideal generated by homogeneous
polynomials lies in the ideal. -/
theorem componentsGE_mem_span {ι : Type w} [Finite ι] {q : ι → MvPolynomial σ K}
    {c : ι → NatOrdinal} (hq : ∀ j, IsWeightedHomogeneous wt (q j) (c j)) {P : MvPolynomial σ K}
    (hP : P ∈ Ideal.span (Set.range q)) (τ : NatOrdinal) :
    componentsGE wt τ P ∈ Ideal.span (Set.range q) := by
  rw [componentsGE_eq_sum_weightedHomogeneousComponent]
  exact Ideal.sum_mem _ fun e _ ↦ weightedHomogeneousComponent_mem_span wt hq hP e

/-- A homogeneous component of degree at least `τ` is unchanged by passing to the part at or
above `τ`. -/
theorem weightedHomogeneousComponent_componentsGE_of_le {τ e : NatOrdinal} (hτe : τ ≤ e)
    (P : MvPolynomial σ K) :
    weightedHomogeneousComponent wt e (componentsGE wt τ P) =
      weightedHomogeneousComponent wt e P := by
  classical
  ext d
  rw [coeff_weightedHomogeneousComponent, coeff_weightedHomogeneousComponent, coeff_componentsGE]
  split_ifs with h1 h2
  · rfl
  · exact absurd (h1 ▸ hτe) h2
  · rfl

/-- If the part at or above `τ` of `P` lies in the ideal generated by homogeneous polynomials, so
does every homogeneous component of `P` of degree at least `τ`. -/
theorem weightedHomogeneousComponent_mem_span_of_componentsGE_mem {ι : Type w} [Finite ι]
    {q : ι → MvPolynomial σ K} {c : ι → NatOrdinal}
    (hq : ∀ j, IsWeightedHomogeneous wt (q j) (c j)) {P : MvPolynomial σ K} {τ e : NatOrdinal}
    (hP : componentsGE wt τ P ∈ Ideal.span (Set.range q)) (hτe : τ ≤ e) :
    weightedHomogeneousComponent wt e P ∈ Ideal.span (Set.range q) := by
  rw [← weightedHomogeneousComponent_componentsGE_of_le wt hτe]
  exact weightedHomogeneousComponent_mem_span wt hq hP e

end MvPolynomial

end
