/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.Algebra.GradedRing.HomogeneousSpan
public import ConwayRefinement.Algebra.MvPolynomial.FinitePartErasure

import ConwayRefinement.Blueprint

/-!
# A weighted-homogeneous polynomial in the ideal of selected partial derivatives

Suppose `F` is weighted homogeneous of degree `δ`, the coefficient `n` of `1 = ω^0` in the Cantor
normal form of `δ` is positive, and `F` lies in the ideal generated by the partial derivatives at
variables whose weights have constant Cantor coefficient `n`. Then

`F = ∑_t (∂F/∂X_t) (X_t + V_t)`,

where each `V_t` is weighted homogeneous of degree `wt t` and contains no variable whose weight has
constant Cantor coefficient `n`.

Homogeneous ideal membership supplies the cofactors. Setting the selected variables to zero in
each cofactor gives the polynomials `V_t`; the polynomial identity in
`FinitePartErasure` then supplies the terms `X_t`.
-/

universe u v

open scoped NatOrdinal

open OrdinalGraded

public noncomputable section

namespace MvPolynomial

variable {σ : Type u} {K : Type v} [Field K] {wt : σ → NatOrdinal}

/-- Decompose a weighted-homogeneous polynomial that belongs to the ideal generated by the partial
derivatives at variables carrying its positive constant Cantor coefficient. -/
@[blueprint "lem:successor-relation-decomposition"
  (phase := "Algebraic and ordinal preliminaries")
  (title := "Partial-derivative decomposition of a homogeneous ideal relation")
  (statement := /--
    Let $F$ be weighted homogeneous of degree $\delta$, and let $n>0$ be the
    coefficient of $1=\omega^0$ in the Cantor normal form of $\delta$. Suppose
    \[
      F\in\bigl(\partial_iF:i\in\operatorname{vars}(F),\
        \operatorname{coeff}_{\omega^0}(\operatorname{wt}(i))=n\bigr).
    \]
    Then there are weighted-homogeneous polynomials $V_i$ of degree
    $\operatorname{wt}(i)$, involving no variable whose weight has constant
    Cantor coefficient $n$, such that
    \[
      F=\sum_{\substack{i\in\operatorname{vars}(F)\\
          \operatorname{coeff}_{\omega^0}(\operatorname{wt}(i))=n}}
        \frac{\partial F}{\partial X_i}(X_i+V_i).
    \]
  -/)
  (proof := /--
  By \ref{lem:homogeneous-element-of-generated-ideal}, homogeneous ideal
  membership writes $F=\sum_i(\partial_iF)U_i$, with $U_i$ weighted homogeneous
  of degree $\operatorname{wt}(i)$. Let $V_i$ be obtained from $U_i$ by setting
  to zero every variable whose weight has constant Cantor coefficient $n$.
  Applying the same substitution to the displayed ideal identity and combining
  it with \ref{lem:relation-shape} gives the required formula.
  -/)]
theorem exists_eq_sum_pderiv_mul_X_add_of_mem_span {δ : NatOrdinal}
    (hδ : 0 < δ.constantCoeff) {F : MvPolynomial σ K} (hF : IsWeightedHomogeneous wt F δ)
    (hFI : F ∈ Ideal.span ((fun t ↦ pderiv t F) '' (varsOfFinitePart wt F δ : Set σ))) :
    ∃ V : σ → MvPolynomial σ K,
      (∀ t ∈ varsOfFinitePart wt F δ, IsWeightedHomogeneous wt (V t) (wt t) ∧
        V t ∈ supported K {i | (wt i).constantCoeff ≠ δ.constantCoeff}) ∧
      F = ∑ t ∈ varsOfFinitePart wt F δ, pderiv t F * (X t + V t) := by
  classical
  letI := weightedGradedAlgebra K wt
  -- naming the index set keeps later rewrites from reaching inside it
  set T := varsOfFinitePart wt F δ with hT
  have hmemT : ∀ t : ↥T, (t : σ) ∈ F.vars ∧ (wt t).constantCoeff = δ.constantCoeff := fun t ↦
    mem_varsOfFinitePart_iff.mp (hT ▸ t.2)
  obtain ⟨lam, hlam⟩ : ∃ lam : ↥T → NatOrdinal, ∀ t, lam t + wt t = δ :=
    ⟨_, fun t ↦ (exists_add_wt_eq_of_mem_vars hF (hmemT t).1).choose_spec⟩
  -- `F = ∑_t (∂F/∂X_t) U_t` with `U_t` homogeneous of degree `wt t`
  have hFI' : F ∈ Ideal.span (Set.range fun t : ↥T ↦ pderiv (t : σ) F) := by
    rwa [Set.image_eq_range] at hFI
  obtain ⟨U, hU, -, hFU⟩ := exists_eq_sum_mul_of_mem_span
    (𝒜 := weightedHomogeneousSubmodule K wt)
    (q := fun t : ↥T ↦ pderiv (t : σ) F) (c := lam)
    (fun t ↦ (mem_weightedHomogeneousSubmodule _ _ _ _).mpr
      (isWeightedHomogeneous_pderiv_of_add_wt_eq hF (hlam t)))
    ((mem_weightedHomogeneousSubmodule _ _ _ _).mpr hF) hFI'
  have hUt : ∀ t : ↥T, IsWeightedHomogeneous wt (U t) (wt t) := fun t ↦
    (mem_weightedHomogeneousSubmodule _ _ _ _).mp (hU t (wt t) (by rw [add_comm]; exact hlam t))
  -- the partial derivatives are already free of the variables carrying the finite part
  have hc : ∀ t : ↥T, eraseFinitePart wt δ.constantCoeff (pderiv (t : σ) F) =
      pderiv (t : σ) F := fun t ↦
    eraseFinitePart_eq_self wt δ.constantCoeff fun i hi ↦ by
      rw [constantCoeff_wt_eq_zero_of_mem_vars (isWeightedHomogeneous_pderiv_of_add_wt_eq hF
        (hlam t)) (NatOrdinal.constantCoeff_eq_zero_of_add_eq (hmemT t).2 (hlam t)) hi]
      exact hδ.ne
  have hκF : eraseFinitePart wt δ.constantCoeff F =
      ∑ t : ↥T, pderiv (t : σ) F * eraseFinitePart wt δ.constantCoeff (U t) := by
    conv_lhs => rw [hFU]
    rw [map_sum]
    exact Finset.sum_congr rfl fun t _ ↦ by rw [map_mul, hc]
  refine ⟨fun t ↦ if h : t ∈ T then eraseFinitePart wt δ.constantCoeff (U ⟨t, h⟩) else 0,
    fun t ht ↦ ?_, ?_⟩
  · beta_reduce
    rw [dif_pos ht]
    exact ⟨isWeightedHomogeneous_eraseFinitePart wt _ (hUt ⟨t, ht⟩),
      eraseFinitePart_mem_supported wt _ _⟩
  · have hshape := eraseFinitePart_add_sum_X_mul_pderiv hδ hF
    rw [← hT, hκF, ← Finset.sum_coe_sort T] at hshape
    rw [← Finset.sum_coe_sort T]
    conv_lhs => rw [← hshape]
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun t _ ↦ ?_
    beta_reduce
    rw [dif_pos t.2, mul_add, mul_comm (X (t : σ)), add_comm]

end MvPolynomial

end
