/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module


import ConwayRefinement.Blueprint
public import Mathlib.Algebra.MvPolynomial.Equiv
public import Mathlib.Algebra.MvPolynomial.Supported
public import Mathlib.RingTheory.MvPolynomial.Basic
public import Mathlib.RingTheory.Polynomial.Basic
public import Mathlib.RingTheory.PrincipalIdealDomain
public import Mathlib.RingTheory.Noetherian.Basic

/-!
# Syzygies of finitely many polynomials in finitely many variables

Let `c_b` (`b ∈ B`, finite) be elements of a commutative ring. A *syzygy* of `c` is a tuple `u`
with `∑ c_b u_b = 0`. Over a Noetherian ring the syzygies form a finitely generated module. Over a
polynomial ring `R₀[X_j]` the syzygies of elements `c_b ∈ R₀` are generated by the syzygies with
entries in `R₀`: write each entry as a polynomial with coefficients in `R₀`; the coefficient
tuples are syzygies over `R₀`.

Applied to `R₀ = K[X_i : i ∈ Λ]` for a finite set `Λ` of variables — Noetherian by Hilbert's basis
theorem — and `K[X_i : i ∈ ι] = R₀[X_i : i ∉ Λ]`, this gives finitely many syzygies with entries in
`K[X_i : i ∈ Λ]` generating the `K[X_i : i ∈ ι]`-module of syzygies of any finite family
`c_b ∈ K[X_i : i ∈ Λ]`.
-/

universe u v w

open MvPolynomial

public section

namespace MvPolynomial

section Noetherian

variable {R₀ : Type u} [CommRing R₀] [IsNoetherianRing R₀] {B : Type v} [Fintype B]

/-- Over a Noetherian ring, the syzygies of finitely many elements are generated by finitely
many syzygies. -/
theorem exists_finset_syzygy_span (c : B → R₀) :
    ∃ L : Finset (B → R₀), (∀ σ ∈ L, ∑ b, c b * σ b = 0) ∧
      ∀ u : B → R₀, ∑ b, c b * u b = 0 → u ∈ Submodule.span R₀ (L : Set (B → R₀)) := by
  classical
  let φ : (B → R₀) →ₗ[R₀] R₀ := ∑ b, c b • LinearMap.proj b
  have hφ : ∀ u, φ u = ∑ b, c b * u b := fun u ↦ by
    simp only [φ, LinearMap.sum_apply, LinearMap.smul_apply, LinearMap.proj_apply, smul_eq_mul]
  obtain ⟨L, hL⟩ := IsNoetherian.noetherian (LinearMap.ker φ)
  refine ⟨L, fun σ hσ ↦ ?_, fun u hu ↦ ?_⟩
  · have : σ ∈ LinearMap.ker φ := hL ▸ Submodule.subset_span hσ
    rw [LinearMap.mem_ker, hφ] at this
    exact this
  · rw [hL, LinearMap.mem_ker, hφ]
    exact hu

end Noetherian

section BaseChange

variable {R₀ : Type u} [CommRing R₀] {σ : Type w} {B : Type v} [Fintype B]

/-- **Base change.** A syzygy over `R₀[X]` of elements `c_b ∈ R₀` is a combination, with monomial
coefficients, of syzygies over `R₀`: its coefficient tuples. -/
theorem exists_eq_sum_monomial_mul_C_of_sum_C_mul_eq_zero (c : B → R₀)
    (u : B → MvPolynomial σ R₀) (hu : ∑ b, C (c b) * u b = 0) :
    ∃ (m : Finset (σ →₀ ℕ)) (v : (σ →₀ ℕ) → B → R₀),
      (∀ d ∈ m, ∑ b, c b * v d b = 0) ∧ ∀ b, u b = ∑ d ∈ m, monomial d 1 * C (v d b) := by
  classical
  refine ⟨Finset.univ.biUnion fun b ↦ (u b).support, fun d b ↦ coeff d (u b), fun d _ ↦ ?_,
    fun b ↦ ?_⟩
  · have := congrArg (coeff d) hu
    rw [coeff_sum, coeff_zero] at this
    simpa only [coeff_C_mul] using this
  · conv_lhs => rw [(u b).as_sum]
    rw [Finset.sum_subset (Finset.subset_biUnion_of_mem (fun b ↦ (u b).support)
      (Finset.mem_univ b))]
    · exact Finset.sum_congr rfl fun d _ ↦ by rw [mul_comm, C_mul_monomial, mul_one]
    · intro d _ hd
      rw [MvPolynomial.notMem_support_iff.mp hd, monomial_zero]

end BaseChange

section Supported

variable {K : Type u} [Field K] {ι : Type w} {B : Type v} [Fintype B]

/-- The isomorphism `K[X_i : i ∈ ι] ≅ K[X_i : i ∈ Λ][X_i : i ∉ Λ]` separating the variables in
`Λ`. -/
noncomputable def splitVariables (Λ : Set ι) [DecidablePred (· ∈ Λ)] :
    MvPolynomial ι K ≃ₐ[K] MvPolynomial {i // i ∉ Λ} (MvPolynomial Λ K) :=
  (renameEquiv K ((Equiv.sumComm _ _).trans (Equiv.sumCompl (· ∈ Λ))).symm).trans
    (sumAlgEquiv K _ _)

/-- A polynomial in the variables of `Λ` becomes a constant. -/
theorem splitVariables_rename (Λ : Set ι) [DecidablePred (· ∈ Λ)] (q : MvPolynomial Λ K) :
    splitVariables Λ (rename (Subtype.val : Λ → ι) q) = C q := by
  set f : {i // i ∉ Λ} ⊕ Λ ≃ ι := (Equiv.sumComm _ _).trans (Equiv.sumCompl (· ∈ Λ)) with hf
  have hval : (Subtype.val : Λ → ι) = f ∘ Sum.inr := by
    funext a
    simp [hf]
  have h1 : splitVariables (K := K) Λ (rename (Subtype.val : Λ → ι) q) =
      sumAlgEquiv K {i // i ∉ Λ} Λ (rename Sum.inr q) := by
    rw [splitVariables, AlgEquiv.trans_apply, hval, ← rename_rename, renameEquiv_apply,
      rename_rename, Equiv.symm_comp_self]
    simp
  have h2 := AlgHom.congr_fun (sumAlgEquiv_comp_rename_inr K {i // i ∉ Λ} Λ) q
  simp only [AlgHom.comp_apply, IsScalarTower.toAlgHom_apply, algebraMap_eq] at h2
  rw [h1]
  exact h2

/-- A constant comes from a polynomial in the variables of `Λ`. -/
theorem splitVariables_symm_C (Λ : Set ι) [DecidablePred (· ∈ Λ)] (q : MvPolynomial Λ K) :
    (splitVariables Λ).symm (C q) = rename (Subtype.val : Λ → ι) q := by
  rw [← splitVariables_rename Λ q, AlgEquiv.symm_apply_apply]

/-- **Finitely many generating syzygies with entries in the variables of `Λ`.** For a finite set
`Λ` of variables and `c_b ∈ K[X_i : i ∈ Λ]`, there are finitely many syzygies of `c` with entries
in `K[X_i : i ∈ Λ]` generating the `K[X_i : i ∈ ι]`-module of all syzygies of `c`. -/
@[blueprint "lem:syzygies-finite-variables"
  (phase := "Algebraic and ordinal preliminaries")
  (title := "Finite generation of polynomial syzygies")
  (statement := /--
    Let $B$ be a finite set, let $\Lambda\subseteq I$ be finite, and let
    $c_b\in K[X_i:i\in\Lambda]$ for every $b\in B$. There is a finite family
    of tuples $\sigma\in K[X_i:i\in\Lambda]^B$ satisfying
    $\sum_{b\in B}c_b\sigma_b=0$ that generates, over $K[X_i:i\in I]$, every
    tuple $u\in K[X_i:i\in I]^B$ satisfying $\sum_{b\in B}c_bu_b=0$.
  -/)
  (proof := /--
  The ring $K[X_i:i\in\Lambda]$ is Noetherian, so the kernel of
  $(u_b)\mapsto\sum_bc_bu_b$ is finitely generated. Identify
  $K[X_i:i\in I]$ with a polynomial ring in the remaining variables over
  $K[X_i:i\in\Lambda]$. Expanding an arbitrary syzygy in those variables makes
  each coefficient tuple a syzygy over $K[X_i:i\in\Lambda]$. Express each such
  tuple in the chosen finite generating family and reassemble the polynomial.
  -/)]
theorem exists_finset_syzygy_span_supported (Λ : Set ι) [Finite Λ] (c : B → MvPolynomial ι K)
    (hc : ∀ b, c b ∈ supported K Λ) :
    ∃ L : Finset (B → MvPolynomial ι K),
      (∀ σ ∈ L, (∀ b, σ b ∈ supported K Λ) ∧ ∑ b, c b * σ b = 0) ∧
      ∀ u : B → MvPolynomial ι K, ∑ b, c b * u b = 0 →
        u ∈ Submodule.span (MvPolynomial ι K) (L : Set (B → MvPolynomial ι K)) := by
  classical
  -- lifts of the `c_b` to `K[X_i : i ∈ Λ]`
  have hc' : ∀ b, ∃ q : MvPolynomial Λ K, rename (Subtype.val : Λ → ι) q = c b := fun b ↦ by
    have := hc b
    rwa [supported_eq_range_rename, AlgHom.mem_range] at this
  choose c₀ hc₀ using hc'
  obtain ⟨L₀, hL₀, hspan₀⟩ := exists_finset_syzygy_span c₀
  let ρ : (B → MvPolynomial Λ K) → (B → MvPolynomial ι K) := fun σ b ↦ rename Subtype.val (σ b)
  refine ⟨L₀.image ρ, fun σ hσ ↦ ?_, fun u hu ↦ ?_⟩
  · obtain ⟨σ₀, hσ₀, rfl⟩ := Finset.mem_image.mp hσ
    refine ⟨fun b ↦ ?_, ?_⟩
    · rw [supported_eq_range_rename]
      exact ⟨σ₀ b, rfl⟩
    · have := congrArg (rename (Subtype.val : Λ → ι)) (hL₀ σ₀ hσ₀)
      rw [map_sum, map_zero] at this
      simpa only [map_mul, hc₀] using this
  · -- separate the variables: the entries of `u` are polynomials over `K[X_i : i ∈ Λ]`
    set e := splitVariables (K := K) Λ with hedef
    have hu' : ∑ b, C (c₀ b) * e (u b) = 0 := by
      have := congrArg e hu
      rw [map_sum, map_zero] at this
      simpa only [map_mul, ← hc₀, hedef, splitVariables_rename] using this
    obtain ⟨m, v, hv, huv⟩ :=
      exists_eq_sum_monomial_mul_C_of_sum_C_mul_eq_zero c₀ (fun b ↦ e (u b)) hu'
    -- the coefficient tuples are combinations of the generators
    have hvspan : ∀ d, d ∈ m → ∃ r : (B → MvPolynomial Λ K) → MvPolynomial Λ K,
        ∑ σ₀ ∈ L₀, r σ₀ • σ₀ = v d := fun d hd ↦ by
      obtain ⟨f, _, hf⟩ := Submodule.mem_span_finset.mp (hspan₀ (v d) (hv d hd))
      exact ⟨f, hf⟩
    choose! r hr using hvspan
    have hu_eq : u = ∑ d ∈ m, ∑ σ₀ ∈ L₀,
        (e.symm (monomial d 1) * rename Subtype.val (r d σ₀)) • ρ σ₀ := by
      funext b
      have hvb : ∀ d ∈ m, v d b = ∑ σ₀ ∈ L₀, r d σ₀ * σ₀ b := fun d hd ↦ by
        rw [← hr d hd, Finset.sum_apply]
        rfl
      calc u b = e.symm (e (u b)) := (e.symm_apply_apply _).symm
        _ = ∑ d ∈ m, e.symm (monomial d 1) * rename Subtype.val (v d b) := by
          rw [huv b, map_sum]
          exact Finset.sum_congr rfl fun d _ ↦ by rw [map_mul, hedef, splitVariables_symm_C]
        _ = ∑ d ∈ m, ∑ σ₀ ∈ L₀,
            (e.symm (monomial d 1) * rename Subtype.val (r d σ₀)) * rename Subtype.val (σ₀ b) := by
          refine Finset.sum_congr rfl fun d hd ↦ ?_
          rw [hvb d hd, map_sum, Finset.mul_sum]
          exact Finset.sum_congr rfl fun σ₀ _ ↦ by rw [map_mul, mul_assoc]
        _ = _ := by
          simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, ρ]
    rw [hu_eq]
    exact Submodule.sum_mem _ fun d _ ↦ Submodule.sum_mem _ fun σ₀ hσ₀ ↦
      Submodule.smul_mem _ _ (Submodule.subset_span (Finset.mem_image_of_mem ρ hσ₀))

end Supported

end MvPolynomial

end
