/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.HahnSeries.NegativeMonomialIdeal
public import Mathlib.RingTheory.Ideal.Quotient.Defs

import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# Berarducci germs of nonpositive real Hahn series

For a field `K`, `Berarducci.Series K` is the ring `K((ℝ⁽≤0⁾))`, and
`Berarducci.Germ K` is its quotient by the ideal `J` generated by the monomials `t^x` for
`x < 0`. This is Berarducci, Definition 5.1. The additive subgroup
`Berarducci.nearConstantSubgroup K` is the subgroup denoted by `J + K` in Berarducci,
Definition 5.2 and LM24, Section 2.7. It is deliberately an `AddSubgroup`, not an ideal.

The quotient equality certificate proves that two series determine the same germ exactly when
their coefficients agree on an interval `(η, 0]`. The endpoint zero is included: a discrepancy at
zero is a nonzero constant and therefore does not belong to `J`.

These quotient and subgroup definitions make sense over any field. Results imported from
Berarducci that use characteristic zero will retain that hypothesis in their theorem signatures.
-/

universe v

public noncomputable section

namespace Berarducci

open HahnSeries

variable {K : Type v} [Field K]

/-- Every element of the negative-monomial ideal has zero constant coefficient. -/
theorem constantCoeff_eq_zero_of_mem_negativeMonomialIdeal
    {b : HahnSeries.Nonpositive ℝ K}
    (hb : b ∈ HahnSeries.Nonpositive.negativeMonomialIdeal K) :
    HahnSeries.Nonpositive.constantCoeff b = 0 := by
  have hsup :=
    HahnSeries.Nonpositive.mem_negativeMonomialIdeal_iff_supportSup_lt_zero.mp hb
  by_contra hcoeff
  have hbZero : b ≠ 0 := by
    intro hb
    subst b
    simp at hcoeff
  have hzeroSupport : 0 ∈ (b : K⟦ℝ⟧).support := by
    rw [HahnSeries.mem_support]
    simpa [HahnSeries.Nonpositive.constantCoeff_apply] using hcoeff
  rw [HahnSeries.Nonpositive.supportSup_of_ne hbZero] at hsup
  apply (not_lt_of_ge _ hsup)
  exact WithBot.coe_le_coe.mpr
    (le_csSup (HahnSeries.Nonpositive.bddAbove_support b) hzeroSupport)

/-- Berarducci's ring `K((ℝ⁽≤0⁾))` of nonpositive real Hahn series. -/
abbrev Series (K : Type v) [Field K] := HahnSeries.Nonpositive ℝ K

/-- Berarducci's ring of germs `K((ℝ⁽≤0⁾)) / J`. -/
abbrev Germ (K : Type v) [Field K] :=
  Series K ⧸ HahnSeries.Nonpositive.negativeMonomialIdeal K

/-- The quotient map from nonpositive series to Berarducci germs. -/
def toGerm : Series K →+* Germ K :=
  Ideal.Quotient.mk (HahnSeries.Nonpositive.negativeMonomialIdeal K)

/-- Evaluating the germ quotient map is Mathlib's ideal-quotient constructor. -/
@[simp]
theorem toGerm_apply (b : Series K) :
    toGerm b = Ideal.Quotient.mk
      (HahnSeries.Nonpositive.negativeMonomialIdeal K) b :=
  (rfl)

/-- The additive subgroup of constant series in `Berarducci.Series K`. -/
def constantSubgroup (K : Type v) [Field K] : AddSubgroup (Series K) :=
  HahnSeries.Nonpositive.C.toAddMonoidHom.range

/-- Berarducci's additive subgroup `J + K` of series equal to a constant modulo `J`. -/
def nearConstantSubgroup (K : Type v) [Field K] : AddSubgroup (Series K) :=
  (HahnSeries.Nonpositive.negativeMonomialIdeal K).toAddSubgroup ⊔ constantSubgroup K

/-- Membership in the constant subgroup means equality to a constant Hahn series. -/
theorem mem_constantSubgroup_iff {b : Series K} :
    b ∈ constantSubgroup K ↔ ∃ k : K, HahnSeries.Nonpositive.C k = b :=
  AddMonoidHom.mem_range

/-- Membership in `J + K` means being a sum of an element of `J` and a constant series. -/
theorem mem_nearConstantSubgroup_iff {b : Series K} :
    b ∈ nearConstantSubgroup K ↔
      ∃ j ∈ HahnSeries.Nonpositive.negativeMonomialIdeal K,
        ∃ k : K, j + HahnSeries.Nonpositive.C k = b := by
  rw [nearConstantSubgroup, AddSubgroup.mem_sup]
  constructor
  · rintro ⟨j, hj, c, hc, rfl⟩
    rw [mem_constantSubgroup_iff] at hc
    obtain ⟨k, rfl⟩ := hc
    exact ⟨j, hj, k, rfl⟩
  · rintro ⟨j, hj, k, rfl⟩
    exact ⟨j, hj, HahnSeries.Nonpositive.C k,
      mem_constantSubgroup_iff.mpr ⟨k, rfl⟩, rfl⟩

/-- Two series have the same germ exactly when their difference belongs to `J`. -/
theorem toGerm_eq_toGerm_iff {b c : Series K} :
    toGerm b = toGerm c ↔
      b - c ∈ HahnSeries.Nonpositive.negativeMonomialIdeal K :=
  Ideal.Quotient.eq

/-- Two nonpositive series define the same germ exactly when their coefficients agree on some
interval immediately below zero, including the right endpoint. -/
theorem toGerm_eq_toGerm_iff_exists_coeff_eq {b c : Series K} :
    toGerm b = toGerm c ↔
      ∃ η < (0 : ℝ), ∀ δ : ℝ, η < δ → δ ≤ 0 →
        (b : K⟦ℝ⟧).coeff δ = (c : K⟦ℝ⟧).coeff δ := by
  rw [toGerm_eq_toGerm_iff]
  constructor
  · intro hbc
    have hsup :=
      HahnSeries.Nonpositive.mem_negativeMonomialIdeal_iff_supportSup_lt_zero.mp hbc
    by_cases hd : b - c = 0
    · have hbcEq : b = c := sub_eq_zero.mp hd
      exact ⟨-1, by norm_num, fun _ _ _ ↦ by rw [hbcEq]⟩
    · have hsupReal : sSup ((b - c : Series K) : K⟦ℝ⟧).support < 0 := by
        rw [HahnSeries.Nonpositive.supportSup_of_ne hd] at hsup
        exact WithBot.coe_lt_coe.mp hsup
      refine ⟨sSup ((b - c : Series K) : K⟦ℝ⟧).support, hsupReal,
        fun δ hδ _ ↦ ?_⟩
      have hnotSupport : δ ∉ ((b - c : Series K) : K⟦ℝ⟧).support := by
        intro hδSupport
        have hle := le_csSup
          (HahnSeries.Nonpositive.bddAbove_support (b - c)) hδSupport
        exact (not_lt_of_ge hle) hδ
      have hcoeff : (((b - c : Series K) : K⟦ℝ⟧).coeff δ) = 0 := by
        rw [← not_ne_iff, ← HahnSeries.mem_support]
        exact hnotSupport
      simpa using sub_eq_zero.mp hcoeff
  · rintro ⟨η, hη, hcoeff⟩
    rw [HahnSeries.Nonpositive.mem_negativeMonomialIdeal_iff_supportSup_lt_zero]
    by_cases hd : b - c = 0
    · simp [hd]
    · rw [HahnSeries.Nonpositive.supportSup_of_ne hd]
      apply WithBot.coe_lt_coe.mpr
      refine (csSup_le ?_ ?_).trans_lt hη
      · have hd' : (((b - c : Series K) : K⟦ℝ⟧)) ≠ 0 := by
          intro h
          exact hd (Subtype.ext h)
        exact HahnSeries.support_nonempty_iff.mpr hd'
      · intro δ hδSupport
        apply le_of_not_gt
        intro hηδ
        have hδ0 := HahnSeries.Nonpositive.support_subset (b - c) hδSupport
        have heq := hcoeff δ hηδ hδ0
        have hzero : (((b - c : Series K) : K⟦ℝ⟧).coeff δ) = 0 := by
          simpa using sub_eq_zero.mpr heq
        exact (HahnSeries.mem_support _ _).mp hδSupport hzero

/-- A series belongs to `J + K` exactly when subtracting its own constant coefficient leaves an
element of `J`. -/
theorem mem_nearConstantSubgroup_iff_sub_C_constantCoeff_mem {b : Series K} :
    b ∈ nearConstantSubgroup K ↔
      b - HahnSeries.Nonpositive.C (HahnSeries.Nonpositive.constantCoeff b) ∈
        HahnSeries.Nonpositive.negativeMonomialIdeal K := by
  constructor
  · intro hb
    obtain ⟨j, hj, k, hsum⟩ := mem_nearConstantSubgroup_iff.mp hb
    have hcoeff : HahnSeries.Nonpositive.constantCoeff b = k := by
      rw [← hsum, map_add,
        constantCoeff_eq_zero_of_mem_negativeMonomialIdeal hj]
      simp
    rw [hcoeff, ← hsum, add_sub_cancel_right]
    exact hj
  · intro hb
    apply mem_nearConstantSubgroup_iff.mpr
    refine ⟨b - HahnSeries.Nonpositive.C
      (HahnSeries.Nonpositive.constantCoeff b), hb,
        HahnSeries.Nonpositive.constantCoeff b, ?_⟩
    exact sub_add_cancel _ _

/-- A series belongs to `J + K` exactly when its germ is represented by a constant series. -/
theorem mem_nearConstantSubgroup_iff_exists_germ_eq_constant {b : Series K} :
    b ∈ nearConstantSubgroup K ↔
      ∃ k : K, toGerm b = toGerm (HahnSeries.Nonpositive.C k) := by
  rw [mem_nearConstantSubgroup_iff_sub_C_constantCoeff_mem, ← toGerm_eq_toGerm_iff]
  constructor
  · exact fun h ↦ ⟨HahnSeries.Nonpositive.constantCoeff b, h⟩
  · rintro ⟨k, hk⟩
    rw [toGerm_eq_toGerm_iff] at hk ⊢
    have hcoeff : HahnSeries.Nonpositive.constantCoeff b = k := by
      have hzero := constantCoeff_eq_zero_of_mem_negativeMonomialIdeal hk
      have hzero' : HahnSeries.Nonpositive.constantCoeff b - k = 0 := by
        simpa using hzero
      exact sub_eq_zero.mp hzero'
    simpa [hcoeff] using hk

/-- The negative-monomial ideal, regarded as an additive subgroup, is contained in `J + K`. -/
theorem negativeMonomialIdeal_le_nearConstantSubgroup :
    (HahnSeries.Nonpositive.negativeMonomialIdeal K).toAddSubgroup ≤
      nearConstantSubgroup K := by
  intro b hb
  apply AddSubgroup.mem_sup.mpr
  exact ⟨b, hb, 0, (constantSubgroup K).zero_mem, add_zero b⟩

/-- Series congruent modulo `J + K` have equal coefficients on some interval `(η, 0)`. The right
endpoint is excluded: a constant summand changes exactly the coefficient at zero. -/
theorem exists_coeff_eq_of_sub_mem_nearConstantSubgroup
    {b c : Series K} (hbc : b - c ∈ nearConstantSubgroup K) :
    ∃ η < (0 : ℝ), ∀ δ : ℝ, η < δ → δ < 0 →
      (b : K⟦ℝ⟧).coeff δ = (c : K⟦ℝ⟧).coeff δ := by
  have hq := mem_nearConstantSubgroup_iff_sub_C_constantCoeff_mem.mp hbc
  have hgerm : toGerm
        (b - c - HahnSeries.Nonpositive.C
          (HahnSeries.Nonpositive.constantCoeff (b - c))) = toGerm 0 := by
    rw [toGerm_eq_toGerm_iff]
    simpa using hq
  obtain ⟨η, hη, hcoeff⟩ :=
    toGerm_eq_toGerm_iff_exists_coeff_eq.mp hgerm
  refine ⟨η, hη, fun δ hηδ hδ ↦ ?_⟩
  have heq := hcoeff δ hηδ hδ.le
  have hzero : (b : K⟦ℝ⟧).coeff δ - (c : K⟦ℝ⟧).coeff δ = 0 := by
    simpa [hδ.ne] using heq
  exact sub_eq_zero.mp hzero

end Berarducci
