/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module


import ConwayRefinement.Blueprint
public import ConwayRefinement.HahnSeries.OrdinalValue.AlgebraicIndependence.LoweringDerivation
public import ConwayRefinement.Algebra.GradedRing.HomogeneousSpan
import ConwayRefinement.HahnSeries.OrdinalValue.AlgebraicIndependence.SumAlongCutoffs
import ConwayRefinement.HahnSeries.OrdinalValue.AlgebraicIndependence.OmegaSupport
import ConwayRefinement.HahnSeries.OrdinalValue.AlgebraicIndependence.DerivAtInjective

/-!
# Ideal membership of a class from ideal membership of its derivative

Let `α` be a successor ordinal and `(q_1, …, q_m) ⊆ P̂` the ideal generated by finitely many
homogeneous elements `q j` of degrees `c j` that are zero or limits (so `∂ q_j = 0`). For
`x ∈ P_α`, if `∂(x)` is the class of a function at `0⁻` with values in `(q_1, …, q_m)`, then
`x ∈ (q_1, …, q_m)`; indeed `x = ∑_j q_j w_j` with `w_j ∈ P_{μ_j + 1}` and `μ_j + c_j = α ⊖ 1`.

The proof uses that every function at `0⁻` vanishing outside a sequence `γ_k ↑ 0` is a derivative,
and that `∂` is injective on `P_α`. Take a principal representative `p` of `x`; its derivative
`γ ↦ ∂(p)(γ)` vanishes outside a strictly increasing sequence of cutoffs `γ_k` with supremum `0`
(`exists_principal_representative_derivAt`). Decompose the value at `γ_k`, an element of
`(q_1, …, q_m) ∩ P_{α ⊖ 1}`, as `∑_j q_j a_{jk}` with `a_{jk} ∈ P_{μ_j}`, without any coherence in
`k` (`exists_decompose_eq_sum_mul_of_mem_span`). Each `k ↦ a_{jk}` is the derivative of the class
`w_j ∈ P_{μ_j + 1}` of a sum along the cutoffs `γ_k` (`exists_sumAlongCutoffs`).
Since `∂` is a derivation and `∂ q_j = 0`, `∂(∑_j q_j w_j) = ∑_j q_j ∂(w_j) = ∂(x)`, and `∂` is
injective on `P_α`.
-/

universe v w

open scoped NatOrdinal HahnSeries
open Berarducci HahnSeries LoweringDerivation DirectSum

public noncomputable section

namespace Berarducci

variable {K : Type v} [Field K]

/-- The class of a series in `P̂`, through an equality of indices. -/
theorem of_principalComponentMk_congr {β β' : NatOrdinal} (h : β = β') (t : Series K)
    (hβ : ordinalValue t < ω^ (β + 1)) (hβ' : ordinalValue t < ω^ (β' + 1)) :
    DirectSum.of (PrincipalComponent K) β (principalComponentMk β t hβ) =
      DirectSum.of (PrincipalComponent K) β' (principalComponentMk β' t hβ') := by
  subst h
  rfl

/-- The class of a function at `0⁻` of a finite sum is the sum of the classes. -/
theorem funAtZeroMinus_coe_sum {ι : Type w} (s : Finset ι) (g : ι → ℝ → PrincipalSubring K) :
    ((fun ξ ↦ ∑ j ∈ s, g j ξ : ℝ → PrincipalSubring K) : FunAtZeroMinus (PrincipalSubring K)) =
      ∑ j ∈ s, ((g j : ℝ → PrincipalSubring K) : FunAtZeroMinus (PrincipalSubring K)) := by
  have : (fun ξ ↦ ∑ j ∈ s, g j ξ : ℝ → PrincipalSubring K) = ∑ j ∈ s, g j := by
    ext ξ
    simp [Finset.sum_apply]
  rw [this]
  exact map_sum (Filter.Germ.coeRingHom _) g s

/-- `∂` vanishes on homogeneous elements of degree zero or a limit. -/
theorem principalSubringDerivation_eq_zero_of_constantCoeff_eq_zero {c : NatOrdinal}
    (hc : c.constantCoeff = 0) {q : PrincipalSubring K} (hq : q ∈ principalGrading K c) :
    principalSubringDerivation K q = 0 := by
  obtain ⟨b, rfl⟩ := (DirectSum.mem_rangeLof_iff K _ c q).mp hq
  rw [DirectSum.lof_eq_of, principalSubringDerivation_of,
    principalComponentDerivation_of_eq_zero hc]

/-- **A sequence of values at the cutoffs `γ_k` is the derivative of a class.** Given cutoffs
`γ_k ↑ 0` and, for each `k`, an element `u k ∈ P_β` (`β + c = δ`), there is `w ∈ P̂` with
`q * w ∈ P_{δ+1}` for `q ∈ P_c`, whose derivative is the class of a function equal to `u k` at
`γ_k` and to `0` at every other cutoff in `(γ_0, 0)`. When no `β` with `β + c = δ` exists (and
then every `u k = 0`), `w = 0`. -/
theorem exists_principalSubringDerivation_eq_of_forall {δ c : NatOrdinal} {q : PrincipalSubring K}
    (hq : q ∈ principalGrading K c) (γ : ℕ → ℝ) (hγ : StrictMono γ) (hneg : ∀ k, γ k < 0)
    (hcof : ∀ η < (0 : ℝ), ∃ k, η < γ k) (u : ℕ → PrincipalSubring K)
    (hu : ∀ k, ∀ β, β + c = δ → u k ∈ principalGrading K β)
    (hu0 : ∀ k, (¬ ∃ β, β + c = δ) → u k = 0) :
    ∃ w : PrincipalSubring K, q * w ∈ principalGrading K (δ + 1) ∧
      ∃ g : ℝ → PrincipalSubring K, principalSubringDerivation K w = (g : FunAtZeroMinus _) ∧
        (∀ k, g (γ k) = u k) ∧ ∀ ξ, γ 0 < ξ → ξ < 0 → (∀ k, ξ ≠ γ k) → g ξ = 0 := by
  classical
  by_cases h : ∃ β, β + c = δ
  · obtain ⟨μ, hμ⟩ := h
    -- the values, as elements of the homogeneous component `P_μ`
    have ha : ∀ k, ∃ a : PrincipalComponent K μ,
        DirectSum.of (PrincipalComponent K) μ a = u k := fun k ↦ by
      obtain ⟨a, ha⟩ := (DirectSum.mem_rangeLof_iff K _ μ (u k)).mp (hu k μ hμ)
      exact ⟨a, by rw [← DirectSum.lof_eq_of K]; exact ha⟩
    choose a ha using ha
    -- the sum (m) along the cutoffs `γ_k` whose derivative takes these values
    obtain ⟨s, hs, hsk, hsoff⟩ := exists_sumAlongCutoffs μ γ hγ hneg hcof a
    have hidx : (μ + 1).removeNat 1 = μ := by
      have h1 : 1 ≤ (μ + 1).constantCoeff := by
        have := NatOrdinal.constantCoeff_add_natCast μ 1
        rw [Nat.cast_one] at this
        omega
      have := NatOrdinal.removeNat_add_natCast (a := μ + 1) (n := 1) h1
      rw [Nat.cast_one] at this
      exact add_right_cancel this
    have hpos : 0 < (μ + 1).constantCoeff := by
      have := NatOrdinal.constantCoeff_add_natCast μ 1
      rw [Nat.cast_one] at this
      omega
    refine ⟨DirectSum.of (PrincipalComponent K) (μ + 1) (principalComponentMk (μ + 1) s hs), ?_,
      fun ξ ↦ DirectSum.of (PrincipalComponent K) ((μ + 1).removeNat 1) (derivAt (μ + 1) s ξ), ?_,
      fun k ↦ ?_, fun ξ hξ0 hξ hξk ↦ ?_⟩
    · -- the degree of `q * w`
      have hmem := SetLike.mul_mem_graded hq (of_mem_principalGrading (μ + 1)
        (principalComponentMk (μ + 1) s hs))
      have heq : c + (μ + 1) = δ + 1 := by rw [← add_assoc, add_comm c μ, hμ]
      rwa [heq] at hmem
    · rw [principalSubringDerivation_of, principalComponentDerivation_principalComponentMk hpos]
    · -- the value at `γ k`
      obtain ⟨hk, hak⟩ := hsk k
      have hk' : ordinalValue (translatedTruncation (s : K⟦ℝ⟧) (γ k)) <
          ω^ ((μ + 1).removeNat 1 + 1) := by rwa [hidx]
      beta_reduce
      rw [derivAt_eq (μ + 1) s (γ k) hk', of_principalComponentMk_congr hidx _ hk' hk, hak, ha]
    · -- the value at a cutoff that is not a `γ k`
      have hlt := hsoff ξ hξ0 hξ hξk
      have hk' : ordinalValue (translatedTruncation (s : K⟦ℝ⟧) ξ) <
          ω^ ((μ + 1).removeNat 1 + 1) := by
        rw [hidx]
        exact hlt.trans (NatOrdinal.wpow_lt_wpow.mpr (lt_add_one μ))
      beta_reduce
      rw [derivAt_eq (μ + 1) s ξ hk', of_principalComponentMk_congr hidx _ hk' (by
        exact hlt.trans (NatOrdinal.wpow_lt_wpow.mpr (lt_add_one μ))),
        (principalComponentMk_eq_zero_iff μ _ _).mpr hlt, map_zero]
  · refine ⟨0, by rw [mul_zero]; exact zero_mem _, fun _ ↦ 0, by rw [map_zero]; rfl,
      fun k ↦ (hu0 k h).symm, fun _ _ _ _ ↦ rfl⟩

/-- **Ideal membership of a class from ideal membership of its derivative.** Let `α` be a
successor ordinal, let `q j ∈ P_{c j}` be finitely many homogeneous elements of degrees `c j` that
are zero or limits, and let `x ∈ P_α`. If `∂(x)` is the class of a function at `0⁻` with values in
the ideal `(q_1, …, q_m)`, then `x` lies in that ideal. -/
@[blueprint "prop:ideal-from-derivative"
  (phase := "Translated truncations")
  (title := "Derivative criterion for homogeneous ideal membership")
  (statement := /--
    Let $K$ be a field and let $(q_j)_{j\in I}$ be a finite family in
    $\widehat{\mathrm P}$. Suppose that $q_j$ is homogeneous of degree $c_j$
    and that the coefficient of $\omega^0$ in the Cantor normal form of $c_j$
    is zero for every $j$. Let $\alpha$ be an ordinal whose coefficient of
    $\omega^0$ is positive, and let $x\in\mathrm P_\alpha$. If
    $f\colon\mathbb R\to\widehat{\mathrm P}$ satisfies
    \[
      f(\xi)\in(q_j:j\in I)\quad\text{for every }\xi\in\mathbb R
    \]
    and the lowering derivative $\partial x$ is the class of $f$ at $0^-$,
    then
    \[
      x\in(q_j:j\in I)\subseteq\widehat{\mathrm P}.
    \]
  -/)
  (proof := /--
  By \ref{lem:successor-principal-rv-countable-support}, choose a principal series
  representing $x$ whose derivative is supported on a strictly increasing
  sequence of cutoffs cofinal below $0$. At each cutoff, decompose the value of
  $f$ separately as a homogeneous linear combination of the $q_j$. For each
  $j$, apply \ref{prop:realise-derivative} to the resulting sequence of
  coefficients, obtaining a homogeneous element $w_j$ whose derivative has
  exactly those values at the chosen cutoffs and vanishes between them.

  The coefficient condition on $c_j$ gives $\partial q_j=0$. Hence
  \ref{thm:leibniz-rule-lowering-derivation} shows that
  \[
    \partial\!\left(x-\sum_j q_jw_j\right)=0:
  \]
  at a chosen cutoff this is the selected homogeneous decomposition of
  $f(\xi)$, and between the cutoffs both representative functions vanish near
  $0$. The expression in parentheses is homogeneous of degree $\alpha$.
  The same injectivity of the lowering derivative used in the representative
  theorem applies because the coefficient of $\omega^0$ in $\alpha$ is
  positive. Therefore $x=\sum_jq_jw_j$ and $x\in(q_j:j\in I)$.
  -/)]
theorem mem_span_of_principalSubringDerivation_eq_coe {ι : Type w} [Finite ι]
    {q : ι → PrincipalSubring K} {c : ι → NatOrdinal} (hq : ∀ j, q j ∈ principalGrading K (c j))
    (hc : ∀ j, (c j).constantCoeff = 0) {α : NatOrdinal} (hα : 0 < α.constantCoeff)
    {x : PrincipalSubring K} (hx : x ∈ principalGrading K α) {f : ℝ → PrincipalSubring K}
    (hf : ∀ ξ, f ξ ∈ Ideal.span (Set.range q))
    (hΔ : principalSubringDerivation K x = (f : FunAtZeroMinus (PrincipalSubring K))) :
    x ∈ Ideal.span (Set.range q) := by
  classical
  cases nonempty_fintype ι
  set δ := α.removeNat 1 with hδdef
  have hδ : δ + 1 = α := by
    have := NatOrdinal.removeNat_add_natCast (a := α) (n := 1) hα
    rwa [Nat.cast_one] at this
  have hinj := (principalSubringDerivation_isLoweringDerivation K).injective hα hx
  -- `x` is the class of a principal series `p`
  obtain ⟨a, hax⟩ := (DirectSum.mem_rangeLof_iff K _ α x).mp hx
  rw [DirectSum.lof_eq_of] at hax
  by_cases ha : a = 0
  · rw [← hax, ha, map_zero]
    exact Ideal.zero_mem _
  obtain ⟨p, hp, -, -, hpa, γ, hγ, hneg, hcof, hsupp⟩ :=
    exists_principal_representative_derivAt α hα ha
  have hΔx : principalSubringDerivation K x =
      ((fun ξ ↦ DirectSum.of (PrincipalComponent K) δ (derivAt α p ξ) : ℝ → PrincipalSubring K) :
        FunAtZeroMinus (PrincipalSubring K)) := by
    rw [← hax, ← hpa, principalSubringDerivation_of,
      principalComponentDerivation_principalComponentMk hα]
  -- `f` agrees with `ξ ↦ ∂(p)(ξ)` on `(-ε, 0)`
  rw [hΔx] at hΔ
  obtain ⟨ε, hε, hfε⟩ := (funAtZeroMinus_coe_eq_iff_exists _ _).mp hΔ
  -- decompose the values at the cutoffs along the generators
  have hdec := fun k ↦ OrdinalGraded.exists_decompose_eq_sum_mul_of_mem_span
    (𝒜 := principalGrading K) hq
    (hf (γ k)) δ
  choose u hu hu0 hsum using hdec
  -- each sequence of coefficients `k ↦ u k j` is the derivative of a class `w j`
  have hreal := fun j ↦ exists_principalSubringDerivation_eq_of_forall (hq j) γ hγ hneg hcof
    (fun k ↦ u k j) (fun k β hβ ↦ hu k j β hβ) (fun k h ↦ hu0 k j h)
  choose w hw g hg hgk hgoff using hreal
  -- the difference `x - ∑ q_j w_j` has zero derivative
  have hy : x - ∑ j, q j * w j ∈ principalGrading K α :=
    sub_mem hx (hδ ▸ sum_mem fun j _ ↦ hw j)
  have hΔy : principalSubringDerivation K (x - ∑ j, q j * w j) = 0 := by
    have hΔw : principalSubringDerivation K (∑ j, q j * w j) =
        ((fun ξ ↦ ∑ j, q j * g j ξ : ℝ → PrincipalSubring K) :
          FunAtZeroMinus (PrincipalSubring K)) := by
      rw [map_sum, funAtZeroMinus_coe_sum]
      refine Finset.sum_congr rfl fun j _ ↦ ?_
      rw [principalSubringDerivation_mul,
        principalSubringDerivation_eq_zero_of_constantCoeff_eq_zero
          (hc j) (hq j), zero_mul, zero_add, hg j, FunAtZeroMinus.const_mul_coe]
    rw [map_sub, hΔx, hΔw, ← Filter.Germ.coe_sub, FunAtZeroMinus.coe_eq_zero_iff_exists]
    refine ⟨max (-ε) (γ 0), max_lt (by linarith) (hneg 0), fun ξ hξ1 hξ2 ↦ ?_⟩
    rw [max_lt_iff] at hξ1
    simp only [Pi.sub_apply]
    by_cases hξk : ∃ k, γ k = ξ
    · obtain ⟨k, rfl⟩ := hξk
      -- at a cutoff: `f (γ k) ∈ P_δ` equals its decomposition
      have hfk : f (γ k) = DirectSum.of (PrincipalComponent K) δ (derivAt α p (γ k)) :=
        (hfε (γ k) hξ1.1 hξ2).symm
      have hfδ : f (γ k) ∈ principalGrading K δ := hfk ▸ of_mem_principalGrading δ _
      rw [← hfk, sub_eq_zero, ← decompose_of_mem_same (principalGrading K) hfδ, hsum k]
      exact Finset.sum_congr rfl fun j _ ↦ by rw [hgk j k]
    · -- off the cutoffs both sides vanish
      push Not at hξk
      have h0 : derivAt α p ξ = 0 := by
        by_contra hne
        obtain ⟨k, hk⟩ := hsupp ξ hξ2 hne
        exact hξk k hk
      rw [h0, map_zero, Finset.sum_eq_zero fun j _ ↦ by
        rw [hgoff j ξ hξ1.2 hξ2 fun k ↦ (hξk k).symm, mul_zero], sub_zero]
  have hx' := (principalSubringDerivation_isLoweringDerivation K).injective hα hy hΔy
  rw [sub_eq_zero] at hx'
  rw [hx']
  exact Ideal.sum_mem _ fun j _ ↦ Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨j, rfl⟩)

end Berarducci
