/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.HahnSeries.OrdinalValue.AlgebraicIndependence.PrincipalGraded

/-!
# The ideals `I_{≥j}`

For `j : ℕ`, the ideal `I_{≥j}` of `P̂` is generated by the homogeneous elements of
finite degree at least `j`, that is, by the components `P_e` with `j ≤ e < ω`:

`I_{≥j} = ∑_{j ≤ e < ω} P_e P̂`.

These are the ideals `I_{≥j}` of the internal grading of `P̂`. They form a decreasing
multiplicative filtration `I_{≥•}` with `I_{≥0} = P̂` and `I_{≥1} = I`, and a homogeneous element
of `I_{≥j}` vanishes as soon as `j` exceeds the finite part of its degree (the constant term of
its Cantor normal form).
-/

open scoped DirectSum NatOrdinal

universe v

public noncomputable section

namespace Berarducci

open Berarducci LoweringDerivation

variable {K : Type v} [Field K]

variable (K) in
/-- The ideal `I_{≥j} = ∑_{j ≤ e < ω} P_e P̂` generated by the homogeneous elements of finite degree
at least `j`. -/
abbrev principalIdealGE (j : ℕ) : Ideal (PrincipalSubring K) :=
  idealGE (principalGrading K) j

/-- A homogeneous element of finite degree at least `j` belongs to `I_{≥j}`. -/
theorem principalIdealGEGenerator_mem {j e : ℕ} (hje : j ≤ e)
    (F : PrincipalComponent K (e : NatOrdinal)) :
    DirectSum.of (PrincipalComponent K) (e : NatOrdinal) F ∈ principalIdealGE K j :=
  mem_idealGE_of_mem _ hje (of_mem_principalGrading _ F)

variable (K) in
/-- `I_{≥1} = I = (P̂_{<ω})₊ P̂`. -/
theorem principalIdealGE_one : principalIdealGE K 1 = principalFibreIdeal K :=
  (rfl)

/-- A homogeneous element of `I_{≥j}` whose degree has finite part below `j` is zero. -/
theorem eq_zero_of_homogeneous_mem_principalIdealGE {j : ℕ} {δ : NatOrdinal}
    (hδ : δ.constantCoeff < j) (x : PrincipalComponent K δ)
    (hx : DirectSum.of (PrincipalComponent K) δ x ∈ principalIdealGE K j) : x = 0 :=
  DirectSum.of_injective δ ((eq_zero_of_mem_idealGE_of_constantCoeff_lt _
    (of_mem_principalGrading δ x) hx hδ).trans (map_zero _).symm)

/-- Every component of an element of `I_{≥j}` in a degree whose finite part is below `j` is
zero. -/
theorem principalIdealGE_component_eq_zero {j : ℕ} (x : PrincipalSubring K)
    (hx : x ∈ principalIdealGE K j) {δ : NatOrdinal} (hδ : δ.constantCoeff < j) :
    x δ = 0 := by
  refine eq_zero_of_homogeneous_mem_principalIdealGE hδ (x δ) ?_
  have := idealGE_isHomogeneous (principalGrading K) j δ hx
  rwa [DirectSum.coe_decompose_rangeLof, DirectSum.lof_eq_of] at this

end Berarducci
