/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.HahnSeries.OrdinalValue.PrincipalSubring
public import ConwayRefinement.Algebra.DirectSum.InternalGrading
public import ConwayRefinement.Algebra.LoweringDerivation.FilteredModule
public import ConwayRefinement.Algebra.LoweringDerivation.Polynomial
public import Mathlib.Algebra.MvPolynomial.Eval
public import Mathlib.LinearAlgebra.Basis.VectorSpace
public import Mathlib.RingTheory.Ideal.Quotient.Operations

import ConwayRefinement.Algebra.Valuation.AssociatedGradedValuation
import ConwayRefinement.Algebra.Valuation.DegreeAssociatedGradedDomain
import ConwayRefinement.HahnSeries.OrdinalValue.Statements.OrdinalValueDegree
import Mathlib.LinearAlgebra.Projection

/-!
# The internal grading of `P̂`, its finite-degree part `P̂_{<ω}` and the quotient `P̂/I`

The ring `P̂ = ⨁_{α<ω₁} P_α` is internally graded by its components `P_α`
(`principalGrading`), with `P_0 = K`. The objects of the theory of graded algebras over countable
ordinals, specialised to this grading, are the paper's:

`P̂_{<ω} = ⨁_{n<ω} P_n` is the subalgebra of finite degree, `I = I_{≥1} = (P̂_{<ω})₊ P̂` is the
ideal generated by the elements of positive finite degree, `P̂/I` is the quotient by `I`, and
`(P̂_{<ω})₊² ∩ P_n = ∑_{i,j ≥ 1, i+j=n} P_i P_j` is the subspace of decomposables of `P_n`, with
quotient `P_n / ((P̂_{<ω})₊² ∩ P_n)`. The names below are abbreviations, or definitional aliases,
of the generic objects at `principalGrading K`, the decomposables being read inside the component
`P_n` through its homogeneous inclusion.
The ideal `(P̂_{<ω})₊ ⊆ P̂_{<ω}` of elements of positive degree, the elements of `P̂_{<ω}` with
vanishing degree-zero component, is specific to `P̂`; `I` is the least ideal of `P̂` containing it.

A choice of complements `P_n = ((P̂_{<ω})₊² ∩ P_n) ⊕ E_n` and of bases of the `E_n` supplies a
minimal system `𝓑` of homogeneous generators of `P̂_{<ω}`. The system and the evaluation
`K[X_B : B ∈ 𝓑] → P̂_{<ω}` are noncanonical, but evaluation is surjective for every such choice.

Everything here holds over every coefficient field, except that nonzero vectors of finite degree
have nonzero product: that is the multiplicativity of the ordinal value, Berarducci, Theorem 9.7,
and needs characteristic zero.
-/

universe v

public noncomputable section

open Berarducci LoweringDerivation

namespace Berarducci

open scoped DirectSum NatOrdinal

variable {K : Type v} [Field K]

/-! ### The internal grading of `P̂` -/

variable (K) in
/-- The internal grading of `P̂` by the spaces `P_α`. -/
abbrev principalGrading : NatOrdinal → Submodule K (PrincipalSubring K) :=
  DirectSum.rangeLof K (PrincipalComponent K)

theorem of_mem_principalGrading (α : NatOrdinal) (a : PrincipalComponent K α) :
    DirectSum.of (PrincipalComponent K) α a ∈ principalGrading K α :=
  DirectSum.of_mem_rangeLof K _ α a

variable (K) in
/-- Degree zero of the internal grading is the coefficient field: `P_0 = K`. -/
theorem principalGrading_gradeZeroScalars : GradeZeroScalars (principalGrading K) := by
  rw [gradeZeroScalars_iff]
  intro x hx
  obtain ⟨a, rfl⟩ := (DirectSum.mem_rangeLof_iff K _ _ x).mp hx
  obtain ⟨k, rfl⟩ := principalComponentScalarHom_surjective K a
  exact ⟨k, rfl⟩

/-! ### The finite-degree part `P̂_{<ω}` and its ideal `(P̂_{<ω})₊` -/

variable (K) in
/-- The subalgebra of finite degree `P̂_{<ω} = ⨁_{n<ω} P_n` of `P̂`. -/
abbrev principalFiniteDegreePart : Subalgebra K (PrincipalSubring K) :=
  finiteDegreePart (principalGrading K)

/-- Membership in `P̂_{<ω}` means that every nonzero homogeneous component has finite degree. -/
@[simp]
theorem mem_principalFiniteDegreePart_iff (x : PrincipalSubring K) :
    x ∈ principalFiniteDegreePart K ↔
      ∀ α, x α ≠ 0 → α < NatOrdinal.of Ordinal.omega0 := by
  rw [mem_finiteDegreePart_iff, mem_finiteDegreeSubmodule_iff]
  refine forall_congr' fun α ↦ ?_
  rw [DirectSum.coe_decompose_rangeLof, NatOrdinal.lt_omega0, DirectSum.lof_eq_of]
  exact imp_congr_left (not_congr ⟨fun h0 ↦ DirectSum.of_injective α (h0.trans (map_zero _).symm),
    fun h0 ↦ by rw [h0, map_zero]⟩)

/-- A homogeneous vector of finite degree belongs to `P̂_{<ω}`. -/
theorem principalSubring_of_nat_mem (n : ℕ)
    (x : PrincipalComponent K (n : NatOrdinal)) :
    DirectSum.of (PrincipalComponent K) (n : NatOrdinal) x ∈
      principalFiniteDegreePart K :=
  mem_finiteDegreePart_of_mem _ (of_mem_principalGrading _ x)

variable (K) in
/-- The homogeneous inclusion `P_n → P̂_{<ω}` for a finite degree `n`. -/
def finiteDegreeOf (n : ℕ) :
    PrincipalComponent K (n : NatOrdinal) →ₗ[K]
      principalFiniteDegreePart K where
  toFun x := ⟨DirectSum.of (PrincipalComponent K) (n : NatOrdinal) x,
    principalSubring_of_nat_mem n x⟩
  map_add' x y := by
    apply Subtype.ext
    exact map_add (DirectSum.of (PrincipalComponent K) (n : NatOrdinal)) x y
  map_smul' k x := by
    apply Subtype.ext
    exact DirectSum.of_smul K (M := PrincipalComponent K) (n : NatOrdinal) k x

/-- Coercing the inclusion `P_n → P̂_{<ω}` to `P̂` gives `DirectSum.of`. -/
@[simp]
theorem coe_finiteDegreeOf (n : ℕ)
    (x : PrincipalComponent K (n : NatOrdinal)) :
    (finiteDegreeOf K n x : PrincipalSubring K) =
      DirectSum.of (PrincipalComponent K) (n : NatOrdinal) x := by
  rw [finiteDegreeOf]
  rfl

variable (K) in
/-- The inclusion `P_n → P̂_{<ω}` is injective. -/
theorem finiteDegreeOf_injective (n : ℕ) :
    Function.Injective (finiteDegreeOf K n) := by
  intro x y hxy
  apply DirectSum.of_injective (n : NatOrdinal)
  exact congrArg Subtype.val hxy

/-- In degree zero, the homogeneous inclusion agrees with the algebra map from `K`. -/
theorem finiteDegreeOf_zero_scalar (k : K) :
    finiteDegreeOf K 0 (principalComponentScalarHom K k) =
      algebraMap K (principalFiniteDegreePart K) k := by
  apply Subtype.ext
  rw [coe_finiteDegreeOf]
  exact principalSubring_algebraMap_apply k

variable (K) in
/-- The ideal `(P̂_{<ω})₊ = ⨁_{1≤n<ω} P_n` of elements of positive degree of `P̂_{<ω}`. -/
def positiveFinitePrincipalIdeal :
    Ideal (principalFiniteDegreePart K) where
  carrier := {x | (x : PrincipalSubring K) 0 = 0}
  zero_mem' := by simp
  add_mem' := by
    intro x y hx hy
    change (x : PrincipalSubring K) 0 = 0 at hx
    change (y : PrincipalSubring K) 0 = 0 at hy
    change ((x : PrincipalSubring K) + y) 0 = 0
    simp [hx, hy]
  smul_mem' := by
    classical
    intro x y hy
    change (y : PrincipalSubring K) 0 = 0 at hy
    change ((x : PrincipalSubring K) * y) 0 = 0
    calc
      ((x : PrincipalSubring K) * y) 0 =
          (∑ ij ∈ DFinsupp.support (x : PrincipalSubring K) ×ˢ
              DFinsupp.support (y : PrincipalSubring K),
            DirectSum.of (PrincipalComponent K) (ij.1 + ij.2)
              (GradedMonoid.GMul.mul
                ((x : PrincipalSubring K) ij.1)
                ((y : PrincipalSubring K) ij.2))) 0 :=
        congrArg (fun z : PrincipalSubring K ↦ z 0)
          (DirectSum.mul_eq_sum_support_ghas_mul
            (A := PrincipalComponent K) x y)
      _ = ∑ ij ∈ DFinsupp.support (x : PrincipalSubring K) ×ˢ
          DFinsupp.support (y : PrincipalSubring K),
          (DirectSum.of (PrincipalComponent K) (ij.1 + ij.2)
            (GradedMonoid.GMul.mul
              ((x : PrincipalSubring K) ij.1)
              ((y : PrincipalSubring K) ij.2))) 0 := by
        exact DFinsupp.finsetSum_apply _ _ _
      _ = 0 := by
        apply Finset.sum_eq_zero
        rintro ⟨i, j⟩ hij
        by_cases hgrade : i + j = 0
        · have hj : j = 0 := (NatOrdinal.add_eq_zero_iff.mp hgrade).2
          have hyj : (y : PrincipalSubring K) j = 0 := hj ▸ hy
          have hmulzero : GradedMonoid.GMul.mul
              ((x : PrincipalSubring K) i)
              ((y : PrincipalSubring K) j) = 0 := by
            rw [hyj]
            exact DirectSum.GNonUnitalNonAssocSemiring.mul_zero _
          rw [hmulzero, map_zero]
          rfl
        · rw [DirectSum.of_apply]
          simp [hgrade]

/-- Membership in `(P̂_{<ω})₊` is vanishing of the degree-zero component. -/
@[simp]
theorem mem_positiveFinitePrincipalIdeal_iff_component_zero (x : principalFiniteDegreePart K) :
    x ∈ positiveFinitePrincipalIdeal K ↔
      (x : PrincipalSubring K) 0 = 0 :=
  Iff.rfl

/-- Equivalently, every nonzero component of an element of `(P̂_{<ω})₊` has positive degree. -/
theorem mem_positiveFinitePrincipalIdeal_iff (x : principalFiniteDegreePart K) :
    x ∈ positiveFinitePrincipalIdeal K ↔
      ∀ α, (x : PrincipalSubring K) α ≠ 0 → 0 < α := by
  constructor
  · intro hx α hα
    change (x : PrincipalSubring K) 0 = 0 at hx
    exact bot_lt_iff_ne_bot.mpr fun hzero ↦ hα (hzero ▸ hx)
  · intro hx
    change (x : PrincipalSubring K) 0 = 0
    by_contra hzero
    exact (lt_irrefl 0) (hx 0 hzero)

/-! ### The ideal `I = I_{≥1}` and the quotient `P̂/I` -/

variable (K) in
/-- The ideal `I = I_{≥1} = (P̂_{<ω})₊ P̂` of `P̂` generated by the elements of positive finite
degree. -/
abbrev principalFibreIdeal : Ideal (PrincipalSubring K) :=
  fibreIdeal (principalGrading K)

/-- The ideal `I` is the least ideal of `P̂` containing `(P̂_{<ω})₊`. -/
theorem principalFibreIdeal_le_iff (I : Ideal (PrincipalSubring K)) :
    principalFibreIdeal K ≤ I ↔
      ∀ x : principalFiniteDegreePart K,
        x ∈ positiveFinitePrincipalIdeal K →
          (x : PrincipalSubring K) ∈ I := by
  classical
  constructor
  · intro h x hx
    refine h ?_
    have hx0 : (x : PrincipalSubring K) 0 = 0 :=
      (mem_positiveFinitePrincipalIdeal_iff_component_zero x).mp hx
    have hfin := (mem_principalFiniteDegreePart_iff _).mp x.2
    rw [← DirectSum.sum_support_of (β := PrincipalComponent K) (x : PrincipalSubring K)]
    refine Submodule.sum_mem _ fun α hα ↦ ?_
    have hne : (x : PrincipalSubring K) α ≠ 0 := DFinsupp.mem_support_iff.mp hα
    obtain ⟨n, hn⟩ := NatOrdinal.lt_omega0.mp (hfin α hne)
    have hn0 : 1 ≤ n := Nat.one_le_iff_ne_zero.mpr fun h0 ↦
      hne (by rw [hn, h0, Nat.cast_zero]; exact hx0)
    subst hn
    exact mem_idealGE_of_mem _ hn0 (of_mem_principalGrading _ _)
  · intro h
    change idealGE (principalGrading K) 1 ≤ I
    rw [idealGE_eq_span, Ideal.span_le]
    intro y hy
    obtain ⟨e, he, hye⟩ := (mem_idealGEGenerators_iff _ 1 y).mp hy
    obtain ⟨F, rfl⟩ := (DirectSum.mem_rangeLof_iff K _ _ y).mp hye
    have hmem : finiteDegreeOf K e F ∈ positiveFinitePrincipalIdeal K := by
      rw [mem_positiveFinitePrincipalIdeal_iff_component_zero, coe_finiteDegreeOf]
      exact DirectSum.of_eq_of_ne (e : NatOrdinal) 0 F
        (Ne.symm (Nat.cast_ne_zero.mpr (Nat.one_le_iff_ne_zero.mp he)))
    have hI := h _ hmem
    rwa [coe_finiteDegreeOf, ← DirectSum.lof_eq_of K] at hI

/-- Every element of `(P̂_{<ω})₊` belongs to the ideal `I` of `P̂` it generates. -/
theorem coe_mem_principalFibreIdeal {x : principalFiniteDegreePart K}
    (hx : x ∈ positiveFinitePrincipalIdeal K) :
    (x : PrincipalSubring K) ∈ principalFibreIdeal K :=
  (principalFibreIdeal_le_iff _).mp le_rfl x hx

variable (K) in
/-- The quotient `P̂/I` by the ideal `I = I_{≥1}` (the Lean noun is
"fibre": `P̂/I ≅ P̂ ⊗_{P̂_{<ω}} K` is the fibre of `P̂` over `P̂_{<ω} → K`). It is a definitional
alias rather than a reducible abbreviation, so that instance search on `P̂/I` stops here instead
of unfolding the quotient of the direct sum of components at every use. -/
@[expose] def PrincipalFibre : Type (max 1 v) :=
  Fibre (principalGrading K)

instance principalFibreCommRing : CommRing (PrincipalFibre K) :=
  inferInstanceAs (CommRing (Fibre (principalGrading K)))

instance principalFibreAlgebra : Algebra K (PrincipalFibre K) :=
  inferInstanceAs (Algebra K (Fibre (principalGrading K)))

variable (K) in
/-- The quotient map `π : P̂ → P̂/I`. -/
abbrev principalFibreMap :
    PrincipalSubring K →ₐ[K] PrincipalFibre K :=
  fibreMap (principalGrading K)

/-- The quotient map `π : P̂ → P̂/I` is the usual ideal-quotient constructor on elements. -/
theorem principalFibreMap_apply (x : PrincipalSubring K) :
    principalFibreMap K x =
      Ideal.Quotient.mk (principalFibreIdeal K) x :=
  (rfl)

variable (K) in
/-- The kernel of `π : P̂ → P̂/I` is exactly `I`. -/
@[simp]
theorem principalFibreMap_ker :
    RingHom.ker (principalFibreMap K :
      PrincipalSubring K →+* PrincipalFibre K) =
      principalFibreIdeal K :=
  Ideal.Quotient.mkₐ_ker K (principalFibreIdeal K)

/-- A class in `P̂/I` vanishes exactly when its representative lies in `I`. -/
@[simp]
theorem principalFibreMap_eq_zero_iff (x : PrincipalSubring K) :
    principalFibreMap K x = 0 ↔ x ∈ principalFibreIdeal K :=
  Ideal.Quotient.eq_zero_iff_mem

variable (K) in
/-- The quotient map `π : P̂ → P̂/I` is surjective. -/
theorem principalFibreMap_surjective :
    Function.Surjective (principalFibreMap K) :=
  Ideal.Quotient.mkₐ_surjective K (principalFibreIdeal K)

/-! ### Multiplication of components of finite degree and the decomposables -/

variable (K) in
/-- Multiplication `P_m × P_n → P_{m+n}` of two components of finite degree, with output degree the
natural number `m + n`. -/
def principalComponentMulNat (m n : ℕ) :
    PrincipalComponent K (m : NatOrdinal) → PrincipalComponent K (n : NatOrdinal) →
      PrincipalComponent K ((m + n : ℕ) : NatOrdinal) :=
  fun x y ↦
    LinearEquiv.cast (R := K) (Nat.cast_add m n).symm (principalComponentMul x y)

/-- Multiplication `P_m × P_n → P_{m+n}` is fixed-component multiplication transported across the
equality between the cast of `m + n` and the sum of the casts of `m` and `n`. -/
theorem principalComponentMulNat_apply (m n : ℕ)
    (x : PrincipalComponent K (m : NatOrdinal))
    (y : PrincipalComponent K (n : NatOrdinal)) :
    principalComponentMulNat K m n x y =
      LinearEquiv.cast (R := K) (Nat.cast_add m n).symm
        (principalComponentMul x y) :=
  (rfl)

/-- Multiplication in `P̂_{<ω}` agrees with multiplication
`P_m × P_n → P_{m+n}` of components. -/
theorem finiteDegreeOf_mul (m n : ℕ)
    (x : PrincipalComponent K (m : NatOrdinal))
    (y : PrincipalComponent K (n : NatOrdinal)) :
    finiteDegreeOf K m x * finiteDegreeOf K n y =
      finiteDegreeOf K (m + n)
        (principalComponentMulNat K m n x y) := by
  apply Subtype.ext
  change ((finiteDegreeOf K m x :
      principalFiniteDegreePart K) : PrincipalSubring K) *
      ((finiteDegreeOf K n y :
        principalFiniteDegreePart K) : PrincipalSubring K) =
    ((finiteDegreeOf K (m + n)
      (principalComponentMulNat K m n x y) :
        principalFiniteDegreePart K) : PrincipalSubring K)
  rw [coe_finiteDegreeOf, coe_finiteDegreeOf,
    coe_finiteDegreeOf, DirectSum.of_mul_of]
  apply DirectSum.of_eq_of_gradedMonoid_eq
  have hmulEq : GradedMonoid.GMul.mul x y = principalComponentMul x y :=
    (principalComponentMul_eq_componentMul x y).symm
  rw [hmulEq]
  change (⟨(m : NatOrdinal) + (n : NatOrdinal), principalComponentMul x y⟩ :
      GradedMonoid (PrincipalComponent K)) =
    ⟨((m + n : ℕ) : NatOrdinal), principalComponentMulNat K m n x y⟩
  exact Sigma.ext (Nat.cast_add m n).symm (heq_of_cast_eq _ rfl)

variable [CharZero K] in
/-- Multiplication of nonzero vectors of finite degree is nonzero: the ordinal value is
multiplicative (Berarducci, Theorem 9.7). -/
theorem principalComponentMulNat_ne_zero {m n : ℕ} {x : PrincipalComponent K (m : NatOrdinal)}
    {y : PrincipalComponent K (n : NatOrdinal)}
    (hx : x ≠ 0) (hy : y ≠ 0) :
    principalComponentMulNat K m n x y ≠ 0 := by
  rw [principalComponentMulNat]
  rw [← map_zero (LinearEquiv.cast (R := K) (M := PrincipalComponent K)
    (Nat.cast_add m n).symm)]
  apply (LinearEquiv.cast (R := K) (M := PrincipalComponent K)
    (Nat.cast_add m n).symm).injective.ne
  rw [principalComponentMul_eq_componentMul]
  exact MaxAddDegree.componentMul_ne_zero
    (ordinalValueDegreeValuation K) x y hx hy

variable (K) in
/-- The subspace `(P̂_{<ω})₊² ∩ P_n = ∑_{i,j ≥ 1, i+j=n} P_i P_j` of decomposables of `P_n`: the
decomposable part of the internal grading in degree `n`, read inside the component through the
homogeneous inclusion. -/
abbrev decomposablePrincipalComponent (n : ℕ) :
    Submodule K (PrincipalComponent K (n : NatOrdinal)) :=
  (decomposable (principalGrading K) n).comap
    (DirectSum.lof K NatOrdinal (PrincipalComponent K) (n : NatOrdinal))

/-- A homogeneous vector is decomposable exactly when its inclusion is a decomposable
element of `P̂`. -/
theorem mem_decomposablePrincipalComponent_iff
    (n : ℕ) (x : PrincipalComponent K (n : NatOrdinal)) :
    x ∈ decomposablePrincipalComponent K n ↔
      DirectSum.of (PrincipalComponent K) (n : NatOrdinal) x ∈
        decomposable (principalGrading K) n := by
  rw [Submodule.mem_comap, DirectSum.lof_eq_of]

/-- A product of two homogeneous components of positive finite degree belongs to the decomposables
`(P̂_{<ω})₊² ∩ P_{i+j}`. -/
theorem principalComponentMulNat_mem_decomposable {i j : ℕ} (hi : 0 < i) (hj : 0 < j)
    (x : PrincipalComponent K (i : NatOrdinal))
    (y : PrincipalComponent K (j : NatOrdinal)) :
    principalComponentMulNat K i j x y ∈
      decomposablePrincipalComponent K (i + j) := by
  rw [mem_decomposablePrincipalComponent_iff]
  have h := congrArg Subtype.val (finiteDegreeOf_mul i j x y)
  rw [Subalgebra.coe_mul, coe_finiteDegreeOf, coe_finiteDegreeOf, coe_finiteDegreeOf] at h
  rw [← h]
  exact mul_mem_decomposable _ hi hj (of_mem_principalGrading _ _) (of_mem_principalGrading _ _)

variable (K) in
/-- There are no decomposables in degrees zero and one. -/
theorem decomposablePrincipalComponent_eq_bot_of_le_one {n : ℕ} (hn : n ≤ 1) :
    decomposablePrincipalComponent K n = ⊥ := by
  rw [eq_bot_iff]
  intro z hz
  rw [mem_decomposablePrincipalComponent_iff] at hz
  have hle : decomposable (principalGrading K) n ≤ ⊥ :=
    decomposable_le _ fun i j hi hj hij ↦ (by omega : False).elim
  rw [Submodule.mem_bot]
  exact DirectSum.of_injective (n : NatOrdinal)
    (((Submodule.mem_bot K).mp (hle hz)).trans (map_zero _).symm)

variable (K) in
/-- There are no decomposables in degree zero. -/
@[simp]
theorem decomposablePrincipalComponent_zero :
    decomposablePrincipalComponent K 0 = ⊥ :=
  decomposablePrincipalComponent_eq_bot_of_le_one K (Nat.zero_le 1)

variable (K) in
/-- There are no decomposables in degree one: `(P̂_{<ω})₊² ∩ P_1 = 0`. -/
@[simp]
theorem decomposablePrincipalComponent_one :
    decomposablePrincipalComponent K 1 = ⊥ :=
  decomposablePrincipalComponent_eq_bot_of_le_one K le_rfl

variable (K) in
/-- The quotient `P_n / ((P̂_{<ω})₊² ∩ P_n)` of a finite-degree component by its
decomposables. -/
abbrev PrincipalIndecomposableQuotient (n : ℕ) :=
  PrincipalComponent K (n : NatOrdinal) ⧸ decomposablePrincipalComponent K n

variable (K) in
/-- The quotient map `P_n → P_n / ((P̂_{<ω})₊² ∩ P_n)`. -/
def principalIndecomposableMk (n : ℕ) :
    PrincipalComponent K (n : NatOrdinal) →ₗ[K]
      PrincipalIndecomposableQuotient K n :=
  (decomposablePrincipalComponent K n).mkQ

variable (K) in
/-- The kernel of `P_n → P_n / ((P̂_{<ω})₊² ∩ P_n)` is exactly the decomposables. -/
@[simp]
theorem principalIndecomposableMk_ker (n : ℕ) :
    LinearMap.ker (principalIndecomposableMk K n) =
      decomposablePrincipalComponent K n :=
  by
    rw [principalIndecomposableMk, Submodule.ker_mkQ]

variable (K) in
/-- The quotient map `P_n → P_n / ((P̂_{<ω})₊² ∩ P_n)` is surjective. -/
theorem principalIndecomposableMk_surjective (n : ℕ) :
    Function.Surjective (principalIndecomposableMk K n) :=
  by
    rw [principalIndecomposableMk]
    exact Submodule.mkQ_surjective _

/-- A class in `P_n / ((P̂_{<ω})₊² ∩ P_n)` vanishes exactly when its representative is
decomposable. -/
@[simp]
theorem principalIndecomposableMk_eq_zero_iff (n : ℕ)
    (x : PrincipalComponent K (n : NatOrdinal)) :
    principalIndecomposableMk K n x = 0 ↔
      x ∈ decomposablePrincipalComponent K n := by
  rw [← LinearMap.mem_ker, principalIndecomposableMk_ker]

variable (K) in
/-- A chosen complement `E_n` of the decomposables `(P̂_{<ω})₊² ∩ P_n` in `P_n`. -/
noncomputable def principalIndecomposableComplement (n : ℕ) :
    Submodule K (PrincipalComponent K (n : NatOrdinal)) :=
  Classical.choose (decomposablePrincipalComponent K n).exists_isCompl

variable (K) in
/-- The chosen subspace `E_n` is complementary to the decomposables `(P̂_{<ω})₊² ∩ P_n`. -/
theorem decomposablePrincipalComponent_isCompl_complement (n : ℕ) :
    IsCompl (decomposablePrincipalComponent K n)
      (principalIndecomposableComplement K n) :=
  Classical.choose_spec (decomposablePrincipalComponent K n).exists_isCompl

variable (K) in
/-- The chosen index type for a basis of `E_n`: it indexes `𝓑_n = 𝓑 ∩ P_n`, the elements of degree
`n` of the minimal system. -/
abbrev PrincipalCoordinateIndex (n : ℕ) :=
  Module.Free.ChooseBasisIndex K (principalIndecomposableComplement K n)

variable (K) in
/-- A chosen basis `𝓑_n` of the complement `E_n`. -/
noncomputable def principalCoordinateBasis (n : ℕ) :
    Module.Basis (PrincipalCoordinateIndex K n) K
      (principalIndecomposableComplement K n) :=
  Module.Free.chooseBasis K (principalIndecomposableComplement K n)

variable (K) in
/-- The chosen complement `E_n` identified with the quotient `P_n / ((P̂_{<ω})₊² ∩ P_n)`. -/
noncomputable def principalIndecomposableComplementEquiv (n : ℕ) :
    principalIndecomposableComplement K n ≃ₗ[K]
      PrincipalIndecomposableQuotient K n :=
  ((decomposablePrincipalComponent K n).quotientEquivOfIsCompl
    (principalIndecomposableComplement K n)
    (decomposablePrincipalComponent_isCompl_complement K n)).symm

/-- The complement equivalence sends a vector to its class modulo the decomposables. -/
@[simp]
theorem principalIndecomposableComplementEquiv_apply (n : ℕ)
    (x : principalIndecomposableComplement K n) :
    principalIndecomposableComplementEquiv K n x =
      (decomposablePrincipalComponent K n).mkQ x := by
  rw [principalIndecomposableComplementEquiv]
  exact DFunLike.congr_fun
    (Submodule.toLinearMap_symm_quotientEquivOfIsCompl
      (decomposablePrincipalComponent_isCompl_complement K n)) x

variable (K) in
/-- The basis of `P_n / ((P̂_{<ω})₊² ∩ P_n)` induced from the chosen basis `𝓑_n` of `E_n`. -/
noncomputable def principalIndecomposableBasis (n : ℕ) :
    Module.Basis (PrincipalCoordinateIndex K n) K
      (PrincipalIndecomposableQuotient K n) :=
  (principalCoordinateBasis K n).map
    (principalIndecomposableComplementEquiv K n)

/-- The functional on `P_n / ((P̂_{<ω})₊² ∩ P_n)` dual to one basis vector `B ∈ 𝓑_n`. -/
noncomputable def principalCoordinateFunctional (n : ℕ)
    (i : PrincipalCoordinateIndex K n) :
    Module.Dual K (PrincipalIndecomposableQuotient K n) :=
  (principalIndecomposableBasis K n).coord i

/-- The dual functionals form the Kronecker dual family of the basis `𝓑_n`. -/
@[simp]
theorem principalCoordinateFunctional_basis (n : ℕ)
    (i j : PrincipalCoordinateIndex K n) :
    principalCoordinateFunctional n i
        (principalIndecomposableBasis K n j) = if i = j then 1 else 0 := by
  classical
  rw [principalCoordinateFunctional, Module.Basis.coord_apply]
  simp [Finsupp.single_apply, eq_comm]

variable (K) in
/-- The minimal system `𝓑` of homogeneous generators of `P̂_{<ω}`, as an index type: an element
`B ∈ 𝓑` is a positive finite degree `n` together with an index into the chosen basis `𝓑_n` of
`E_n`. -/
abbrev MinimalSystem :=
  Σ n : {n : ℕ // 0 < n}, PrincipalCoordinateIndex K n

/-- The degree `deg B` of an element `B ∈ 𝓑`, a positive natural number. -/
abbrev minimalSystemDegree (x : MinimalSystem K) : ℕ :=
  x.1

/-- Every `B ∈ 𝓑` has positive degree. -/
theorem minimalSystemDegree_pos (x : MinimalSystem K) :
    0 < minimalSystemDegree x :=
  x.1.property

/-- An element `B ∈ 𝓑` as a vector of its component `P_{deg B}`. -/
noncomputable def minimalSystemComponent (x : MinimalSystem K) :
    PrincipalComponent K (minimalSystemDegree x : NatOrdinal) :=
  (principalCoordinateBasis K x.1 x.2).1

theorem minimalSystemComponent_eq (x : MinimalSystem K) :
    minimalSystemComponent x = (principalCoordinateBasis K x.1 x.2).1 :=
  (rfl)

/-- The class of `B ∈ 𝓑` modulo the decomposables is the corresponding basis vector of
`P_n / ((P̂_{<ω})₊² ∩ P_n)`. -/
@[simp]
theorem minimalSystemComponent_mkQ (x : MinimalSystem K) :
    Submodule.Quotient.mk (minimalSystemComponent x) =
      principalIndecomposableBasis K x.1 x.2 := by
  rw [minimalSystemComponent,
    principalIndecomposableBasis, Module.Basis.map_apply,
    principalIndecomposableComplementEquiv_apply]
  rfl

/-- The named quotient map sends `B ∈ 𝓑` to the corresponding basis vector of the quotient of
its component by the decomposables. -/
@[simp]
theorem principalIndecomposableMk_minimalSystemComponent
    (x : MinimalSystem K) :
    principalIndecomposableMk K
        (minimalSystemDegree x)
        (minimalSystemComponent x) =
      principalIndecomposableBasis K x.1 x.2 := by
  rw [principalIndecomposableMk]
  exact minimalSystemComponent_mkQ x

/-- The functional on `P_{deg B} / ((P̂_{<ω})₊² ∩ P_{deg B})` dual to `B ∈ 𝓑`. -/
noncomputable def minimalSystemFunctional (x : MinimalSystem K) :
    Module.Dual K (PrincipalIndecomposableQuotient K x.1) :=
  principalCoordinateFunctional x.1 x.2

/-- `B ∈ 𝓑` evaluates to one under its dual functional. -/
@[simp]
theorem minimalSystemFunctional_self (x : MinimalSystem K) :
    minimalSystemFunctional x
        (principalIndecomposableBasis K x.1 x.2) = 1 := by
  rw [minimalSystemFunctional,
    principalCoordinateFunctional_basis]
  simp

/-- The dual functional of `B ∈ 𝓑_n` evaluates the basis `𝓑_n` by the Kronecker formula. -/
@[simp]
theorem minimalSystemFunctional_basis
    (n : {n : ℕ // 0 < n}) (i j : PrincipalCoordinateIndex K n) :
    minimalSystemFunctional ⟨n, i⟩
        (principalIndecomposableBasis K n j) =
      if i = j then 1 else 0 := by
  rw [minimalSystemFunctional,
    principalCoordinateFunctional_basis]

variable (K) in
/-- In degree one the chosen complement is the whole component `P_1`: `(P̂_{<ω})₊² ∩ P_1 = 0`, there
being no two positive degrees with sum one. -/
theorem principalIndecomposableComplement_one_eq_top :
    principalIndecomposableComplement K 1 = ⊤ := by
  have h := decomposablePrincipalComponent_isCompl_complement K 1
  rw [decomposablePrincipalComponent_one] at h
  have hsup := h.sup_eq_top
  rwa [bot_sup_eq] at hsup

variable (K) in
/-- `𝓑_1 = 𝓑 ∩ P_1` is a `K`-basis of the whole component `P_1`. Its coordinate representation
expands every element of `P_1` in the elements of `𝓑` of degree one. -/
noncomputable def principalCoordinateBasisOne :
    Module.Basis (PrincipalCoordinateIndex K 1) K
      (PrincipalComponent K ((1 : ℕ) : NatOrdinal)) :=
  (principalCoordinateBasis K 1).map
    ((LinearEquiv.ofEq _ _ (principalIndecomposableComplement_one_eq_top K)).trans
      (Submodule.topEquiv))

/-- The basis vectors of `P_1` are the elements of `𝓑` of degree one. -/
@[simp]
theorem principalCoordinateBasisOne_apply (i : PrincipalCoordinateIndex K 1) :
    principalCoordinateBasisOne K i =
      minimalSystemComponent ⟨⟨1, Nat.one_pos⟩, i⟩ := by
  rw [principalCoordinateBasisOne, Module.Basis.map_apply, LinearEquiv.trans_apply]
  rfl

/-- Every `B ∈ 𝓑` is a nonzero vector of its component. -/
theorem minimalSystemComponent_ne_zero (x : MinimalSystem K) :
    minimalSystemComponent x ≠ 0 := by
  rw [minimalSystemComponent]
  intro hzero
  apply (principalCoordinateBasis K x.1).ne_zero x.2
  exact Subtype.ext hzero

/-- An element `B ∈ 𝓑` regarded as an element of `P̂_{<ω}`. -/
noncomputable def minimalSystemElement (x : MinimalSystem K) :
    principalFiniteDegreePart K :=
  finiteDegreeOf K
    (minimalSystemDegree x)
    (minimalSystemComponent x)

/-- `B ∈ 𝓑` is homogeneous of degree `deg B`. -/
theorem minimalSystemElement_eq (x : MinimalSystem K) :
    minimalSystemElement x =
      finiteDegreeOf K (minimalSystemDegree x) (minimalSystemComponent x) :=
  (rfl)

/-- The element of `P̂` underlying `B ∈ 𝓑` is its homogeneous inclusion. -/
@[simp]
theorem coe_minimalSystemElement (x : MinimalSystem K) :
    ((minimalSystemElement x :
        principalFiniteDegreePart K) : PrincipalSubring K) =
      DirectSum.of (PrincipalComponent K)
        (minimalSystemDegree x : NatOrdinal)
        (minimalSystemComponent x) := by
  rw [minimalSystemElement, coe_finiteDegreeOf]

/-- Every `B ∈ 𝓑` belongs to `(P̂_{<ω})₊`. -/
theorem minimalSystemElement_mem_positive (x : MinimalSystem K) :
    minimalSystemElement x ∈
      positiveFinitePrincipalIdeal K := by
  change (DirectSum.of (PrincipalComponent K)
    (minimalSystemDegree x : NatOrdinal)
    (minimalSystemComponent x)) 0 = 0
  rw [DirectSum.of_apply]
  split_ifs with hzero
  · exact ((Nat.cast_ne_zero.mpr
      (Nat.ne_of_gt (minimalSystemDegree_pos x))) hzero).elim
  · rfl

/-- Every `B ∈ 𝓑` is nonzero in `P̂_{<ω}`. -/
theorem minimalSystemElement_ne_zero (x : MinimalSystem K) :
    minimalSystemElement x ≠ 0 := by
  intro hzero
  apply minimalSystemComponent_ne_zero x
  apply finiteDegreeOf_injective K
    (minimalSystemDegree x)
  rw [map_zero]
  exact hzero

variable (K) in
/-- The evaluation `K[X_B : B ∈ 𝓑] → P̂_{<ω}`, `X_B ↦ B`. -/
noncomputable def finiteDegreePolynomialEval :
    MvPolynomial (MinimalSystem K) K →ₐ[K]
      principalFiniteDegreePart K :=
  MvPolynomial.aeval minimalSystemElement

/-- The evaluation `K[X_B : B ∈ 𝓑] → P̂_{<ω}` sends each indeterminate `X_B` to `B`. -/
@[simp]
theorem finiteDegreePolynomialEval_X (x : MinimalSystem K) :
    finiteDegreePolynomialEval K (MvPolynomial.X x) =
      minimalSystemElement x := by
  rw [finiteDegreePolynomialEval, MvPolynomial.aeval_X]

private theorem finiteDegreeOf_mem_polynomialRange
    (n : ℕ) (x : PrincipalComponent K (n : NatOrdinal)) :
    finiteDegreeOf K n x ∈
      (finiteDegreePolynomialEval K).range := by
  induction n using Nat.strong_induction_on with
  | h n ih =>
      let A := (finiteDegreePolynomialEval K).range
      rcases n.eq_zero_or_pos with rfl | hn
      · obtain ⟨k, hk⟩ := principalComponentScalarHom_surjective K x
        have hk' : principalComponentScalarHom K k = x := by
          simpa only [Nat.cast_zero] using hk
        refine ⟨MvPolynomial.C k, ?_⟩
        change finiteDegreePolynomialEval K (MvPolynomial.C k) = _
        rw [finiteDegreePolynomialEval, MvPolynomial.aeval_C,
          ← hk', finiteDegreeOf_zero_scalar]
      · let D := decomposablePrincipalComponent K n
        let E := principalIndecomposableComplement K n
        have hCompl : IsCompl D E :=
          decomposablePrincipalComponent_isCompl_complement K n
        obtain ⟨d, e, hde, _⟩ :=
          Submodule.existsUnique_add_of_isCompl hCompl x
        rw [← hde, map_add]
        apply A.add_mem
        · change finiteDegreeOf K n (d :
              PrincipalComponent K (n : NatOrdinal)) ∈ A
          -- the image of `A` in `P̂` contains every product `P_i P_j` with `i + j = n`
          let N : Submodule K (PrincipalSubring K) :=
            (Subalgebra.toSubmodule A).map (principalFiniteDegreePart K).val.toLinearMap
          have hN : decomposable (principalGrading K) n ≤ N := by
            refine decomposable_le _ fun i j hi hj hij ↦ Submodule.mul_le.mpr fun a ha b hb ↦ ?_
            obtain ⟨a', rfl⟩ := (DirectSum.mem_rangeLof_iff K _ _ a).mp ha
            obtain ⟨b', rfl⟩ := (DirectSum.mem_rangeLof_iff K _ _ b).mp hb
            subst hij
            refine ⟨finiteDegreeOf K i a' * finiteDegreeOf K j b',
              A.mul_mem (ih i (by omega) a') (ih j (by omega) b'), ?_⟩
            rw [AlgHom.toLinearMap_apply, Subalgebra.coe_val, Subalgebra.coe_mul,
              coe_finiteDegreeOf, coe_finiteDegreeOf, DirectSum.lof_eq_of, DirectSum.lof_eq_of]
          obtain ⟨s, hs, hsd⟩ := hN (Submodule.mem_comap.mp d.2)
          rw [AlgHom.toLinearMap_apply, Subalgebra.coe_val] at hsd
          have hds : finiteDegreeOf K n (d : PrincipalComponent K (n : NatOrdinal)) = s := by
            apply Subtype.ext
            rw [coe_finiteDegreeOf, ← DirectSum.lof_eq_of K, ← hsd]
          rw [hds]
          exact hs
        · change finiteDegreeOf K n (e :
              PrincipalComponent K (n : NatOrdinal)) ∈ A
          let B := principalCoordinateBasis K n
          have he : e ∈ Submodule.span K (Set.range B) := by
            rw [B.span_eq]
            exact Submodule.mem_top
          refine Submodule.span_induction (R := K) (M := E)
            (s := Set.range B) (p := fun y _ ↦
            finiteDegreeOf K n (y :
              PrincipalComponent K (n : NatOrdinal)) ∈ A) ?_ ?_ ?_ ?_ he
          · intro z hz
            obtain ⟨i, rfl⟩ := hz
            let q : MinimalSystem K := ⟨⟨n, hn⟩, i⟩
            refine ⟨MvPolynomial.X q, ?_⟩
            change finiteDegreePolynomialEval K (MvPolynomial.X q) = _
            rw [finiteDegreePolynomialEval_X]
            rfl
          · change finiteDegreeOf K n (0 :
              PrincipalComponent K (n : NatOrdinal)) ∈ A
            rw [map_zero]
            exact A.zero_mem
          · intro y z _ _ hy hz
            simpa using A.add_mem hy hz
          · intro k y _ hy
            simpa using A.smul_mem hy k

variable (K) in
/-- The minimal system `𝓑` generates `P̂_{<ω}`: the evaluation `K[X_B : B ∈ 𝓑] → P̂_{<ω}` is
surjective. -/
theorem finiteDegreePolynomialEval_surjective :
    Function.Surjective (finiteDegreePolynomialEval K) := by
  intro x
  let A := (finiteDegreePolynomialEval K).range
  let p : PrincipalSubring K → Prop := fun y ↦
    ∀ hy : ∀ α, y α ≠ 0 → α < NatOrdinal.of Ordinal.omega0,
      (⟨y, (mem_principalFiniteDegreePart_iff y).mpr hy⟩ : principalFiniteDegreePart K) ∈ A
  have hx : ∀ α, (x : PrincipalSubring K) α ≠ 0 → α < NatOrdinal.of Ordinal.omega0 :=
    (mem_principalFiniteDegreePart_iff _).mp x.2
  change (⟨(x : PrincipalSubring K), (mem_principalFiniteDegreePart_iff _).mpr hx⟩ :
    principalFiniteDegreePart K) ∈ A
  refine DFinsupp.induction (p := p) (x : PrincipalSubring K) ?_ ?_ hx
  · intro hy
    change (0 : principalFiniteDegreePart K) ∈ A
    exact A.zero_mem
  · intro α b y hyα hb hy hfinite
    have hαFinite : α < NatOrdinal.of Ordinal.omega0 := by
      apply hfinite α
      change (DFinsupp.single α b + y) α ≠ 0
      simp [hyα, hb]
    obtain ⟨n, hn⟩ := NatOrdinal.lt_omega0.mp hαFinite
    subst α
    have hyFinite : ∀ β, y β ≠ 0 →
        β < NatOrdinal.of Ordinal.omega0 := by
      intro β hyβ
      apply hfinite β
      by_cases hβ : (n : NatOrdinal) = β
      · subst β
        simpa [hyα] using hb
      · change (DFinsupp.single (n : NatOrdinal) b + y) β ≠ 0
        simpa [DFinsupp.single_apply, hβ] using hyβ
    have hsingle := finiteDegreeOf_mem_polynomialRange n b
    have hyRange := hy hyFinite
    have hsum :
        (⟨DFinsupp.single (n : NatOrdinal) b + y,
            (mem_principalFiniteDegreePart_iff _).mpr hfinite⟩ : principalFiniteDegreePart K) =
          finiteDegreeOf K n b +
            (⟨y, (mem_principalFiniteDegreePart_iff y).mpr hyFinite⟩ :
              principalFiniteDegreePart K) := by
      apply Subtype.ext
      change DFinsupp.single (n : NatOrdinal) b + y =
        ((finiteDegreeOf K n b :
          principalFiniteDegreePart K) : PrincipalSubring K) +
            (show PrincipalSubring K from y)
      rw [coe_finiteDegreeOf]
      ext β
      simp only [DFinsupp.add_apply, DirectSum.add_apply]
      rw [DirectSum.of_apply, DFinsupp.single_apply]
    rw [hsum]
    exact A.add_mem hsingle hyRange

end Berarducci
