/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module


import ConwayRefinement.Blueprint
public import
  ConwayRefinement.HahnSeries.OrdinalValue.AlgebraicIndependence.PrincipalRepresentatives
public import ConwayRefinement.Algebra.MvPolynomial.ComponentsSpan

/-!
# The translated truncations of a term `u · q(b_𝓑)` satisfy (p)

Let `q ∈ K[X]` be homogeneous of degree `c`, evaluated at principal-series representatives, and let
`u` be a series
of ordinal value below `ω^(b+1)` whose translated truncations at cutoffs `ζ < 0` have ordinal
value below `ω^b` (for instance a principal series of degree `b`), with `b ⊕ c < α`. The
separation condition (n) for `(b, c, τ)` — `b ⊕ θ < τ` for every `θ < c` — gives, for every
cutoff `ζ ≤ 0`, that `pol((u q(b_𝓑))^{|ζ})_{≥τ}` lies in the ideal `(q)`: the translated
truncations of `u · q(b_𝓑)` satisfy the condition (p) for `(q; τ)`. By the convolution formula,
read in polynomials [Ber00, Lem. 7.5],
`pol((u q(b_𝓑))^{|ζ}) = pol(u^{|ζ}) · q + ∑ pol(u^{|β}) pol(q(b_𝓑)^{|ζ - β})`, the first term lies
in `(q)` and every other term has as a factor the polynomial of a translated truncation of
`q(b_𝓑)` at a cutoff `< 0`, hence has degree below `τ`.
-/

universe v w

open scoped NatOrdinal HahnSeries
open Berarducci HahnSeries MvPolynomial OrdinalGraded

public noncomputable section

namespace Berarducci

variable {K : Type v} [Field K] {ι : Type w} {wt : ι → NatOrdinal} {x : ι → PrincipalSubring K}

namespace Lifts

variable (σ : Lifts wt x) (hx : IsMinimalSystem (Berarducci.principalGrading K) wt x)
  {α : NatOrdinal} (hinj : ∀ β < α, InjectiveAt K wt x β) (hσ : σ.IsPrincipal)
include hinj hσ

/-- **High-degree components of translated truncations of a polynomial multiple.** Under the
displayed ordinal-value and Hessenberg-sum bounds, the components of degree at least `τ` of
`pol((u * q(b_𝓑))^{|ζ})` lie in the principal ideal generated by `q`. -/
@[blueprint "lem:term-truncation-condition"
  (phase := "Translated truncations")
  (title := "High-degree components of translated truncations of a polynomial multiple")
  (statement := /--
    Let $K$ be a field and let $\mathcal B$ be a minimal homogeneous generating
    system of $\widehat{\mathrm P}$, with principal representatives $b_B$.
    Assume evaluation is injective in every degree below $\alpha$. Let
    $Q\in K[X_B:B\in\mathcal B]$ be weighted homogeneous of degree $\sigma$.
    Suppose
    \[
      v_J(u)<\omega^{\rho+1},\qquad
      v_J(u^{|\zeta})<\omega^\rho\quad(\zeta<0),
    \]
    \[
      \rho\oplus\sigma<\alpha,\qquad
      \rho\oplus\theta<\tau\quad(\theta<\sigma).
    \]
    Then, for every $\xi\le0$,
    \[
      \operatorname{pol}_{<\alpha}
        \!\left((uQ(b_B))^{|\xi}\right)_{\ge\tau}
        \in (Q)\subseteq K[X_B:B\in\mathcal B].
    \]
  -/)
  (proof := /--
  By \ref{prop:polynomial-representative-exists}, translated truncations of
  ordinal value below $\omega^\alpha$ have polynomial representatives of
  degree below $\alpha$; \ref{prop:polynomial-evaluation-ordinal-value} gives
  the needed uniqueness.
  Expand the translated truncation of $uQ(b_B)$ by convolution. The endpoint
  term is $\operatorname{pol}_{<\alpha}(u^{|\xi})Q$, so its components of
  degree at least $\tau$ lie in $(Q)$. In every other term the $Q(b_B)$ factor
  is translated-truncated at a negative cutoff. By
  \ref{lem:principal-representatives-homogeneous-polynomial-truncation}, its polynomial
  representative has degree below $\sigma$, while the representative of the
  $u$ factor has degree at most $\rho$. Thus $\rho\oplus\theta<\tau$ makes the
  component of degree at least $\tau$ vanish. Summing proves the claim.
  -/)]
theorem componentsGE_pol_translatedTruncation_mul_aeval_mem {q : MvPolynomial ι K}
    {c : NatOrdinal} (hq : IsWeightedHomogeneous wt q c) {u : Series K} {b : NatOrdinal}
    (hu : ordinalValue u < ω^ (b + 1))
    (hucut : ∀ ζ : ℝ, ζ < 0 → ordinalValue (translatedTruncation (u : K⟦ℝ⟧) ζ) < ω^ b)
    (hbc : b + c < α) {τ : NatOrdinal} (hsep : ∀ θ, θ < c → b + θ < τ) {ζ : ℝ} (hζ : ζ ≤ 0) :
    componentsGE wt τ
        (σ.pol hx α (translatedTruncation ((u * aeval σ.lift q : Series K) : K⟦ℝ⟧) ζ)) ∈
      Ideal.span (Set.range fun _ : Unit ↦ q) := by
  classical
  have hwt : ∀ i, wt i ≠ 0 := hx.ne_zero
  have hbα : b < α := (NatOrdinal.le_add_right).trans_lt hbc
  have hcα : c < α := (NatOrdinal.le_add_left).trans_lt hbc
  set v : Series K := aeval σ.lift q with hvdef
  have hv : ordinalValue v < ω^ (c + 1) := (σ.aeval_represents hq).ordinalValue_lt
  have hvcut : ∀ ξ : ℝ, ξ < 0 → ordinalValue (translatedTruncation (v : K⟦ℝ⟧) ξ) < ω^ c :=
    fun ξ hξ ↦ hσ.ordinalValue_translatedTruncation_aeval_lt hwt hq hξ
  -- the convolution index set, with the endpoints added
  set S : Finset ℝ := insert 0 (insert ζ (convolutionIndex (u : K⟦ℝ⟧) (v : K⟦ℝ⟧) ζ)) with hSdef
  have hS1 : convolutionIndex (u : K⟦ℝ⟧) (v : K⟦ℝ⟧) ζ ⊆ S :=
    (Finset.subset_insert _ _).trans (Finset.subset_insert _ _)
  have hS2 : ∀ β ∈ S, ζ ≤ β ∧ β ≤ 0 := by
    intro β hβ
    rw [hSdef, Finset.mem_insert, Finset.mem_insert] at hβ
    rcases hβ with rfl | rfl | hβ
    · exact ⟨hζ, le_rfl⟩
    · exact ⟨le_rfl, hζ⟩
    · exact mem_Icc_of_mem_convolutionIndex hβ
  -- ordinal value bounds on the translated truncations of the factors
  have hucut' : ∀ β, β ≤ 0 → ordinalValue (translatedTruncation (u : K⟦ℝ⟧) β) < ω^ (b + 1) := by
    intro β hβ
    rcases lt_or_eq_of_le hβ with h | rfl
    · exact (hucut β h).trans (NatOrdinal.wpow_lt_wpow.mpr (lt_add_one b))
    · rw [translatedTruncation_zero]; exact hu
  have hvcut' : ∀ β, β ≤ 0 → ordinalValue (translatedTruncation (v : K⟦ℝ⟧) β) < ω^ (c + 1) := by
    intro β hβ
    rcases lt_or_eq_of_le hβ with h | rfl
    · exact (hvcut β h).trans (NatOrdinal.wpow_lt_wpow.mpr (lt_add_one c))
    · rw [translatedTruncation_zero]; exact hv
  have hb1 : b + 1 ≤ α := Order.add_one_le_of_lt hbα
  have hc1 : c + 1 ≤ α := Order.add_one_le_of_lt hcα
  -- the a priori ordinal value bound on the translated truncation of the product
  have hprod : ordinalValue (translatedTruncation ((u * v : Series K) : K⟦ℝ⟧) ζ) < ω^ α := by
    have hgerm : toGerm (translatedTruncation ((u * v : Series K) : K⟦ℝ⟧) ζ) =
        toGerm (∑ β ∈ S, translatedTruncation (u : K⟦ℝ⟧) β *
          translatedTruncation (v : K⟦ℝ⟧) (ζ - β)) := by
      rw [← germAt_apply, Subring.coe_mul, germAt_mul_of_subset u v ζ hS1, map_sum]
      simp only [germAt_apply, map_mul]
    rw [ordinalValue_eq_of_sub_mem_negativeMonomialIdeal (toGerm_eq_toGerm_iff.mp hgerm)]
    refine ordinalValue_sum_lt _ _ (NatOrdinal.wpow_pos α) fun β hβ ↦ ?_
    obtain ⟨hζβ, hβ0⟩ := hS2 β hβ
    refine (ordinalValue_mul_lt_wpow_add_one (hucut' β hβ0)
      (hvcut' (ζ - β) (by linarith))).trans_le (NatOrdinal.wpow_le_wpow.mpr ?_)
    exact Order.add_one_le_of_lt hbc
  -- the term bounds for the convolution formula
  have hterm : ∀ β ∈ S,
      ordinalValue (translatedTruncation (u : K⟦ℝ⟧) β) < ω^ α ∧
      ordinalValue (translatedTruncation (v : K⟦ℝ⟧) (ζ - β)) < ω^ α ∧
      DegreeLT wt (σ.pol hx α (translatedTruncation (u : K⟦ℝ⟧) β) *
        σ.pol hx α (translatedTruncation (v : K⟦ℝ⟧) (ζ - β))) α := by
    intro β hβ
    obtain ⟨hζβ, hβ0⟩ := hS2 β hβ
    have h1 := hucut' β hβ0
    have h2 := hvcut' (ζ - β) (by linarith)
    refine ⟨h1.trans_le (NatOrdinal.wpow_le_wpow.mpr hb1),
      h2.trans_le (NatOrdinal.wpow_le_wpow.mpr hc1), ?_⟩
    have hdu : DegreeLE wt (σ.pol hx α (translatedTruncation (u : K⟦ℝ⟧) β)) b :=
      degreeLT_add_one_iff_degreeLE.mp (σ.pol_degreeLT_of_lt hx hinj hb1 h1)
    have hdv : DegreeLE wt (σ.pol hx α (translatedTruncation (v : K⟦ℝ⟧) (ζ - β))) c :=
      degreeLT_add_one_iff_degreeLE.mp (σ.pol_degreeLT_of_lt hx hinj hc1 h2)
    exact (hdu.mul hdv).degreeLT hbc
  rw [σ.pol_translatedTruncation_mul_eq_sum hx hinj hS1 hprod hterm, componentsGE_sum]
  refine Ideal.sum_mem _ fun β hβ ↦ ?_
  obtain ⟨hζβ, hβ0⟩ := hS2 β hβ
  rcases eq_or_lt_of_le hζβ with rfl | hlt
  · -- the term `pol(u^{|ζ}) · q`
    rw [sub_self, translatedTruncation_zero, hvdef, σ.pol_aeval hx hinj (hq.degreeLT hcα)]
    exact componentsGE_mem_span wt (fun _ : Unit ↦ hq)
      (Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨(), rfl⟩)) τ
  · -- a translated truncation of `q(b_𝓑)` at a cutoff `< 0`: degree below `τ`
    have hdu : DegreeLE wt (σ.pol hx α (translatedTruncation (u : K⟦ℝ⟧) β)) b :=
      degreeLT_add_one_iff_degreeLE.mp (σ.pol_degreeLT_of_lt hx hinj hb1 (hucut' β hβ0))
    have hdv : DegreeLT wt (σ.pol hx α (translatedTruncation (v : K⟦ℝ⟧) (ζ - β))) c :=
      σ.pol_degreeLT_of_lt hx hinj hcα.le (hvcut (ζ - β) (by linarith))
    rw [componentsGE_eq_zero_of_forall_lt wt fun d hd ↦ ?_]
    · exact zero_mem _
    obtain ⟨d₁, hd₁, d₂, hd₂, hw⟩ := exists_add_eq_weight_of_mem_support_mul (wt := wt) hd
    rw [← hw]
    calc Finsupp.weight wt d₁ + Finsupp.weight wt d₂
        ≤ b + Finsupp.weight wt d₂ := add_le_add_left ((degreeLE_iff).mp hdu d₁ hd₁) _
      _ < τ := hsep _ ((degreeLT_iff).mp hdv d₂ hd₂)

end Lifts

end Berarducci
