/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module


import ConwayRefinement.Blueprint
public import ConwayRefinement.HahnSeries.OrdinalValue.AlgebraicIndependence.DerivationIdeal
public import ConwayRefinement.HahnSeries.OrdinalValue.AlgebraicIndependence.OrdinalValueCutoffs
public import ConwayRefinement.Algebra.MvPolynomial.ComponentsSpan
public import ConwayRefinement.SetTheory.Ordinal.FinitePart

/-!
# Ideal membership of a class from the condition (p) on its translated truncations

Let `q j ∈ K[X]` be finitely many homogeneous polynomials `Q_1, …, Q_m` of degrees `c j` that are
zero or limits, and let `τ + 1 < α`, evaluation being injective below `α`. If `u ∈ J_{ω^(τ+2)}`
and, for all real cutoffs `δ < 0` sufficiently close to `0`, the translated truncation `u^{|δ}`
lies in `J_{ω^(τ+1)}` and the translated truncations satisfy (p) for `(Q_1, …, Q_m; τ)` — the part
`pol(u^{|δ})_{≥τ}` of degree at least `τ` of the polynomial of `u^{|δ}` modulo `J` lies in the
ideal `(Q_1, …, Q_m) ⊆ K[X]` — then the class of `u` in `P_{τ+1}` lies in the ideal
`(Q_1(𝓑), …, Q_m(𝓑)) ⊆ P̂`.

This is ideal membership of a class from ideal membership of its derivative
(`mem_span_of_principalSubringDerivation_eq_coe`) applied to the class of `u`: its derivative is the
class in `Fun_{0⁻}(P̂)` of `δ ↦ u^{|δ} + J_{ω^τ}`, and `u^{|δ} + J_{ω^τ} ∈ P_τ` is the evaluation
`pol(u^{|δ})_τ(𝓑)` of the degree-`τ` component of the polynomial of `u^{|δ}`, an element of the
ideal.
-/

universe v w

open scoped NatOrdinal HahnSeries
open Berarducci HahnSeries MvPolynomial DirectSum OrdinalGraded

public noncomputable section

namespace Berarducci

variable {K : Type v} [Field K] {ι : Type w} {wt : ι → NatOrdinal} {x : ι → PrincipalSubring K}

/-- Evaluation carries the ideal of `K[X]` generated by the `q j` into the ideal of `P̂` generated
by the evaluations `(q j)(𝓑)`. -/
theorem aeval_mem_span_range_of_mem_span {ι' : Type*} {q : ι' → MvPolynomial ι K}
    {P : MvPolynomial ι K} (hP : P ∈ Ideal.span (Set.range q)) :
    aeval x P ∈ Ideal.span (Set.range fun j ↦ aeval x (q j)) := by
  have := Ideal.mem_map_of_mem (aeval x : MvPolynomial ι K →ₐ[K] PrincipalSubring K).toRingHom hP
  rw [Ideal.map_span, ← Set.range_comp] at this
  exact this

/-- `τ + 1` has positive finite part. -/
theorem constantCoeff_add_one_pos (τ : NatOrdinal) : 0 < (τ + 1).constantCoeff := by
  have := NatOrdinal.constantCoeff_add_natCast τ 1
  rw [Nat.cast_one] at this
  rw [this]
  exact Nat.succ_pos _

/-- `(τ + 1) ⊖ 1 = τ`: removing `1` from the finite part of `τ + 1` gives back `τ`. -/
theorem removeNat_one_add_one (τ : NatOrdinal) : (τ + 1).removeNat 1 = τ := by
  have h := NatOrdinal.removeNat_add_natCast (a := τ + 1) (n := 1) (by
    have := constantCoeff_add_one_pos τ
    omega)
  rw [Nat.cast_one] at h
  exact add_right_cancel h

namespace Lifts

variable (σ : Lifts wt x) (hx : IsMinimalSystem (principalGrading K) wt x) {α : NatOrdinal}
  (hinj : ∀ β < α, InjectiveAt K wt x β)
include hinj

/-- **Ideal membership in `P_(τ+1)` from translated truncations.** For `τ + 1 < α` and
`u ∈ J_{ω^(τ+2)}`, suppose that the translated truncations `u^{|δ}` for `-ε < δ < 0`
lie in `J_{ω^(τ+1)}` and that `pol(u^{|δ})_{≥τ}` lies in the ideal `(q_1, …, q_m)`.
Then the class of `u` in `P_{τ+1}` lies in the ideal of `P̂` generated by the evaluations
`(q j)(𝓑)`. -/
@[blueprint "lem:lower-below-successor"
  (phase := "Translated truncations")
  (title := "Ideal membership in $\\mathrm P_{\\tau+1}$ from translated truncations")
  (statement := /--
    Let $K$ be a field, let $(x_i)_{i\in I}$ be a minimal homogeneous
    generating system of $\Ph$, with $x_i\in\Prin_{w_i}$, and choose series
    $b_i$ representing $x_i$. Fix
    $\alpha<\omega_1$, and assume that evaluation at $(x_i)$ is injective in
    every weighted degree below $\alpha$.

    Let $Q_1,\ldots,Q_m\in K[X_i:i\in I]$ be weighted homogeneous of degrees
    $\sigma_1,\ldots,\sigma_m$, each a limit ordinal or $0$. Let
    $\tau+1<\alpha$, and let $u\in\Kser$ satisfy
    $\vJ(u)<\omega^{\tau+2}$. Suppose there is $\varepsilon>0$ such that, for
    every $-\varepsilon<\gamma<0$,
    \[
      \vJ(\trunc u\gamma)<\omega^{\tau+1},\qquad
      \partGE{\pol(\trunc u\gamma)}{\tau}\in(Q_1,\ldots,Q_m).
    \]
    Then the class $u+J_{\omega^{\tau+1}}\in\Prin_{\tau+1}$ belongs, inside
    $\Ph$, to the ideal generated by
    $Q_1(x_i),\ldots,Q_m(x_i)$.
  -/)
  (proof := /--
  For every $\gamma\in(-\varepsilon,0)$,
  \ref{lem:polynomial-homogeneous-component-represents-class} identifies the
  class of $\trunc u\gamma$ in $\Prin_\tau$ with the evaluation of the
  degree-$\tau$ component of $\pol(\trunc u\gamma)$. Since the part of degree
  at least $\tau$ lies in the homogeneous ideal $(Q_1,\ldots,Q_m)$, its
  degree-$\tau$ component does too. Hence every value of the derivative of
  $u+J_{\omega^{\tau+1}}$, sufficiently close to $0$, lies in the ideal
  generated by the $Q_j(x_i)$. Applying \ref{prop:ideal-from-derivative} gives
  the asserted ideal membership in $\Ph$.
  -/)]
theorem of_principalComponentMk_mem_span_of_forall_componentsGE_mem {ι' : Type*} [Finite ι']
    {q : ι' → MvPolynomial ι K} {c : ι' → NatOrdinal}
    (hq : ∀ j, IsWeightedHomogeneous wt (q j) (c j)) (hc : ∀ j, (c j).constantCoeff = 0)
    {τ : NatOrdinal} (hτ : τ + 1 < α) {u : Series K} (hu : ordinalValue u < ω^ (τ + 1 + 1))
    {ε : ℝ} (hε : 0 < ε)
    (hdrop : ∀ δ : ℝ, -ε < δ → δ < 0 →
      ordinalValue (translatedTruncation (u : K⟦ℝ⟧) δ) < ω^ (τ + 1))
    (htrunc : ∀ δ : ℝ, -ε < δ → δ < 0 →
      componentsGE wt τ (σ.pol hx α (translatedTruncation (u : K⟦ℝ⟧) δ)) ∈
        Ideal.span (Set.range q)) :
    DirectSum.of (PrincipalComponent K) (τ + 1) (principalComponentMk (τ + 1) u hu) ∈
      Ideal.span (Set.range fun j ↦ aeval x (q j)) := by
  classical
  have hα1 : 0 < (τ + 1).constantCoeff := constantCoeff_add_one_pos τ
  have hrem : (τ + 1).removeNat 1 = τ := removeNat_one_add_one τ
  have hτα : τ < α := (lt_add_one τ).trans hτ
  have hq' : ∀ j, aeval x (q j) ∈ principalGrading K (c j) :=
    fun j ↦ aeval_mem_of_forall_mem hx.mem (hq j)
  -- the derivative of the class of `u`, as a function at `0⁻`
  let f : ℝ → PrincipalSubring K := fun δ ↦
    if -ε < δ ∧ δ < 0 then
      DirectSum.of (PrincipalComponent K) ((τ + 1).removeNat 1) (derivAt (τ + 1) u δ)
    else 0
  have hΔ : principalSubringDerivation K
      (DirectSum.of (PrincipalComponent K) (τ + 1) (principalComponentMk (τ + 1) u hu)) =
        (f : FunAtZeroMinus (PrincipalSubring K)) := by
    rw [principalSubringDerivation_of, principalComponentDerivation_principalComponentMk hα1]
    exact (funAtZeroMinus_coe_eq_iff_exists _ _).mpr ⟨ε, hε, fun δ h1 h2 ↦ by
      simp only [f, if_pos (And.intro h1 h2)]⟩
  have hf : ∀ δ, f δ ∈ Ideal.span (Set.range fun j ↦ aeval x (q j)) := by
    intro δ
    by_cases h : -ε < δ ∧ δ < 0
    · simp only [f, if_pos h]
      have hδ : ordinalValue (translatedTruncation (u : K⟦ℝ⟧) δ) <
          ω^ ((τ + 1).removeNat 1 + 1) := by
        rw [hrem]; exact hdrop δ h.1 h.2
      rw [derivAt_eq (τ + 1) u δ hδ, of_principalComponentMk_congr hrem _ hδ (by
        rw [← hrem]; exact hδ)]
      have hrep := σ.represents_aeval_weightedHomogeneousComponent_pol hx hinj hτα
        (hdrop δ h.1 h.2)
      rw [hrep.of_principalComponentMk]
      exact aeval_mem_span_range_of_mem_span
        (weightedHomogeneousComponent_mem_span_of_componentsGE_mem wt hq (htrunc δ h.1 h.2) le_rfl)
    · simp only [f, if_neg h]
      exact Ideal.zero_mem _
  exact mem_span_of_principalSubringDerivation_eq_coe hq' hc hα1 (of_mem_principalGrading _ _) hf hΔ

end Lifts

end Berarducci
