/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.SetTheory.Ordinal.FinitePart
public import Mathlib.RingTheory.GradedAlgebra.Basic
public import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
public import Mathlib.RingTheory.Ideal.Quotient.Operations

import Mathlib.LinearAlgebra.DFinsupp

/-!
# Graded algebras over countable ordinals: the ideals `I_{≥j}` and the quotient `A/I`

Let `A` (Lean `R`) be a commutative algebra over a field `E`, graded by the natural numbers'
ordinal extension `NatOrdinal` with its natural sum `⊕` (Lean `+`). The paper's setting has
`A_0 = E`; this file uses only the grading. For `j ∈ ℕ`, the ideal `I_{≥j}` is generated by the
homogeneous elements of finite degree at least `j`,

`I_{≥j} = ∑_{j ≤ n < ω} A_n A`,

with `I_{≥0} = A` and `I_{≥i} I_{≥j} ⊆ I_{≥i+j}`; the `I_{≥j}` are homogeneous and decreasing.
Every homogeneous element of `I_{≥j}` is a finite sum of products `B C` with `B ∈ A_e`, `e ≥ j`
finite, and `C` homogeneous of complementary degree, so `I_{≥j} ∩ A_δ = 0` as soon as `j` exceeds
the finite part of `δ` (the constant Cantor coefficient, Lean `δ.constantCoeff`). The quotient
`A/I`, `I = I_{≥1}`, inherits the grading: the images `(A/I)_β = π(A_β)` form an internal direct
sum decomposition of `A/I`, making it a graded `E`-algebra.

The paper writes `A/I` (in the application, `P̂/I`) and calls it the quotient; its one use of
the word "fibre" is "`P̂/I ≅ P̂ ⊗_{P̂_{<ω}} K`, the fibre of `P̂` over the quotient map
`P̂_{<ω} → P̂_{<ω}/(P̂_{<ω})₊ = K`". "Fibre" is this Lean's noun for it: `Fibre 𝒜` is `A/I`,
`fibreIdeal 𝒜` is `I`, `fibreMap 𝒜` is `π`, and `fibreGrade 𝒜 β` is `(A/I)_β`.
-/

universe u v

open scoped DirectSum

public noncomputable section

namespace LoweringDerivation

variable {E : Type u} {R : Type v} [Field E] [CommRing R] [Algebra E R]
variable (𝒜 : NatOrdinal → Submodule E R) [GradedAlgebra 𝒜]

/-! ### The ideals `I_{≥j}` -/

/-- The generators of `I_{≥j}`: the homogeneous elements of finite degree at least `j`. -/
def idealGEGenerators (j : ℕ) : Set R :=
  ⋃ e : ℕ, ⋃ (_ : j ≤ e), (𝒜 (e : NatOrdinal) : Set R)

/-- The ideal `I_{≥j} = ∑_{j ≤ n < ω} A_n A` generated by the homogeneous elements of finite degree
at least `j`. -/
def idealGE (j : ℕ) : Ideal R :=
  Ideal.span (idealGEGenerators 𝒜 j)

omit [GradedAlgebra 𝒜] in
theorem idealGE_eq_span (j : ℕ) : idealGE 𝒜 j = Ideal.span (idealGEGenerators 𝒜 j) := (rfl)

omit [GradedAlgebra 𝒜] in
theorem mem_idealGEGenerators_iff (j : ℕ) (x : R) :
    x ∈ idealGEGenerators 𝒜 j ↔ ∃ e : ℕ, j ≤ e ∧ x ∈ 𝒜 (e : NatOrdinal) := by
  simp [idealGEGenerators]

omit [GradedAlgebra 𝒜] in
theorem mem_idealGE_of_mem {j e : ℕ} (hje : j ≤ e) {x : R}
    (hx : x ∈ 𝒜 (e : NatOrdinal)) :
    x ∈ idealGE 𝒜 j :=
  Ideal.subset_span ((mem_idealGEGenerators_iff 𝒜 j x).mpr ⟨e, hje, hx⟩)

omit [GradedAlgebra 𝒜] in
theorem idealGE_antitone {i j : ℕ} (hij : i ≤ j) :
    idealGE 𝒜 j ≤ idealGE 𝒜 i :=
  Ideal.span_mono fun x hx ↦ by
    obtain ⟨e, hje, hxe⟩ := (mem_idealGEGenerators_iff 𝒜 j x).mp hx
    exact (mem_idealGEGenerators_iff 𝒜 i x).mpr ⟨e, hij.trans hje, hxe⟩

theorem idealGE_zero : idealGE 𝒜 0 = ⊤ :=
  (Ideal.eq_top_iff_one _).mpr (mem_idealGE_of_mem 𝒜 (e := 0) le_rfl
    (by simpa using SetLike.one_mem_graded 𝒜))

theorem idealGE_mul_le (i j : ℕ) :
    idealGE 𝒜 i * idealGE 𝒜 j ≤ idealGE 𝒜 (i + j) := by
  rw [idealGE, idealGE, Ideal.span_mul_span]
  refine Ideal.span_le.mpr ?_
  rintro _ ⟨x, hx, y, hy, rfl⟩
  obtain ⟨e, hie, hxe⟩ := (mem_idealGEGenerators_iff 𝒜 i x).mp hx
  obtain ⟨e', hje', hye'⟩ := (mem_idealGEGenerators_iff 𝒜 j y).mp hy
  refine Ideal.subset_span ((mem_idealGEGenerators_iff 𝒜 (i + j) (x * y)).mpr
    ⟨e + e', Nat.add_le_add hie hje', ?_⟩)
  rw [Nat.cast_add]
  exact SetLike.mul_mem_graded hxe hye'

theorem mul_mem_idealGE {i j : ℕ} {x y : R} (hx : x ∈ idealGE 𝒜 i)
    (hy : y ∈ idealGE 𝒜 j) : x * y ∈ idealGE 𝒜 (i + j) :=
  idealGE_mul_le 𝒜 i j (Ideal.mul_mem_mul hx hy)

theorem idealGE_isHomogeneous (j : ℕ) : (idealGE 𝒜 j).IsHomogeneous 𝒜 :=
  Ideal.homogeneous_span 𝒜 _ fun x hx ↦ by
    obtain ⟨e, -, hxe⟩ := (mem_idealGEGenerators_iff 𝒜 j x).mp hx
    exact ⟨(e : NatOrdinal), hxe⟩

/-! ### Homogeneous presentations and the vanishing `I_{≥j} ∩ A_δ = 0` -/

/-- The degree-`δ` component of a product `r * g` with `g` homogeneous of degree `e` is
`r_β * g` when `β ⊕ e = δ`. -/
theorem decompose_mul_of_right_mem_eq {r g : R} {e β δ : NatOrdinal} (hg : g ∈ 𝒜 e)
    (hβ : β + e = δ) :
    (DirectSum.decompose 𝒜 (r * g) δ : R) = (DirectSum.decompose 𝒜 r β : R) * g := by
  rw [DirectSum.decompose_mul, DirectSum.decompose_of_mem 𝒜 hg]
  exact DirectSum.coe_mul_of_apply_aux 𝒜 _ _ fun x ↦
    ⟨fun hx ↦ add_right_cancel (hx.trans hβ.symm), fun hx ↦ hx ▸ hβ⟩

/-- The degree-`δ` component of `r * g`, with `g` homogeneous of degree `e`, vanishes when no
degree `β` satisfies `β ⊕ e = δ`. -/
theorem decompose_mul_of_right_mem_eq_zero {r g : R} {e δ : NatOrdinal} (hg : g ∈ 𝒜 e)
    (h : ∀ β, β + e ≠ δ) : (DirectSum.decompose 𝒜 (r * g) δ : R) = 0 := by
  classical
  rw [DirectSum.decompose_mul, DirectSum.decompose_of_mem 𝒜 hg,
    DirectSum.coe_mul_apply_eq_dfinsuppSum, DFinsupp.sum_comm]
  refine (DFinsupp.sum_single_index ?_).trans (DFinsupp.sum_eq_zero fun β ↦ if_neg (h β))
  simp

/-- The degree-`δ` component of an element of the span of homogeneous generators is a finite sum
of products `r_k * g_k`, with `g_k` a generator, of degree `e g_k`, and `r_k` a homogeneous
component, of degree `β_k` with `β_k ⊕ e g_k = δ`, of the coefficient of `g_k`. -/
theorem exists_decompose_eq_sum_of_mem_span {S : Set R} (e : S → NatOrdinal)
    (hS : ∀ g : S, (g : R) ∈ 𝒜 (e g)) {x : R} (hx : x ∈ Ideal.span S) (δ : NatOrdinal) :
    ∃ (κ : Type) (_ : Fintype κ) (g : κ → S) (r : κ → R) (β : κ → NatOrdinal),
      (∀ k, r k ∈ 𝒜 (β k)) ∧ (∀ k, β k + e (g k) = δ) ∧
        (DirectSum.decompose 𝒜 x δ : R) = ∑ k, r k * g k := by
  classical
  obtain ⟨n, c, g, hsum⟩ := Submodule.mem_span_set'.mp hx
  let κ := {i : Fin n // ∃ β, β + e (g i) = δ}
  choose β hβ using fun k : κ ↦ k.2
  refine ⟨κ, inferInstance, fun k ↦ g k.1, fun k ↦ (DirectSum.decompose 𝒜 (c k.1) (β k) : R), β,
    fun k ↦ (DirectSum.decompose 𝒜 (c k.1) (β k)).2, hβ, ?_⟩
  let β' : Fin n → NatOrdinal := fun i ↦
    if hP : ∃ β, β + e (g i) = δ then β ⟨i, hP⟩ else 0
  have hterm : ∀ i : Fin n, (DirectSum.decompose 𝒜 (c i • (g i : R)) δ : R) =
      if ∃ β, β + e (g i) = δ then (DirectSum.decompose 𝒜 (c i) (β' i) : R) * g i else 0 := by
    intro i
    rw [smul_eq_mul]
    split_ifs with hP
    · rw [show β' i = β ⟨i, hP⟩ from dif_pos hP]
      exact decompose_mul_of_right_mem_eq 𝒜 (hS (g i)) (hβ ⟨i, hP⟩)
    · exact decompose_mul_of_right_mem_eq_zero 𝒜 (hS (g i)) fun β hβ ↦ hP ⟨β, hβ⟩
  rw [← hsum, DirectSum.decompose_sum, DirectSum.sum_apply, Submodule.coe_sum,
    Finset.sum_congr rfl fun i _ ↦ hterm i, ← Finset.sum_filter,
    Finset.sum_subtype (Finset.univ.filter fun i : Fin n ↦ ∃ β, β + e (g i) = δ)
      (p := fun i : Fin n ↦ ∃ β, β + e (g i) = δ) (fun i ↦ by simp)]
  exact Finset.sum_congr rfl fun k _ ↦ by rw [show β' k.1 = β k from dif_pos k.2]

/-- A homogeneous element of `I_{≥j} ∩ A_δ` is a finite sum of products `a * b` with `a ∈ A_e`,
`e ≥ j` finite, and `b` homogeneous of a degree `β` with `e ⊕ β = δ`. -/
theorem exists_homogeneous_presentation {j : ℕ} {δ : NatOrdinal} {x : R} (hxδ : x ∈ 𝒜 δ)
    (hx : x ∈ idealGE 𝒜 j) :
    ∃ (κ : Type) (_ : Fintype κ) (e : κ → ℕ) (a b : κ → R) (β : κ → NatOrdinal),
      (∀ k, j ≤ e k) ∧ (∀ k, a k ∈ 𝒜 (e k : NatOrdinal)) ∧
        (∀ k, b k ∈ 𝒜 (β k)) ∧ (∀ k, (e k : NatOrdinal) + β k = δ) ∧
        x = ∑ k, a k * b k := by
  choose e hje hge using fun g : idealGEGenerators 𝒜 j ↦ (mem_idealGEGenerators_iff 𝒜 j g).mp g.2
  obtain ⟨κ, _, g, r, β, hr, hβ, hx'⟩ := exists_decompose_eq_sum_of_mem_span 𝒜
    (fun g ↦ (e g : NatOrdinal)) hge (by rwa [idealGE_eq_span] at hx) δ
  refine ⟨κ, inferInstance, fun k ↦ e (g k), fun k ↦ g k, r, β, fun k ↦ hje (g k),
    fun k ↦ hge (g k), hr, fun k ↦ by rw [add_comm]; exact hβ k, ?_⟩
  rw [← DirectSum.decompose_of_mem_same 𝒜 hxδ, hx']
  exact Finset.sum_congr rfl fun k _ ↦ mul_comm _ _

/-- `I_{≥j} ∩ A_δ = 0` once `j` exceeds the finite part of `δ` (its constant Cantor
coefficient): for `δ = λ + n` with `n < j`, no product `B C` with `B ∈ A_e`, `e ≥ j` finite, has
degree `δ`. -/
theorem eq_zero_of_mem_idealGE_of_constantCoeff_lt {j : ℕ} {δ : NatOrdinal} {x : R}
    (hxδ : x ∈ 𝒜 δ) (hx : x ∈ idealGE 𝒜 j) (hj : δ.constantCoeff < j) : x = 0 := by
  obtain ⟨κ, _, e, a, b, β, hje, -, -, heβ, rfl⟩ :=
    exists_homogeneous_presentation 𝒜 hxδ hx
  refine Finset.sum_eq_zero fun k _ ↦ (absurd ?_ (not_lt.mpr (hje k)))
  have h := congrArg NatOrdinal.constantCoeff (heβ k)
  rw [NatOrdinal.constantCoeff_add, NatOrdinal.constantCoeff_natCast] at h
  omega

/-! ### The quotient `A/I` and its grading -/

/-- The ideal `I = I_{≥1}` generated by the elements of positive finite degree. -/
abbrev fibreIdeal : Ideal R := idealGE 𝒜 1

/-- The quotient `A/I`, `I = I_{≥1}`; for `A = P̂` the paper's `P̂/I`. -/
abbrev Fibre : Type v := R ⧸ fibreIdeal 𝒜

/-- The quotient map `π : A → A/I`. -/
abbrev fibreMap : R →ₐ[E] Fibre 𝒜 := Ideal.Quotient.mkₐ E (fibreIdeal 𝒜)

omit [GradedAlgebra 𝒜] in
theorem fibreMap_surjective : Function.Surjective (fibreMap 𝒜) :=
  Ideal.Quotient.mkₐ_surjective E _

omit [GradedAlgebra 𝒜] in
theorem fibreMap_eq_zero_iff (x : R) : fibreMap 𝒜 x = 0 ↔ x ∈ fibreIdeal 𝒜 :=
  Ideal.Quotient.eq_zero_iff_mem

/-- The degree-`β` part `(A/I)_β = π(A_β)` of the quotient. -/
def fibreGrade (β : NatOrdinal) : Submodule E (Fibre 𝒜) :=
  (𝒜 β).map (fibreMap 𝒜).toLinearMap

omit [GradedAlgebra 𝒜] in
theorem fibreMap_mem_fibreGrade {β : NatOrdinal} {x : R} (hx : x ∈ 𝒜 β) :
    fibreMap 𝒜 x ∈ fibreGrade 𝒜 β :=
  ⟨x, hx, rfl⟩

omit [GradedAlgebra 𝒜] in
theorem exists_mem_of_mem_fibreGrade {β : NatOrdinal} {c : Fibre 𝒜}
    (hc : c ∈ fibreGrade 𝒜 β) :
    ∃ x ∈ 𝒜 β, fibreMap 𝒜 x = c :=
  hc

omit [GradedAlgebra 𝒜] in
/-- `(A/I)_n = 0` for `1 ≤ n < ω`: the positive finite degrees vanish in `A/I`. -/
theorem fibreGrade_natCast_eq_bot {n : ℕ} (hn : 1 ≤ n) : fibreGrade 𝒜 (n : NatOrdinal) = ⊥ := by
  rw [eq_bot_iff]
  rintro c ⟨x, hx, rfl⟩
  rw [Submodule.mem_bot, AlgHom.toLinearMap_apply, fibreMap_eq_zero_iff]
  exact mem_idealGE_of_mem 𝒜 hn hx

theorem fibreGrade_mul_le (α β : NatOrdinal) :
    fibreGrade 𝒜 α * fibreGrade 𝒜 β ≤ fibreGrade 𝒜 (α + β) := by
  rw [fibreGrade, fibreGrade, fibreGrade]
  refine Submodule.mul_le.mpr ?_
  rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩
  exact ⟨x * y, SetLike.mul_mem_graded hx hy, map_mul (fibreMap 𝒜) x y⟩

theorem mul_mem_fibreGrade {α β : NatOrdinal} {c d : Fibre 𝒜} (hc : c ∈ fibreGrade 𝒜 α)
    (hd : d ∈ fibreGrade 𝒜 β) : c * d ∈ fibreGrade 𝒜 (α + β) :=
  fibreGrade_mul_le 𝒜 α β (Submodule.mul_mem_mul hc hd)

theorem pow_mem_fibreGrade {α : NatOrdinal} {c : Fibre 𝒜} (hc : c ∈ fibreGrade 𝒜 α)
    (n : ℕ) :
    c ^ n ∈ fibreGrade 𝒜 (n • α) := by
  induction n with
  | zero =>
    rw [pow_zero, zero_smul]
    exact fibreMap_mem_fibreGrade 𝒜 (SetLike.one_mem_graded 𝒜)
  | succ n ih =>
    rw [pow_succ, succ_nsmul]
    exact mul_mem_fibreGrade 𝒜 ih hc

/-- `I ∩ A_0 = 0`. -/
theorem fibreIdeal_inf_grade_zero : (fibreIdeal 𝒜).restrictScalars E ⊓ 𝒜 0 = ⊥ := by
  rw [eq_bot_iff]
  intro y hy
  obtain ⟨hyW, hyδ⟩ := Submodule.mem_inf.mp hy
  rw [Submodule.restrictScalars_mem] at hyW
  rw [Submodule.mem_bot]
  exact eq_zero_of_mem_idealGE_of_constantCoeff_lt 𝒜 hyδ hyW
    (by rw [NatOrdinal.constantCoeff_zero]; exact Nat.one_pos)

/-- `A/I ≠ 0`: `1 ∉ I`. -/
theorem one_notMem_fibreIdeal [Nontrivial R] : (1 : R) ∉ fibreIdeal 𝒜 := fun h ↦
  one_ne_zero ((Submodule.mem_bot E).mp ((fibreIdeal_inf_grade_zero 𝒜).le
    (Submodule.mem_inf.mpr ⟨(Submodule.restrictScalars_mem E _ _).mpr h,
      SetLike.one_mem_graded 𝒜⟩)))

instance [Nontrivial R] : Nontrivial (Fibre 𝒜) :=
  Ideal.Quotient.nontrivial_iff.mpr fun h ↦ one_notMem_fibreIdeal 𝒜 (h ▸ Submodule.mem_top)

/-- `I` is homogeneous: the homogeneous components of an element of `I` lie in `I`. -/
theorem decompose_mem_fibreIdeal {x : R} (hx : x ∈ fibreIdeal 𝒜) (δ : NatOrdinal) :
    (DirectSum.decompose 𝒜 x δ : R) ∈ fibreIdeal 𝒜 :=
  idealGE_isHomogeneous 𝒜 1 δ hx

/-! ### `A/I` is internally graded -/

/-- The `(A/I)_β` form an internal direct sum decomposition of `A/I`. -/
theorem fibreGrade_isInternal : DirectSum.IsInternal (fibreGrade 𝒜) := by
  classical
  refine DirectSum.isInternal_submodule_of_iSupIndep_of_iSup_eq_top ?_ ?_
  · refine iSupIndep_of_dfinsupp_lsum_injective _ ?_
    rw [injective_iff_map_eq_zero]
    intro v hv
    choose x hx hxv using fun α ↦ exists_mem_of_mem_fibreGrade 𝒜 (v α).2
    -- the sum of the lifts lies in `I`, hence so does each homogeneous component
    have hsum : ∑ α ∈ v.support, x α ∈ fibreIdeal 𝒜 := by
      rw [← fibreMap_eq_zero_iff, map_sum]
      simp only [hxv]
      rw [← hv, DFinsupp.lsum_apply_apply, DFinsupp.sumAddHom_apply]
      rfl
    ext α
    by_cases hα : α ∈ v.support
    · have hcomp : (DirectSum.decompose 𝒜 (∑ β ∈ v.support, x β) α : R) = x α := by
        rw [DirectSum.decompose_sum, DirectSum.sum_apply, Submodule.coe_sum,
          Finset.sum_eq_single α]
        · exact DirectSum.decompose_of_mem_same 𝒜 (hx α)
        · intro β _ hβ
          exact DirectSum.decompose_of_mem_ne 𝒜 (hx β) hβ
        · intro h; exact absurd hα h
      have : fibreMap 𝒜 (x α) = 0 := by
        rw [fibreMap_eq_zero_iff, ← hcomp]
        exact decompose_mem_fibreIdeal 𝒜 hsum α
      rw [hxv] at this
      rw [DFinsupp.zero_apply, Submodule.coe_zero]
      exact this
    · rw [DFinsupp.notMem_support_iff.mp hα]
      rfl
  · rw [eq_top_iff]
    intro c _
    obtain ⟨x, rfl⟩ := fibreMap_surjective 𝒜 c
    rw [← DirectSum.sum_support_decompose 𝒜 x, map_sum]
    exact Submodule.sum_mem _ fun α _ ↦ Submodule.mem_iSup_of_mem α
      (fibreMap_mem_fibreGrade 𝒜 (DirectSum.decompose 𝒜 x α).2)

instance : SetLike.GradedMonoid (fibreGrade 𝒜) where
  one_mem := by
    rw [← map_one (fibreMap 𝒜)]
    exact fibreMap_mem_fibreGrade 𝒜 (SetLike.one_mem_graded 𝒜)
  mul_mem _ _ _ _ hc hd := mul_mem_fibreGrade 𝒜 hc hd

/-- `A/I` is a graded `E`-algebra, graded by the `(A/I)_β = π(A_β)`. -/
instance : GradedAlgebra (fibreGrade 𝒜) := { (fibreGrade_isInternal 𝒜).chooseDecomposition with }

end LoweringDerivation
