/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.Algebra.Valuation.DegreeInitialForm
public import Mathlib.Algebra.Algebra.Subalgebra.Basic
public import Mathlib.Algebra.Algebra.Operations


/-!
# The degree over a subalgebra

Let `ν` be a max-additive degree on a commutative ring `R` and let `P` be a subalgebra of `R`.
The level `γ` of the degree over `P` is the `P`-submodule generated by the elements of degree at
most `γ`,

`P · R_{ν ≤ γ}`.

The degree over `P`, `ν_P(t)`, is the least `γ` with `t ∈ P · R_{ν ≤ γ}`; for `ν = deg` on
`K((ℝ^{≤0}))` and `P = S`, the series of finite degree, this is the paper's degree over `S`,
`deg_S`. It is again a max-additive degree, it is bounded by `ν`, it is separated, and every
non-zero element of `P` has degree zero over `P`.
-/

universe u v w

public noncomputable section

namespace MaxAddDegree

variable {R : Type u} {M : Type v} {L : Type w}
variable [CommRing R] [AddCommMonoid M] [LinearOrder M] [IsOrderedCancelAddMonoid M]
variable [CommRing L] [Algebra L R]

/-- The level `P · R_{ν ≤ γ}` of the degree over `P`: the `P`-submodule generated by the elements
of degree at most `γ`. -/
def degreeOverStage (ν : MaxAddDegree R M) (P : Subalgebra L R) (γ : M) : Submodule P R :=
  Submodule.span P (ν.filtrationLE γ : Set R)

variable (ν : MaxAddDegree R M) (P : Subalgebra L R)

omit [IsOrderedCancelAddMonoid M] in
theorem degreeOverStage_le_iff (N : Submodule P R) (γ : M) :
    ν.degreeOverStage P γ ≤ N ↔ (ν.filtrationLE γ : Set R) ⊆ N :=
  Submodule.span_le

omit [IsOrderedCancelAddMonoid M] in
theorem mem_degreeOverStage_of_degree_le {t : R} {γ : M} (ht : ν t ≤ γ) :
    t ∈ ν.degreeOverStage P γ :=
  Submodule.subset_span ((ν.mem_filtrationLE_iff γ t).mpr ht)

omit [IsOrderedCancelAddMonoid M] in
theorem degreeOverStage_mono {γ γ' : M} (h : γ ≤ γ') :
    ν.degreeOverStage P γ ≤ ν.degreeOverStage P γ' :=
  Submodule.span_mono fun t ht ↦ (ν.mem_filtrationLE_iff γ' t).mpr
    (le_trans ((ν.mem_filtrationLE_iff γ t).mp ht) (WithBot.coe_le_coe.mpr h))

theorem degreeOverStage_mul_le (γ γ' : M) :
    ν.degreeOverStage P γ * ν.degreeOverStage P γ' ≤ ν.degreeOverStage P (γ + γ') := by
  rw [degreeOverStage, degreeOverStage, Submodule.span_mul_span]
  refine Submodule.span_le.mpr ?_
  rintro _ ⟨x, hx, y, hy, rfl⟩
  exact Submodule.subset_span ((ν.mem_filtrationLE_iff _ _).mpr
    (degree_mul_le_add ((ν.mem_filtrationLE_iff _ _).mp hx) ((ν.mem_filtrationLE_iff _ _).mp hy)))

theorem mul_mem_degreeOverStage {γ γ' : M} {x y : R} (hx : x ∈ ν.degreeOverStage P γ)
    (hy : y ∈ ν.degreeOverStage P γ') : x * y ∈ ν.degreeOverStage P (γ + γ') :=
  ν.degreeOverStage_mul_le P γ γ' (Submodule.mul_mem_mul hx hy)

omit [IsOrderedCancelAddMonoid M] in
theorem one_mem_degreeOverStage_zero : (1 : R) ∈ ν.degreeOverStage P 0 :=
  ν.mem_degreeOverStage_of_degree_le P (by simpa using ν.map_one_le_zero)

omit [IsOrderedCancelAddMonoid M] in
theorem coe_mem_degreeOverStage_zero (p : P) : (p : R) ∈ ν.degreeOverStage P 0 := by
  have := (ν.degreeOverStage P 0).smul_mem p (ν.one_mem_degreeOverStage_zero P)
  rwa [Algebra.smul_def, mul_one] at this

omit [IsOrderedCancelAddMonoid M] in
theorem exists_mem_degreeOverStage (t : R) : ∃ γ : M, t ∈ ν.degreeOverStage P γ := by
  cases h : ν t with
  | bot => exact ⟨0, ν.mem_degreeOverStage_of_degree_le P (by rw [h]; exact bot_le)⟩
  | coe m => exact ⟨m, ν.mem_degreeOverStage_of_degree_le P h.le⟩

variable [WellFoundedLT M]

omit [IsOrderedCancelAddMonoid M] in
/-- The least `γ` with `t ∈ P · R_{ν ≤ γ}`. -/
private def fibreMin (t : R) : M :=
  WellFounded.min wellFounded_lt {γ : M | t ∈ ν.degreeOverStage P γ}
    (ν.exists_mem_degreeOverStage P t)

omit [IsOrderedCancelAddMonoid M] in
private theorem mem_degreeOverStage_fibreMin (t : R) : t ∈ ν.degreeOverStage P (fibreMin ν P t) :=
  WellFounded.min_mem wellFounded_lt {γ : M | t ∈ ν.degreeOverStage P γ}
    (ν.exists_mem_degreeOverStage P t)

omit [IsOrderedCancelAddMonoid M] in
private theorem fibreMin_le {t : R} {γ : M} (h : t ∈ ν.degreeOverStage P γ) :
    fibreMin ν P t ≤ γ :=
  not_lt.mp fun hlt ↦ WellFounded.not_lt_min wellFounded_lt {γ : M | t ∈ ν.degreeOverStage P γ}
    (show γ ∈ {γ : M | t ∈ ν.degreeOverStage P γ} from h) hlt

omit [IsOrderedCancelAddMonoid M] in
private theorem fibreMin_le_iff (t : R) (γ : M) :
    fibreMin ν P t ≤ γ ↔ t ∈ ν.degreeOverStage P γ :=
  ⟨fun h ↦ ν.degreeOverStage_mono P h (mem_degreeOverStage_fibreMin ν P t), fibreMin_le ν P⟩

open Classical in
/-- The value of the degree over `P`, before bundling. -/
private def degreeOverFun (t : R) : WithBot M :=
  if t = 0 then ⊥ else ((fibreMin ν P t : M) : WithBot M)

omit [IsOrderedCancelAddMonoid M] in
private theorem degreeOverFun_le_iff (t : R) (γ : M) :
    degreeOverFun ν P t ≤ γ ↔ t ∈ ν.degreeOverStage P γ := by
  rw [degreeOverFun]
  split_ifs with ht
  · subst ht
    exact ⟨fun _ ↦ Submodule.zero_mem _, fun _ ↦ bot_le⟩
  · rw [WithBot.coe_le_coe]
    exact fibreMin_le_iff ν P t γ

omit [IsOrderedCancelAddMonoid M] in
private theorem degreeOverFun_eq_bot_iff (t : R) : degreeOverFun ν P t = ⊥ ↔ t = 0 := by
  rw [degreeOverFun]
  split_ifs with ht
  · exact ⟨fun _ ↦ ht, fun _ ↦ rfl⟩
  · exact ⟨fun h ↦ absurd h WithBot.coe_ne_bot, fun h ↦ absurd h ht⟩

omit [AddCommMonoid M] [IsOrderedCancelAddMonoid M] [WellFoundedLT M] in
private theorem withBot_eq_of_forall_le_iff {a b : WithBot M} (hbot : a = ⊥ ↔ b = ⊥)
    (h : ∀ γ : M, a ≤ γ ↔ b ≤ γ) : a = b := by
  cases a with
  | bot => exact (hbot.mp rfl).symm
  | coe m =>
    cases b with
    | bot => exact absurd (hbot.mpr rfl) WithBot.coe_ne_bot
    | coe n =>
      exact le_antisymm ((h n).mpr le_rfl) ((h m).mp le_rfl)

/-- The degree over `P`, `ν_P`: the least `γ` with `t ∈ P · R_{ν ≤ γ}`, and `-∞` at `0`. For
`ν = deg` and `P = S` this is the paper's `deg_S`. -/
def degreeOver : MaxAddDegree R M where
  toFun := degreeOverFun ν P
  map_zero' := by rw [degreeOverFun, if_pos rfl]
  map_one_le_zero' := by
    rw [WithBot.coe_zero.symm, degreeOverFun_le_iff]
    exact ν.one_mem_degreeOverStage_zero P
  map_neg' t := by
    refine withBot_eq_of_forall_le_iff ?_ fun γ ↦ ?_
    · rw [degreeOverFun_eq_bot_iff, degreeOverFun_eq_bot_iff, neg_eq_zero]
    · rw [degreeOverFun_le_iff, degreeOverFun_le_iff]
      exact ⟨fun h ↦ by simpa using Submodule.neg_mem (ν.degreeOverStage P γ) h,
        fun h ↦ Submodule.neg_mem (ν.degreeOverStage P γ) h⟩
  map_add_le_max' t t' := by
    cases hmax : max (degreeOverFun ν P t) (degreeOverFun ν P t') with
    | bot =>
      have ht : degreeOverFun ν P t = ⊥ := le_bot_iff.mp (hmax ▸ le_max_left _ _)
      have ht' : degreeOverFun ν P t' = ⊥ := le_bot_iff.mp (hmax ▸ le_max_right _ _)
      rw [(degreeOverFun_eq_bot_iff ν P t).mp ht, (degreeOverFun_eq_bot_iff ν P t').mp ht',
        add_zero, (degreeOverFun_eq_bot_iff ν P 0).mpr rfl]
    | coe γ =>
      rw [degreeOverFun_le_iff]
      have ht : degreeOverFun ν P t ≤ γ := hmax ▸ le_max_left _ _
      have ht' : degreeOverFun ν P t' ≤ γ := hmax ▸ le_max_right _ _
      exact (ν.degreeOverStage P γ).add_mem ((degreeOverFun_le_iff ν P t γ).mp ht)
        ((degreeOverFun_le_iff ν P t' γ).mp ht')
  map_mul_le_add' t t' := by
    cases ht : degreeOverFun ν P t with
    | bot =>
      rw [(degreeOverFun_eq_bot_iff ν P t).mp ht, zero_mul,
        (degreeOverFun_eq_bot_iff ν P 0).mpr rfl]
      exact bot_le
    | coe γ =>
      cases ht' : degreeOverFun ν P t' with
      | bot =>
        rw [(degreeOverFun_eq_bot_iff ν P t').mp ht', mul_zero,
          (degreeOverFun_eq_bot_iff ν P 0).mpr rfl]
        exact bot_le
      | coe γ' =>
        rw [← WithBot.coe_add, degreeOverFun_le_iff]
        exact ν.mul_mem_degreeOverStage P ((degreeOverFun_le_iff ν P t γ).mp ht.le)
          ((degreeOverFun_le_iff ν P t' γ').mp ht'.le)

theorem degreeOver_le_iff (t : R) (γ : M) :
    ν.degreeOver P t ≤ γ ↔ t ∈ ν.degreeOverStage P γ :=
  degreeOverFun_le_iff ν P t γ

theorem degreeOver_eq_bot_iff (t : R) : ν.degreeOver P t = ⊥ ↔ t = 0 :=
  degreeOverFun_eq_bot_iff ν P t

theorem degreeOver_isSeparated : (ν.degreeOver P).IsSeparated :=
  (isSeparated_iff _).mpr fun t ↦ ν.degreeOver_eq_bot_iff P t

theorem degreeOver_le_of_degree_le {t : R} {γ : M} (ht : ν t ≤ γ) :
    ν.degreeOver P t ≤ γ :=
  (ν.degreeOver_le_iff P t γ).mpr (ν.mem_degreeOverStage_of_degree_le P ht)

theorem degreeOver_le (hν : ν.IsSeparated) (t : R) : ν.degreeOver P t ≤ ν t := by
  cases h : ν t with
  | bot =>
    rw [((isSeparated_iff ν).mp hν t).mp h, (ν.degreeOver_eq_bot_iff P 0).mpr rfl]
  | coe γ => exact ν.degreeOver_le_of_degree_le P h.le

theorem degreeOver_coe_le_zero (p : P) : ν.degreeOver P (p : R) ≤ 0 := by
  rw [WithBot.coe_zero.symm, degreeOver_le_iff]
  exact ν.coe_mem_degreeOverStage_zero P p

/-- Multiplying an element of degree at most `γ` by an element of `P` keeps the degree over `P`
at most `γ`. -/
theorem degreeOver_coe_mul_le_of_degree_le (p : P) {t : R} {γ : M} (ht : ν t ≤ γ) :
    ν.degreeOver P ((p : R) * t) ≤ γ :=
  ((ν.degreeOver P).map_mul_le_add _ _).trans <| by
    calc ν.degreeOver P (p : R) + ν.degreeOver P t ≤ 0 + (γ : WithBot M) :=
          add_le_add (ν.degreeOver_coe_le_zero P p) (ν.degreeOver_le_of_degree_le P ht)
      _ = γ := zero_add _

theorem coe_mul_mem_degreeOver_filtrationLE_of_degree_le (p : P) {t : R} {γ : M} (ht : ν t ≤ γ) :
    (p : R) * t ∈ (ν.degreeOver P).filtrationLE γ :=
  ((ν.degreeOver P).mem_filtrationLE_iff _ _).mpr (ν.degreeOver_coe_mul_le_of_degree_le P p ht)

/-- When `0` is the least value, every non-zero element of `P` has degree exactly zero over `P`. -/
theorem degreeOver_coe_eq_zero (h0 : ∀ m : M, 0 ≤ m) {p : P} (hp : (p : R) ≠ 0) :
    ν.degreeOver P (p : R) = 0 := by
  refine le_antisymm (ν.degreeOver_coe_le_zero P p) ?_
  cases h : ν.degreeOver P (p : R) with
  | bot => exact absurd ((ν.degreeOver_eq_bot_iff P _).mp h) hp
  | coe m => exact WithBot.coe_le_coe.mpr (h0 m)

theorem degreeOver_algebraMap_eq_zero (h0 : ∀ m : M, 0 ≤ m) {l : L}
    (hl : algebraMap L R l ≠ 0) : ν.degreeOver P (algebraMap L R l) = 0 :=
  ν.degreeOver_coe_eq_zero P h0 (p := ⟨algebraMap L R l, P.algebraMap_mem l⟩) hl

/-- Degree over `P` below `γ` means membership in a strictly lower level, for non-zero elements. -/
theorem exists_mem_degreeOverStage_of_degreeOver_lt {t : R} {γ : M} (ht : t ≠ 0)
    (h : ν.degreeOver P t < γ) : ∃ γ' < γ, t ∈ ν.degreeOverStage P γ' := by
  cases hψ : ν.degreeOver P t with
  | bot => exact absurd ((ν.degreeOver_eq_bot_iff P t).mp hψ) ht
  | coe m =>
    rw [hψ] at h
    exact ⟨m, WithBot.coe_lt_coe.mp h, (ν.degreeOver_le_iff P t m).mp hψ.le⟩

theorem degreeOver_lt_of_mem_degreeOverStage_of_lt {t : R} {γ' γ : M}
    (h : t ∈ ν.degreeOverStage P γ') (hlt : γ' < γ) : ν.degreeOver P t < γ :=
  lt_of_le_of_lt ((ν.degreeOver_le_iff P t γ').mpr h) (WithBot.coe_lt_coe.mpr hlt)

end MaxAddDegree
