/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.Algebra.Valuation.DegreeAssociatedGraded
public import ConwayRefinement.Algebra.Valuation.QuotientDegree
public import Mathlib.RingTheory.Ideal.Maps

import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Associated graded rings of least-representative quotients

Let a separated max-additive degree on `R` be indexed by a well-ordered additive monoid. Passage
to `R ⧸ I` induces a surjective map on every homogeneous component and hence a surjective graded
ring homomorphism. Its kernel is the homogeneous initial ideal of `I`: the ideal generated by the
classes of ideal elements in every weak filtration.

Consequently, the associated graded ring of the least-representative quotient degree is canonically
isomorphic to the quotient of the source associated graded ring by the initial ideal: the
filtered-quotient isomorphism `gr_ν R ⧸ in_ν(I) ≅ gr_ν̄ (R ⧸ I)`.
-/

open scoped MaxAddDegree

universe u v

public noncomputable section

namespace MaxAddDegree

variable {R : Type u} {M : Type v} [CommRing R] [AddCommMonoid M]
  [LinearOrder M] [IsOrderedCancelAddMonoid M] [WellFoundedLT M]

/-- The quotient map restricted to the weak filtration at a fixed grade. -/
def quotientFiltrationMap (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) (m : M) :
    ν.filtrationLE m →+ (ν.quotient I hν).filtrationLE m where
  toFun x := ⟨Ideal.Quotient.mk I x, by
    rw [(ν.quotient I hν).mem_filtrationLE_iff]
    rw [ν.quotient_apply I hν]
    exact (ν.quotientValue_mk_le I hν x).trans
      ((ν.mem_filtrationLE_iff m x).mp x.2)⟩
  map_zero' := by ext; exact (Ideal.Quotient.mk I).map_zero
  map_add' x y := by ext; exact (Ideal.Quotient.mk I).map_add x y

omit [IsOrderedCancelAddMonoid M] in
@[simp]
theorem coe_quotientFiltrationMap (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) (m : M) (x : ν.filtrationLE m) :
    ((ν.quotientFiltrationMap I hν m x :
        (ν.quotient I hν).filtrationLE m) : R ⧸ I) =
      Ideal.Quotient.mk I x :=
  (rfl)

omit [IsOrderedCancelAddMonoid M] in
private theorem lowerFiltration_le_quotientComponentRepresentative_ker
    (ν : MaxAddDegree R M) (I : Ideal R) (hν : ν.IsSeparated) (m : M) :
    ν.lowerFiltration m ≤
      (((ν.quotient I hν).componentMk m).comp
        (ν.quotientFiltrationMap I hν m)).ker := by
  intro x hx
  rw [AddMonoidHom.mem_ker, AddMonoidHom.comp_apply,
    (ν.quotient I hν).componentMk_eq_zero_iff]
  rw [ν.quotient_apply I hν, coe_quotientFiltrationMap]
  exact (ν.quotientValue_mk_le I hν x).trans_lt
    ((ν.mem_lowerFiltration_iff m x).mp hx)

/-- The map on a homogeneous component induced by passage to a quotient ring. -/
def quotientComponentMap (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) (m : M) :
    ν.Component m →+ (ν.quotient I hν).Component m :=
  QuotientAddGroup.lift (ν.lowerFiltration m)
    (((ν.quotient I hν).componentMk m).comp
      (ν.quotientFiltrationMap I hν m))
    (ν.lowerFiltration_le_quotientComponentRepresentative_ker I hν m)

omit [IsOrderedCancelAddMonoid M] in
@[simp]
theorem quotientComponentMap_componentMk (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) (m : M) (x : ν.filtrationLE m) :
    ν.quotientComponentMap I hν m (ν.componentMk m x) =
      (ν.quotient I hν).componentMk m
        (ν.quotientFiltrationMap I hν m x) :=
  by
    rw [← ν.coe_component_eq_componentMk]
    rfl

omit [IsOrderedCancelAddMonoid M] in
/-- Every homogeneous class for the least-representative quotient degree lifts to the
corresponding source component. -/
theorem quotientComponentMap_surjective (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) (m : M) :
    Function.Surjective (ν.quotientComponentMap I hν m) := by
  intro z
  induction z using QuotientAddGroup.induction_on with
  | H z =>
      by_cases hz : (ν.quotient I hν).componentMk m z = 0
      · refine ⟨0, ?_⟩
        simpa using hz.symm
      · have hznotlt : ¬(ν.quotient I hν) z < m :=
          fun hlt ↦ hz (((ν.quotient I hν).componentMk_eq_zero_iff m z).mpr hlt)
        have hzdegree : (ν.quotient I hν) z = (m : WithBot M) :=
          le_antisymm
            (((ν.quotient I hν).mem_filtrationLE_iff m z).mp z.2)
            (le_of_not_gt hznotlt)
        have hznonzero : (z : R ⧸ I) ≠ 0 := by
          intro hzero
          apply hz
          apply ((ν.quotient I hν).componentMk_eq_zero_iff m z).mpr
          simp [hzero]
        obtain ⟨x, hxz, hxdegree⟩ :=
          ν.exists_representative_quotientValue_eq I hν hznonzero
        have hxle : ν x ≤ (m : WithBot M) := by
          rw [hxdegree]
          rw [← ν.quotient_apply I hν]
          rw [hzdegree]
        refine ⟨ν.componentMk m
          ⟨x, (ν.mem_filtrationLE_iff m x).mpr hxle⟩, ?_⟩
        rw [ν.quotientComponentMap_componentMk]
        rw [(ν.quotient I hν).coe_component_eq_componentMk]
        apply congrArg ((ν.quotient I hν).componentMk m)
        apply Subtype.ext
        rw [coe_quotientFiltrationMap]
        exact hxz

omit [IsOrderedCancelAddMonoid M] in
/-- A source component lies in the kernel exactly when it can be represented at that grade by
an element of the quotient ideal. -/
theorem quotientComponentMap_eq_zero_iff (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) (m : M) (x : ν.Component m) :
    ν.quotientComponentMap I hν m x = 0 ↔
      ∃ i : ν.filtrationLE m, (i : R) ∈ I ∧ ν.componentMk m i = x := by
  induction x using QuotientAddGroup.induction_on with
  | H x =>
      constructor
      · intro hx
        rw [ν.coe_component_eq_componentMk, ν.quotientComponentMap_componentMk,
          (ν.quotient I hν).componentMk_eq_zero_iff] at hx
        by_cases hqx : Ideal.Quotient.mk I (x : R) = 0
        · exact ⟨x, Ideal.Quotient.eq_zero_iff_mem.mp hqx,
            (ν.coe_component_eq_componentMk m x).symm⟩
        · obtain ⟨y, hyx, hydegree⟩ :=
            ν.exists_representative_quotientValue_eq I hν hqx
          have hylt : ν y < (m : WithBot M) := by
            rw [hydegree]
            rw [← ν.quotient_apply I hν]
            rw [coe_quotientFiltrationMap] at hx
            exact hx
          let y' : ν.filtrationLE m :=
            ⟨y, (ν.mem_filtrationLE_iff m y).mpr hylt.le⟩
          have hi : (x : R) - y ∈ I :=
            (Ideal.Quotient.mk_eq_mk_iff_sub_mem (I := I) (x : R) y).mp hyx.symm
          have hile : ν ((x : R) - y) ≤ (m : WithBot M) :=
            (ν.map_sub_le_max (x : R) y).trans
              (max_le ((ν.mem_filtrationLE_iff m x).mp x.2) hylt.le)
          let i : ν.filtrationLE m :=
            ⟨(x : R) - y, (ν.mem_filtrationLE_iff m _).mpr hile⟩
          refine ⟨i, hi, ?_⟩
          rw [ν.coe_component_eq_componentMk]
          have hiSub : i = x - y' := Subtype.ext rfl
          rw [hiSub, map_sub,
            (ν.componentMk_eq_zero_iff m y').mpr hylt, sub_zero]
      · rintro ⟨i, hi, hix⟩
        rw [← hix]
        rw [ν.quotientComponentMap_componentMk,
          (ν.quotient I hν).componentMk_eq_zero_iff]
        simp only [coe_quotientFiltrationMap]
        rw [Ideal.Quotient.eq_zero_iff_mem.mpr hi]
        simp

omit [IsOrderedCancelAddMonoid M] in
/-- The gradewise quotient map preserves the homogeneous unit. -/
theorem quotientComponentMap_componentOne (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) :
    ν.quotientComponentMap I hν 0 ν.componentOne =
      (ν.quotient I hν).componentOne := by
  rw [ν.componentOne_eq_componentMk, ν.quotientComponentMap_componentMk,
    (ν.quotient I hν).componentOne_eq_componentMk]
  apply congrArg ((ν.quotient I hν).componentMk 0)
  apply Subtype.ext
  exact map_one (Ideal.Quotient.mk I)

/-- The gradewise quotient maps preserve homogeneous multiplication. -/
theorem quotientComponentMap_componentMul (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) {m n : M} (x : ν.Component m) (y : ν.Component n) :
    ν.quotientComponentMap I hν (m + n) (ν.componentMul x y) =
      (ν.quotient I hν).componentMul
        (ν.quotientComponentMap I hν m x)
        (ν.quotientComponentMap I hν n y) := by
  induction x using QuotientAddGroup.induction_on with
  | H x =>
      induction y using QuotientAddGroup.induction_on with
      | H y =>
          rw [ν.coe_component_eq_componentMk, ν.coe_component_eq_componentMk]
          rw [ν.componentMul_componentMk, ν.quotientComponentMap_componentMk,
            ν.quotientComponentMap_componentMk, ν.quotientComponentMap_componentMk,
            (ν.quotient I hν).componentMul_componentMk]
          apply congrArg ((ν.quotient I hν).componentMk (m + n))
          apply Subtype.ext
          simp only [ν.coe_mulFiltrationLE, coe_quotientFiltrationMap,
            (ν.quotient I hν).coe_mulFiltrationLE]
          exact (Ideal.Quotient.mk I).map_mul (x : R) (y : R)

/-- The canonical graded ring map induced by passage to the quotient `R ⧸ I`. -/
def associatedGradedQuotientMap (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) :
    ν.AssociatedGraded →+* (ν.quotient I hν).AssociatedGraded :=
  DirectSum.toSemiring
    (fun m ↦ (DirectSum.of (ν.quotient I hν).Component m).comp
      (ν.quotientComponentMap I hν m))
    (by
      simp only [AddMonoidHom.comp_apply]
      rw [show GradedMonoid.GOne.one = ν.componentOne from rfl,
        ν.quotientComponentMap_componentOne]
      exact DirectSum.of_zero_one (ν.quotient I hν).Component)
    (by
      intro m n x y
      simp only [AddMonoidHom.comp_apply]
      rw [show GradedMonoid.GMul.mul x y = ν.componentMul x y from rfl,
        ν.quotientComponentMap_componentMul, DirectSum.of_mul_of]
      rfl)

@[simp]
theorem associatedGradedQuotientMap_of (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) (m : M) (x : ν.Component m) :
    ν.associatedGradedQuotientMap I hν (DirectSum.of ν.Component m x) =
      DirectSum.of (ν.quotient I hν).Component m
        (ν.quotientComponentMap I hν m x) :=
  DirectSum.toSemiring_of _ _ _ m x

/-- The canonical graded quotient map is computed componentwise. -/
theorem associatedGradedQuotientMap_apply (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) (z : ν.AssociatedGraded) (m : M) :
    ν.associatedGradedQuotientMap I hν z m =
      ν.quotientComponentMap I hν m (z m) := by
  induction z using DirectSum.induction_on with
  | zero => simp
  | of n z =>
      by_cases hnm : n = m
      · subst m
        simp [ν.associatedGradedQuotientMap_of]
      · simp [ν.associatedGradedQuotientMap_of, DirectSum.of_apply, hnm]
  | add x y hx hy => simp [map_add, hx, hy]

/-- The canonical map onto the associated graded ring of the quotient is surjective. -/
theorem associatedGradedQuotientMap_surjective (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) :
    Function.Surjective (ν.associatedGradedQuotientMap I hν) := by
  intro z
  induction z using DirectSum.induction_on with
  | zero => exact ⟨0, (ν.associatedGradedQuotientMap I hν).map_zero⟩
  | of m z =>
      obtain ⟨x, hx⟩ := ν.quotientComponentMap_surjective I hν m z
      refine ⟨DirectSum.of ν.Component m x, ?_⟩
      rw [ν.associatedGradedQuotientMap_of, hx]
  | add x y hx hy =>
      obtain ⟨a, ha⟩ := hx
      obtain ⟨b, hb⟩ := hy
      refine ⟨a + b, ?_⟩
      rw [map_add, ha, hb]

/-- The homogeneous initial ideal generated by the classes of ideal elements in every weak
filtration. Classes placed strictly above their degree are zero, so this is the usual ideal
generated by nonzero initial forms. -/
def initialIdeal (ν : MaxAddDegree R M) (I : Ideal R) : Ideal ν.AssociatedGraded :=
  Ideal.span {z | ∃ (m : M) (i : ν.filtrationLE m),
    (i : R) ∈ I ∧ z = ν.homogeneousMk m i}

omit [WellFoundedLT M] in
/-- Every homogeneous class of an ideal element belongs to the initial ideal. -/
theorem homogeneousMk_mem_initialIdeal (ν : MaxAddDegree R M) (I : Ideal R)
    (m : M) (i : ν.filtrationLE m) (hi : (i : R) ∈ I) :
    ν.homogeneousMk m i ∈ ν.initialIdeal I :=
  Ideal.subset_span ⟨m, i, hi, rfl⟩

omit [WellFoundedLT M] in
/-- To contain the initial ideal, it suffices and is necessary to contain every homogeneous class
of an element of the original ideal. -/
theorem initialIdeal_le_iff (ν : MaxAddDegree R M) (I : Ideal R)
    (J : Ideal ν.AssociatedGraded) :
    ν.initialIdeal I ≤ J ↔
      ∀ (m : M) (i : ν.filtrationLE m),
        (i : R) ∈ I → ν.homogeneousMk m i ∈ J := by
  rw [initialIdeal, Ideal.span_le]
  constructor
  · intro h m i hi
    exact h ⟨m, i, hi, rfl⟩
  · rintro h z ⟨m, i, hi, rfl⟩
    exact h m i hi

/-- The initial ideal is exactly the kernel of the canonical graded quotient map. -/
theorem initialIdeal_eq_ker_associatedGradedQuotientMap
    (ν : MaxAddDegree R M) (I : Ideal R) (hν : ν.IsSeparated) :
    ν.initialIdeal I = RingHom.ker (ν.associatedGradedQuotientMap I hν) := by
  apply le_antisymm
  · rw [initialIdeal, Ideal.span_le]
    rintro z ⟨m, i, hi, rfl⟩
    change ν.associatedGradedQuotientMap I hν (ν.homogeneousMk m i) = 0
    rw [ν.homogeneousMk_apply,
      ν.associatedGradedQuotientMap_of, ν.quotientComponentMap_componentMk]
    have hcomponent :
        (ν.quotient I hν).componentMk m
          (ν.quotientFiltrationMap I hν m i) = 0 := by
      rw [(ν.quotient I hν).componentMk_eq_zero_iff]
      simp only [coe_quotientFiltrationMap]
      rw [Ideal.Quotient.eq_zero_iff_mem.mpr hi]
      simp
    rw [hcomponent, (DirectSum.of (ν.quotient I hν).Component m).map_zero]
  · intro z hz
    rw [RingHom.mem_ker] at hz
    classical
    rw [← DirectSum.sum_support_of z]
    apply Submodule.sum_mem
    intro m hm
    have hmzero : ν.quotientComponentMap I hν m (z m) = 0 := by
      rw [← ν.associatedGradedQuotientMap_apply I hν z m, hz]
      rfl
    obtain ⟨i, hi, hix⟩ :=
      (ν.quotientComponentMap_eq_zero_iff I hν m (z m)).mp hmzero
    rw [← hix]
    rw [← ν.homogeneousMk_apply]
    exact ν.homogeneousMk_mem_initialIdeal I m i hi

/-- The associated graded ring of the least-representative quotient is the quotient by the
initial ideal. -/
def associatedGradedQuotientEquiv (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) :
    ν.AssociatedGraded ⧸ ν.initialIdeal I ≃+*
      (ν.quotient I hν).AssociatedGraded :=
  (Ideal.quotEquivOfEq
    (ν.initialIdeal_eq_ker_associatedGradedQuotientMap I hν)).trans
    (RingHom.quotientKerEquivOfSurjective
      (ν.associatedGradedQuotientMap_surjective I hν))

@[simp]
theorem associatedGradedQuotientEquiv_mk (ν : MaxAddDegree R M) (I : Ideal R)
    (hν : ν.IsSeparated) (z : ν.AssociatedGraded) :
    ν.associatedGradedQuotientEquiv I hν
        (Ideal.Quotient.mk (ν.initialIdeal I) z) =
      ν.associatedGradedQuotientMap I hν z := by
  rw [associatedGradedQuotientEquiv, RingEquiv.trans_apply,
    Ideal.quotEquivOfEq_mk, RingHom.quotientKerEquivOfSurjective_apply_mk]

end MaxAddDegree
