/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.Algebra.Valuation.DegreeAssociatedGradedQuotient
public import ConwayRefinement.Algebra.Valuation.DegreeInitialForm
import ConwayRefinement.Algebra.Valuation.DegreeAssociatedGradedDomain
import ConwayRefinement.Algebra.DirectSum.HomogeneousDivisibility
import Mathlib.RingTheory.Ideal.Quotient.Basic

/-!
# Initial ideals of principal ideals

For a multiplicative max-additive degree, the initial ideal of `(q)` is generated by the initial
form of `q`. For a separated degree, a domain associated graded ring supplies multiplicativity, so
the associated graded ring of `R / (q)` is the quotient by that single initial form.

If this graded quotient is a domain, then `R / (q)` is a domain. The same conclusion, that a
nonzero `a` whose initial form generates a prime ideal of the associated graded ring is prime, has
a direct proof for a separated multiplicative degree over a well-ordered value monoid: for
`b ∉ (a)` of least degree in its coset, `in(b) ∈ (in a)` would give `in(b) = in(a) g` with `g`
homogeneous, and a lift `g̃` of `g` would produce `b - a g̃` of smaller degree in the same coset.
-/

open scoped MaxAddDegree

universe u v

public noncomputable section

namespace MaxAddDegree

variable {R : Type u} {M : Type v} [CommRing R] [AddCommMonoid M]
  [LinearOrder M] [IsOrderedCancelAddMonoid M]

/-- The initial ideal of a principal ideal is generated by the initial form of its generator when
the degree is multiplicative. -/
theorem initialIdeal_span_singleton_eq_span_initialForm
    (ν : MaxAddDegree R M) [ν.IsMultiplicative] (q : R) :
    ν.initialIdeal (Ideal.span {q}) = Ideal.span {ν.initialForm q} := by
  apply le_antisymm
  · rw [ν.initialIdeal_le_iff]
    intro m i hi
    by_cases hic : ν.componentMk m i = 0
    · rw [ν.homogeneousMk_apply, hic,
        (DirectSum.of ν.Component m).map_zero]
      exact (Ideal.span {ν.initialForm q}).zero_mem
    · obtain ⟨b, hb⟩ := Ideal.mem_span_singleton.mp hi
      rw [← ν.initialForm_eq_homogeneousMk_of_componentMk_ne_zero m i hic,
        hb, ν.initialForm_mul]
      exact Ideal.mem_span_singleton.mpr ⟨ν.initialForm b, rfl⟩
  · rw [Ideal.span_le]
    intro z hz
    rw [Set.mem_singleton_iff.mp hz]
    by_cases hq : ν q = ⊥
    · rw [ν.initialForm_eq_zero_of_eq_bot hq]
      exact (ν.initialIdeal (Ideal.span {q})).zero_mem
    · rw [ν.initialForm_eq_homogeneousMk_of_ne_bot hq]
      apply ν.homogeneousMk_mem_initialIdeal
      simpa only [ν.coe_initialRepresentative] using
        Ideal.mem_span_singleton_self q

/-- A domain source associated graded ring gives the principal-initial-ideal equality. -/
theorem initialIdeal_span_singleton_eq_span_initialForm_of_isDomain
    (ν : MaxAddDegree R M) (hν : ν.IsSeparated) [IsDomain ν.AssociatedGraded]
    (q : R) :
    ν.initialIdeal (Ideal.span {q}) = Ideal.span {ν.initialForm q} :=
  haveI := ν.isMultiplicative_of_associatedGraded_isDomain hν
  ν.initialIdeal_span_singleton_eq_span_initialForm q

variable [WellFoundedLT M]

/-- The associated graded ring of a principal quotient is the quotient by the generator's initial
form when the source associated graded ring is a domain. -/
def associatedGradedPrincipalQuotientEquiv
    (ν : MaxAddDegree R M) (hν : ν.IsSeparated) [IsDomain ν.AssociatedGraded]
    (q : R) :
    ν.AssociatedGraded ⧸ Ideal.span {ν.initialForm q} ≃+*
      (ν.quotient (Ideal.span {q}) hν).AssociatedGraded :=
  (Ideal.quotEquivOfEq
    (ν.initialIdeal_span_singleton_eq_span_initialForm_of_isDomain hν q).symm).trans
    (ν.associatedGradedQuotientEquiv (Ideal.span {q}) hν)

@[simp]
theorem associatedGradedPrincipalQuotientEquiv_mk
    (ν : MaxAddDegree R M) (hν : ν.IsSeparated) [IsDomain ν.AssociatedGraded]
    (q : R) (z : ν.AssociatedGraded) :
    ν.associatedGradedPrincipalQuotientEquiv hν q
        (Ideal.Quotient.mk (Ideal.span {ν.initialForm q}) z) =
      ν.associatedGradedQuotientMap (Ideal.span {q}) hν z := by
  rw [associatedGradedPrincipalQuotientEquiv, RingEquiv.trans_apply,
    Ideal.quotEquivOfEq_mk, ν.associatedGradedQuotientEquiv_mk]

/-! ### The direct prime criterion -/

omit [IsOrderedCancelAddMonoid M] in
/-- A coset of an ideal not containing zero has a representative of least degree. -/
theorem exists_sub_mem_and_forall_le (ν : MaxAddDegree R M) (hν : ν.IsSeparated) (I : Ideal R)
    {b : R} (hb : b ∉ I) :
    ∃ b₀, b₀ - b ∈ I ∧ ∀ b', b' - b ∈ I → ν b₀ ≤ ν b' := by
  have hq : Ideal.Quotient.mk I b ≠ 0 := fun h ↦ hb (Ideal.Quotient.eq_zero_iff_mem.mp h)
  obtain ⟨b₀, hb₀, hνb₀⟩ := ν.exists_representative_quotientValue_eq I hν hq
  refine ⟨b₀, Ideal.Quotient.eq.mp hb₀, fun b' hb' ↦ ?_⟩
  rw [hνb₀, ← Ideal.Quotient.eq.mpr hb']
  exact ν.quotientValue_mk_le I hν b'

omit [WellFoundedLT M] in
/-- For a separated multiplicative degree, an element `b ∉ (a)` of least degree in its coset
modulo `(a)` has initial form outside `(in_ν a)`: otherwise `in_ν b = in_ν a · g` with `g`
homogeneous, and a lift `g̃` of `g` gives `ν (b - a g̃) < ν b` in the same coset. -/
theorem initialForm_notMem_span_initialForm (ν : MaxAddDegree R M) [ν.IsMultiplicative]
    (hν : ν.IsSeparated) {a b : R} (ha : a ≠ 0) (hb : b ∉ Ideal.span {a})
    (hmin : ∀ b', b' - b ∈ Ideal.span {a} → ν b ≤ ν b') :
    ν.initialForm b ∉ Ideal.span {ν.initialForm a} := by
  classical
  intro hmem
  obtain ⟨g, hg⟩ := Ideal.mem_span_singleton'.mp hmem
  have hb0 : b ≠ 0 := fun h ↦ hb (h ▸ (Ideal.span {a}).zero_mem)
  obtain ⟨e, he⟩ := WithBot.ne_bot_iff_exists.mp (ν.map_ne_bot_of_ne_zero hν ha)
  obtain ⟨d, hd⟩ := WithBot.ne_bot_iff_exists.mp (ν.map_ne_bot_of_ne_zero hν hb0)
  have hale : a ∈ ν.filtrationLE e := (ν.mem_filtrationLE_iff e a).mpr he.ge
  have hble : b ∈ ν.filtrationLE d := (ν.mem_filtrationLE_iff d b).mpr hd.ge
  rw [← ν.homogeneousMk_eq_initialForm_of_degree_eq hale he.symm,
    ← ν.homogeneousMk_eq_initialForm_of_degree_eq hble hd.symm, mul_comm,
    ν.homogeneousMk_apply, ν.homogeneousMk_apply] at hg
  -- compare the components in grade `d = ν b`
  have hd' := congrArg (fun z : ν.AssociatedGraded ↦ z d) hg
  simp only [DirectSum.of_eq_same] at hd'
  by_cases hj : ∃ j, e + j = d
  · obtain ⟨j, rfl⟩ := hj
    rw [DirectSum.of_mul_apply_add] at hd'
    obtain ⟨gt, hgt⟩ : ∃ gt, ν.componentMk j gt = g j :=
      componentInductionOn (g j) fun gt ↦ ⟨gt, rfl⟩
    rw [← hgt, show GradedMonoid.GMul.mul _ _ = ν.componentMul _ _ from rfl,
      ν.componentMul_componentMk, ν.componentMk_eq_componentMk_iff] at hd'
    simp only [ν.coe_mulFiltrationLE] at hd'
    have hlt : ν (b - a * gt) < (e + j : WithBot M) := by
      rw [← ν.map_neg, neg_sub]
      exact hd'
    have hcoset : b - a * gt - b ∈ Ideal.span {a} := by
      rw [sub_sub_cancel_left, neg_mem_iff]
      exact Ideal.mem_span_singleton'.mpr ⟨gt, mul_comm _ _⟩
    exact absurd (hmin _ hcoset) (not_le.mpr (hd ▸ hlt))
  · rw [DirectSum.of_mul_apply_eq_zero_of_not_exists _ _ _ hj, eq_comm,
      ν.componentMk_eq_zero_iff] at hd'
    exact absurd hd' (not_lt.mpr hd.le)

/-- For a separated multiplicative degree over a well-ordered value monoid, a nonzero `a` whose
initial form generates a prime ideal of the associated graded ring generates a prime ideal. -/
theorem span_singleton_isPrime_of_span_initialForm_isPrime (ν : MaxAddDegree R M)
    [ν.IsMultiplicative] (hν : ν.IsSeparated) {a : R} (ha : a ≠ 0)
    (hprime : (Ideal.span {ν.initialForm a}).IsPrime) : (Ideal.span {a}).IsPrime := by
  refine ⟨fun htop ↦ ?_, fun {b c} hbc ↦ ?_⟩
  · -- `in_ν a` is not a unit, so `a` is not a unit
    obtain ⟨a', ha'⟩ := (Ideal.span_singleton_eq_top.mp htop).exists_right_inv
    apply hprime.ne_top
    rw [Ideal.span_singleton_eq_top]
    exact IsUnit.of_mul_eq_one (ν.initialForm a')
      (by rw [← ν.initialForm_mul, ha', ν.initialForm_one])
  · by_contra hnot
    rw [not_or] at hnot
    -- replace `b` and `c` by representatives of least degree in their cosets
    obtain ⟨b₀, hb₀, hbmin⟩ := ν.exists_sub_mem_and_forall_le hν _ hnot.1
    obtain ⟨c₀, hc₀, hcmin⟩ := ν.exists_sub_mem_and_forall_le hν _ hnot.2
    have hb₀' : b₀ ∉ Ideal.span {a} := fun h ↦
      hnot.1 (by simpa using (Ideal.span {a}).sub_mem h hb₀)
    have hc₀' : c₀ ∉ Ideal.span {a} := fun h ↦
      hnot.2 (by simpa using (Ideal.span {a}).sub_mem h hc₀)
    have hmin_b : ∀ b', b' - b₀ ∈ Ideal.span {a} → ν b₀ ≤ ν b' := fun b' h ↦
      hbmin b' (by simpa using (Ideal.span {a}).add_mem h hb₀)
    have hmin_c : ∀ c', c' - c₀ ∈ Ideal.span {a} → ν c₀ ≤ ν c' := fun c' h ↦
      hcmin c' (by simpa using (Ideal.span {a}).add_mem h hc₀)
    have hbc₀ : b₀ * c₀ ∈ Ideal.span {a} := by
      have hmem : b₀ * c₀ - b * c ∈ Ideal.span {a} := by
        rw [show b₀ * c₀ - b * c = (b₀ - b) * c₀ + b * (c₀ - c) by ring]
        exact (Ideal.span {a}).add_mem ((Ideal.span {a}).mul_mem_right _ hb₀)
          ((Ideal.span {a}).mul_mem_left _ hc₀)
      simpa using (Ideal.span {a}).add_mem hmem hbc
    obtain ⟨q, hq⟩ := Ideal.mem_span_singleton'.mp hbc₀
    have hin : ν.initialForm b₀ * ν.initialForm c₀ ∈ Ideal.span {ν.initialForm a} := by
      rw [← ν.initialForm_mul, ← hq, ν.initialForm_mul]
      exact Ideal.mem_span_singleton'.mpr ⟨_, rfl⟩
    rcases hprime.mem_or_mem hin with h | h
    · exact ν.initialForm_notMem_span_initialForm hν ha hb₀' hmin_b h
    · exact ν.initialForm_notMem_span_initialForm hν ha hc₀' hmin_c h

/-- For a separated degree with a domain associated graded ring, a nonzero `a` with
`gr_ν R / (in_ν a)` a domain is prime. -/
theorem prime_of_quotient_span_initialForm_isDomain (ν : MaxAddDegree R M) (hν : ν.IsSeparated)
    [IsDomain ν.AssociatedGraded] {a : R} (ha : a ≠ 0)
    [IsDomain (ν.AssociatedGraded ⧸ Ideal.span {ν.initialForm a})] : Prime a :=
  haveI := ν.isMultiplicative_of_associatedGraded_isDomain hν
  (Ideal.span_singleton_prime ha).mp
    (ν.span_singleton_isPrime_of_span_initialForm_isPrime hν ha
      ((Ideal.Quotient.isDomain_iff_prime _).mp inferInstance))

end MaxAddDegree
