/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.Standalone.Mathlib.Support.HahnLimitTailQuotient
public import Mathlib.Algebra.Divisibility.Basic
public import Mathlib.Algebra.Order.Module.HahnEmbedding
public import Mathlib.Data.Real.Basic
public import Mathlib.RingTheory.HahnSeries.Cardinal
public import Mathlib.SetTheory.Cardinal.Cofinality.Basic
public import Mathlib.SetTheory.Cardinal.Regular

/-!
# A criterion for refinement in bounded Hahn integer parts

Conditions `(A1)`--`(A3)` of LM24, together with two conditions on every common tail at a limit of
Archimedean classes, imply four-factor refinement in a cardinal-bounded Hahn integer part.
-/

public noncomputable section

open Cardinal

namespace ConwayRefinement.Standalone.Hahn

universe u v

variable {G : Type u} {R : Type v}
variable [AddCommGroup G] [LinearOrder G] [IsOrderedAddMonoid G]
variable [Module ℚ G] [IsOrderedModule ℚ G]
variable [Field R]

/-- The cardinal-bounded Hahn integer part
`Z + {x : R((G)) | supp(x) ⊆ G^{<0} and #supp(x) < κ}`. -/
abbrev hahnIntegerPart (Z : Subring R) (κ : Cardinal.{u}) : Set (HahnSeries G R) :=
  {x | x.cardSupp < κ ∧ x.support ⊆ Set.Iic 0 ∧ x.coeff 0 ∈ Z}

/-- The bounded Hahn field is the fraction field of its bounded Hahn integer part. -/
abbrev IsFractionFieldOfHahnIntegerPart (Z : Subring R) (κ : Cardinal.{u}) : Prop :=
  ∀ x : HahnSeries G R, x.cardSupp < κ →
    ∃ a b : HahnSeries G R,
      a ∈ hahnIntegerPart Z κ ∧ b ∈ hahnIntegerPart Z κ ∧ b ≠ 0 ∧ x = a / b

/-- Condition `(A1)`: every nonzero Archimedean stratum is order additively isomorphic to
`ℝ`. -/
abbrev AssumptionA1 (s : HahnEmbedding.ArchimedeanStrata ℚ G) : Prop :=
  ∀ c : FiniteArchimedeanClass G, Nonempty (s.stratum c ≃+o ℝ)

/-- The coefficient field is generated by fractions of elements of `Z`. -/
abbrev GeneratesFractionField (Z : Subring R) : Prop :=
  ∀ x : R, ∃ a b : Z, b ≠ 0 ∧ x = (a : R) / (b : R)

/-- Condition `(A2)` at every nonzero Archimedean class. The second alternative is the
degenerate case in which the strict inner ball is zero. -/
abbrev AssumptionA2 (Z : Subring R) (κ : Cardinal.{u}) : Prop :=
  ∀ c : FiniteArchimedeanClass G,
    κ ≤ Order.cof ↑(FiniteArchimedeanClass.ball ℚ c) ∨
      (Subsingleton ↑(FiniteArchimedeanClass.ball ℚ c) ∧ GeneratesFractionField Z)

/-- Condition `(A3)`: every element of the coefficient ring is primal. -/
abbrev AssumptionA3 (Z : Subring R) : Prop :=
  ∀ z a b : Z, z ∣ a * b →
    ∃ z₁ z₂ : Z, z₁ ∣ a ∧ z₂ ∣ b ∧ z = z₁ * z₂

/-- A nonempty family of nonzero Archimedean classes with no least member in the magnitude
order. -/
abbrev IsLimitFamily (T : Set (FiniteArchimedeanClass G)) : Prop :=
  T.Nonempty ∧ ∀ c ∈ T, ∃ d ∈ T, c < d

/-- The exponents lying beyond every Archimedean class in `T`. -/
abbrev commonTail (T : Set (FiniteArchimedeanClass G)) : Submodule ℚ G :=
  FiniteArchimedeanClass.tailSubmodule ℚ T

/-- An exponent belongs to the common tail exactly when its Archimedean magnitude lies beyond
every class in `T`. -/
theorem mem_commonTail_iff {T : Set (FiniteArchimedeanClass G)} {x : G} :
    x ∈ commonTail T ↔ ∀ c : T, c.1.1 ≤ ArchimedeanClass.mk x := by
  rw [FiniteArchimedeanClass.mem_tailSubmodule_iff,
    FiniteArchimedeanClass.mem_tailKernel_iff]

/-- Cauchy completeness and fraction-field equality for common tails of limit families. -/
structure LimitTailConditions (Z : Subring R) (κ : Cardinal.{u}) : Prop where
  cauchy_complete_quotient (T : Set (FiniteArchimedeanClass G)) (hT : IsLimitFamily T)
      (hTcard : #T < κ) :
    Nonempty (CompleteSpace (G ⧸ commonTail T))
  fraction_field_commonTail (T : Set (FiniteArchimedeanClass G))
      (hT : IsLimitFamily T) (hTcard : #T < κ) :
    IsFractionFieldOfHahnIntegerPart (G := commonTail T) Z κ

/-- **Four-factor refinement from `(A1)`--`(A3)` and the common-tail conditions.** Every equality
`a * b = c * d` in `Z + R((G^{<0}))_κ` has a four-factor refinement. -/
abbrev HahnIntegerPartRefinementCriterion : Prop :=
  CharZero R → ∀ (κ : Cardinal.{u}), ℵ₀ < κ → κ.IsRegular →
    ∀ (Z : Subring R) (s : HahnEmbedding.ArchimedeanStrata ℚ G),
    AssumptionA1 s → AssumptionA2 (G := G) Z κ → AssumptionA3 Z →
    LimitTailConditions (G := G) Z κ →
    ∀ a b c d : HahnSeries G R,
      a ∈ hahnIntegerPart Z κ → b ∈ hahnIntegerPart Z κ →
      c ∈ hahnIntegerPart Z κ → d ∈ hahnIntegerPart Z κ → a * b = c * d →
        ∃ e f g h : HahnSeries G R,
          e ∈ hahnIntegerPart Z κ ∧ f ∈ hahnIntegerPart Z κ ∧
          g ∈ hahnIntegerPart Z κ ∧ h ∈ hahnIntegerPart Z κ ∧
            a = e * f ∧ b = g * h ∧ c = e * g ∧ d = f * h

end ConwayRefinement.Standalone.Hahn

/-!
## Formal proof

Proof module: `HahnIntegerPartRefinementCriterionProof`.

* `HahnIntegerPartRefinementCriterion` → `HahnIntegerPartRefinementCriterion.proof`
-/
