/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.Topology.Order.PWOAddition
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Additive
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Truncation
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Convolution
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Multiplication
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Leibniz
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Power
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Cancellation
public import
  ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.CantorBendixsonValueMultiplicativity
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Germ
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Graded
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Scalar
import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.GlobalCofactors
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.Lifts
import Mathlib.Algebra.MvPolynomial.CommRing
import ConwayRefinement.HahnSeries.Nonpositive
public import Mathlib.Topology.DerivedSet
public import Mathlib.Topology.Instances.Real.Lemmas
import Mathlib.Analysis.SpecificLimits.Basic

/-!
# Addition on a support with an accumulation point

The closed support generated by the negative reciprocal sequence has an accumulation point at
zero. Addition on its square is proper and has a finite noninjective fiber. This excludes both
a finite-support substitute for well-ordering and an injectivity substitute for finite fibers.
The empty-support case separately exercises the degenerate domain.
-/

public noncomputable section

open Set Filter Topology HahnSeries

namespace Tests.PWOAddition

/-- The increasing negative reciprocal sequence converging to zero. -/
def negRecip (n : ℕ) : ℝ := -(1 / ((n : ℝ) + 1))

@[simp]
theorem negRecip_apply (n : ℕ) :
    negRecip n = -(1 / ((n : ℝ) + 1)) := (rfl)

private theorem negRecip_strictMono : StrictMono negRecip := by
  intro m n hmn
  simp only [negRecip_apply]
  apply neg_lt_neg
  exact one_div_lt_one_div_of_lt (by positivity) (by exact_mod_cast Nat.add_lt_add_right hmn 1)

private theorem negRecip_pwo : (range negRecip).IsPWO := by
  simpa only [image_univ] using
    (Set.isPWO_of_wellQuasiOrderedLE (univ : Set ℕ)).image_of_monotoneOn
      (negRecip_strictMono.monotone.monotoneOn _)

private theorem negRecip_tendsto : Tendsto negRecip atTop (𝓝 (0 : ℝ)) := by
  simpa only [← funext negRecip_apply, neg_zero] using
    (tendsto_one_div_add_atTop_nhds_zero_nat (𝕜 := ℝ)).neg

/-- The test support is not discrete: zero is an accumulation point. -/
theorem accumulation : (0 : ℝ) ∈ derivedSet (closure (range negRecip)) := by
  apply mem_derivedSet.mpr
  apply accPt_iff_nhds.mpr
  intro U hU
  have he : ∀ᶠ n in atTop, negRecip n ∈ U := negRecip_tendsto hU
  obtain ⟨n, hn⟩ := he.exists
  refine ⟨negRecip n, ⟨hn, subset_closure (mem_range_self n)⟩, ?_⟩
  simp only [negRecip_apply]
  exact neg_ne_zero.mpr (one_div_ne_zero (by positivity))

/-- The proper-map theorem applies to a support with a genuine accumulation point. -/
theorem proper_add :
    IsProperMap (fun p : closure (range negRecip) ×ˢ closure (range negRecip) ↦ p.1.1 + p.1.2) :=
  negRecip_pwo.closure.isProperMap_add negRecip_pwo.closure isClosed_closure isClosed_closure

/-- The addition fiber is finite although addition is not injective on the support square. -/
theorem finite_noninjective_fiber :
    let s := closure (range negRecip)
    let f := fun p : s ×ˢ s ↦ p.1.1 + p.1.2
    (f ⁻¹' {negRecip 0 + negRecip 1}).Finite ∧ ¬Function.Injective f := by
  dsimp only
  refine ⟨negRecip_pwo.closure.finite_subtype_add_fiber negRecip_pwo.closure _, ?_⟩
  intro hinj
  let p : closure (range negRecip) ×ˢ closure (range negRecip) :=
    ⟨(negRecip 0, negRecip 1), subset_closure (mem_range_self 0), subset_closure (mem_range_self 1)⟩
  let q : closure (range negRecip) ×ˢ closure (range negRecip) :=
    ⟨(negRecip 1, negRecip 0), subset_closure (mem_range_self 1), subset_closure (mem_range_self 0)⟩
  have he : p = q := hinj (by exact add_comm _ _)
  have hfst : negRecip 0 = negRecip 1 := congrArg (fun p ↦ p.1.1) he
  exact (negRecip_strictMono (by decide : 0 < 1)).ne hfst

/-- Empty supports are permitted by the proper-map statement. -/
theorem empty_left : IsProperMap (fun p : (∅ : Set ℝ) ×ˢ closure (range negRecip) ↦
    p.1.1 + p.1.2) :=
  Set.isPWO_empty.isProperMap_add negRecip_pwo.closure isClosed_empty isClosed_closure

/-- A Hahn series with coefficient one on the negative reciprocal sequence and zero elsewhere. -/
def accumulatingSeries : HahnSeries ℝ ℚ := by
  classical
  exact ⟨fun x ↦ if x ∈ range negRecip then 1 else 0, by
    simpa only [Function.support, ne_eq, ite_eq_right_iff, one_ne_zero, imp_false, not_not,
      Set.setOf_mem_eq]
      using negRecip_pwo⟩

open Classical in
@[simp]
theorem accumulatingSeries_coeff (x : ℝ) :
    accumulatingSeries.coeff x = if x ∈ range negRecip then 1 else 0 := by
  classical
  rfl

@[simp]
theorem accumulatingSeries_support : accumulatingSeries.support = range negRecip := by
  classical
  ext x
  simp only [HahnSeries.mem_support, accumulatingSeries_coeff, ne_eq, ite_eq_right_iff,
    one_ne_zero, imp_false, not_not]

/-- A genuine infinite Hahn support has positive rank at zero and value at least `omega`. -/
theorem accumulatingSeries_positive_rank :
    1 ≤ accumulatingSeries.cantorBendixsonRank 0 ∧
      Ordinal.omega0 ≤ accumulatingSeries.cantorBendixsonValue := by
  have hm : (0 : ℝ) ∈
      (accumulatingSeries.closedSupport.cantorBendixson (1 : Ordinal) : Set ℝ) := by
    rw [show (1 : Ordinal) = 0 + 1 by simp, TopologicalSpace.Closeds.cantorBendixson_add_one,
      TopologicalSpace.Closeds.cantorBendixson_zero, TopologicalSpace.Closeds.coe_derived,
      HahnSeries.coe_closedSupport, accumulatingSeries_support]
    exact accumulation
  obtain ⟨hmem, hr⟩ := (accumulatingSeries.mem_support_derivative_iff 0 1).mp hm
  refine ⟨hr, ?_⟩
  rw [accumulatingSeries.cantorBendixsonValue_of_mem hmem]
  simpa only [Ordinal.opow_one] using
    Ordinal.opow_le_opow_right Ordinal.omega0_pos hr

/-- Zero and strictly negative monomials vanish, but a nonzero constant has value one. -/
theorem value_boundary_cases :
    (0 : HahnSeries ℝ ℚ).cantorBendixsonValue = 0 ∧
      (HahnSeries.single (-1 : ℝ) (1 : ℚ)).cantorBendixsonValue = 0 ∧
      (HahnSeries.single (0 : ℝ) (1 : ℚ)).cantorBendixsonValue = 1 := by
  refine ⟨HahnSeries.cantorBendixsonValue_zero, ?_, ?_⟩
  · apply HahnSeries.cantorBendixsonValue_of_finite_of_coeff_eq_zero
    · exact (Set.finite_singleton _).subset HahnSeries.support_single_subset
    · simp
  · apply HahnSeries.cantorBendixsonValue_of_finite_of_coeff_ne_zero
    · exact (Set.finite_singleton _).subset HahnSeries.support_single_subset
    · simp

/-- Weak truncation retains the cutoff monomial; strict truncation deletes it. -/
theorem cutoff_endpoint :
    (HahnSeries.translate (1 : ℝ)
      (HahnSeries.truncLE (-1) (HahnSeries.single (-1) (1 : ℚ)))).cantorBendixsonValue = 1 ∧
    (HahnSeries.translate (1 : ℝ)
      (HahnSeries.truncLT (-1) (HahnSeries.single (-1) (1 : ℚ)))).cantorBendixsonValue = 0 := by
  have hle : HahnSeries.translate (1 : ℝ)
      (HahnSeries.truncLE (-1) (HahnSeries.single (-1) (1 : ℚ))) =
      HahnSeries.single 0 1 := by
    ext x
    by_cases hx : x = 0
    · subst x
      simp [HahnSeries.coeff_truncLE]
    · have hn : x - 1 ≠ -1 := by simpa using hx
      simp [HahnSeries.coeff_truncLE, hx, hn]
  have hlt : HahnSeries.truncLT (-1 : ℝ) (HahnSeries.single (-1) (1 : ℚ)) = 0 := by
    ext x
    by_cases hx : x = -1
    · subst x
      simp [HahnSeries.coeff_truncLT]
    · simp [HahnSeries.coeff_truncLT, hx]
  rw [hle, hlt, map_zero]
  exact ⟨value_boundary_cases.2.2, HahnSeries.cantorBendixsonValue_zero⟩

/-- A cutoff at an actual accumulation point preserves its positive rank. -/
theorem accumulated_cutoff_rank :
    (HahnSeries.translate (0 : ℝ)
      (HahnSeries.truncLE 0 accumulatingSeries)).cantorBendixsonRank 0 ≥ 1 := by
  rw [HahnSeries.translate_zero_apply, HahnSeries.cantorBendixsonRank_truncLE]
  exact accumulatingSeries_positive_rank.1

/-- The finite convolution fiber contains a limit pair absent from both raw supports. -/
theorem convolution_limit_index :
    ((0, 0) : ℝ × ℝ) ∈ accumulatingSeries.closedSupportAddFiber accumulatingSeries 0 ∧
      (0 : ℝ) ∉ accumulatingSeries.support := by
  have hc : (0 : ℝ) ∈ accumulatingSeries.closedSupport := by
    rw [mem_closedSupport, accumulatingSeries_support]
    exact isClosed_closure.closure_subset (derivedSet_subset_closure _ accumulation)
  refine ⟨(mem_closedSupportAddFiber _ _ _ _).mpr ⟨hc, hc, add_zero _⟩, ?_⟩
  rw [accumulatingSeries_support]
  rintro ⟨n, hn⟩
  have hne : negRecip n ≠ 0 := by
    simp only [negRecip_apply, ne_eq, neg_eq_zero, one_div, inv_eq_zero]
    positivity
  exact hne hn

/-- Omitting that limit pair would falsely give value zero for this actual square. -/
theorem convolution_square_nonzero_value :
    (accumulatingSeries * accumulatingSeries).cantorBendixsonValue ≠ 0 := by
  apply mt (cantorBendixsonValue_eq_zero_iff _).mp
  apply not_not.mpr
  have hcoeff (n : ℕ) :
      0 < (accumulatingSeries * accumulatingSeries).coeff (negRecip n + negRecip n) := by
    rw [coeff_mul]
    apply Finset.sum_pos'
    · intro p _
      apply mul_nonneg <;> simp only [accumulatingSeries_coeff] <;> split <;> norm_num
    · refine ⟨(negRecip n, negRecip n), ?_, ?_⟩
      · rw [Finset.mem_addAntidiagonal, accumulatingSeries_support]
        exact ⟨mem_range_self n, mem_range_self n, rfl⟩
      · simp only [accumulatingSeries_coeff, mem_range_self, if_true, one_mul, zero_lt_one]
  have ht := negRecip_tendsto
  apply mem_closure_of_tendsto (by simpa only [add_zero] using ht.add ht)
  exact Filter.Eventually.of_forall fun n ↦ (hcoeff n).ne'

/-- The finite convolution error has value zero on the accumulating support fixture. -/
theorem convolution_error_value :
    (translate (0 : ℝ) (truncLE 0 (accumulatingSeries * accumulatingSeries)) -
      ∑ p ∈ accumulatingSeries.closedSupportAddFiber accumulatingSeries 0,
        translate (-p.1) (truncLE p.1 accumulatingSeries) *
          translate (-p.2) (truncLE p.2 accumulatingSeries)).cantorBendixsonValue = 0 := by
  simpa only [neg_zero] using
    accumulatingSeries.cantorBendixsonValue_convolution_error accumulatingSeries 0

/-- The natural-product upper bound applies to the nonzero infinite-support square. -/
theorem square_value_upper_bound :
    NatOrdinal.of (accumulatingSeries * accumulatingSeries).cantorBendixsonValue ≤
      NatOrdinal.of accumulatingSeries.cantorBendixsonValue *
        NatOrdinal.of accumulatingSeries.cantorBendixsonValue := by
  have hs : accumulatingSeries.support ⊆ Iic 0 := by
    rw [accumulatingSeries_support]
    rintro _ ⟨n, rfl⟩
    simp only [mem_Iic, negRecip_apply]
    exact neg_nonpos.mpr (by positivity)
  exact accumulatingSeries.cantorBendixsonValue_mul_le accumulatingSeries hs hs

/-- Equal nonzero values can cancel completely; the unequal-values hypothesis is necessary. -/
theorem equal_value_cancellation :
    (-accumulatingSeries).cantorBendixsonValue = accumulatingSeries.cantorBendixsonValue ∧
      0 < accumulatingSeries.cantorBendixsonValue ∧
      (accumulatingSeries + -accumulatingSeries).cantorBendixsonValue = 0 := by
  refine ⟨cantorBendixsonValue_neg _,
    Ordinal.omega0_pos.trans_le accumulatingSeries_positive_rank.2, ?_⟩
  rw [add_neg_cancel, cantorBendixsonValue_zero]

/-- An ordinary constant cannot cancel the accumulating part of the test series. -/
theorem constant_does_not_cancel_accumulation :
    (accumulatingSeries + single (0 : ℝ) (1 : ℚ)).cantorBendixsonValue =
      accumulatingSeries.cantorBendixsonValue := by
  have hlt : (single (0 : ℝ) (1 : ℚ)).cantorBendixsonValue <
      accumulatingSeries.cantorBendixsonValue := by
    rw [value_boundary_cases.2.2]
    exact Ordinal.one_lt_omega0.trans_le accumulatingSeries_positive_rank.2
  rw [cantorBendixsonValue_add_eq_max_of_ne _ _ hlt.ne', max_eq_left hlt.le]

private theorem accumulating_support_nonpositive : accumulatingSeries.support ⊆ Iic 0 := by
  rw [accumulatingSeries_support]
  rintro _ ⟨n, rfl⟩
  simp only [mem_Iic, negRecip_apply]
  exact neg_nonpos.mpr (by positivity)

/-- Value one permits an actual infinite tail bounded away from zero. -/
theorem infinite_tail_value_one :
    (translate (-1 : ℝ) accumulatingSeries).support.Infinite ∧
      (translate (-1 : ℝ) accumulatingSeries + single 0 (1 : ℚ)).cantorBendixsonValue = 1 := by
  have hbound : (translate (-1 : ℝ) accumulatingSeries).support ⊆ Iic (-1 : ℝ) := by
    rw [support_translate]
    rintro _ ⟨x, hx, rfl⟩
    simpa only [mem_Iic, add_zero] using
      add_le_add_right (accumulating_support_nonpositive hx) (-1 : ℝ)
  have hnonpos : (translate (-1 : ℝ) accumulatingSeries).support ⊆ Iic 0 :=
    hbound.trans (Iic_subset_Iic.mpr (by norm_num))
  have hz : (translate (-1 : ℝ) accumulatingSeries).cantorBendixsonValue = 0 :=
    (cantorBendixsonValue_eq_zero_iff_support_bounded_lt _ hnonpos).mpr
      ⟨-1, by norm_num, hbound⟩
  constructor
  · intro hf
    have hr := accumulatingSeries.cantorBendixsonRank_translate (-1) 0
    rw [cantorBendixsonRank_of_finite _ hf, eq_comm] at hr
    have hge := accumulatingSeries_positive_rank.1
    rw [hr] at hge
    exact (not_le_of_gt (show (0 : Ordinal) < 1 from zero_lt_one)) hge
  · rw [cantorBendixsonValue_add_eq_max_of_ne _ _ (by
      rw [hz, value_boundary_cases.2.2]; exact zero_ne_one), hz, value_boundary_cases.2.2]
    exact max_eq_right zero_le

/-- A value-one factor with infinite support preserves the accumulating-series value. -/
theorem value_one_factor_preserves_infinite_value :
    ((translate (-1 : ℝ) accumulatingSeries + single 0 (1 : ℚ)) *
      accumulatingSeries).cantorBendixsonValue = accumulatingSeries.cantorBendixsonValue := by
  apply cantorBendixsonValue_mul_of_left_eq_one _ _ _ accumulating_support_nonpositive
    infinite_tail_value_one.2
  intro x hx
  change x ≤ 0
  rcases support_add_subset _ _ hx with hx | hx
  · rw [support_translate] at hx
    obtain ⟨y, hy, rfl⟩ := hx
    exact add_nonpos (by norm_num) (accumulating_support_nonpositive hy)
  · exact (support_single_subset hx : x = 0) ▸ le_rfl

/-- The Leibniz bound is strictly smaller than the predicted square value on an actual
infinite support; this excludes a finite-support or constant-factor substitute. -/
theorem leibniz_infinite_square :
    ∃ ρ : NatOrdinal, 0 < ρ ∧
      ρ < NatOrdinal.of accumulatingSeries.cantorBendixsonValue *
        NatOrdinal.of accumulatingSeries.cantorBendixsonValue ∧
      ∀ᶠ γ in 𝓝[<] (0 : ℝ),
        NatOrdinal.of (translate (-γ) (truncLE γ (accumulatingSeries * accumulatingSeries)) -
          translate (-γ) (truncLE γ accumulatingSeries) * accumulatingSeries -
          accumulatingSeries * translate (-γ) (truncLE γ accumulatingSeries)).cantorBendixsonValue <
            ρ := by
  have hc : 0 ∈ closure accumulatingSeries.support := by
    rw [accumulatingSeries_support]
    exact isClosed_closure.closure_subset (derivedSet_subset_closure _ accumulation)
  let B : Ordinal.AdditivePrincipalAboveOne :=
    ⟨accumulatingSeries.cantorBendixsonValue, by
      rw [accumulatingSeries.cantorBendixsonValue_of_mem hc]
      exact Ordinal.isAdditivelyPrincipal_omega0_opow _,
      Ordinal.one_lt_omega0.trans_le accumulatingSeries_positive_rank.2⟩
  have hρ : 0 < NatOrdinal.of B.residualFactor :=
    pos_iff_ne_zero.mpr B.residualFactor_isAdditivelyPrincipal.ne_zero
  have hV : 0 < NatOrdinal.of B.val := pos_iff_ne_zero.mpr B.2.1.ne_zero
  refine ⟨NatOrdinal.of B.residualFactor * NatOrdinal.of B.val, mul_pos hρ hV, ?_, ?_⟩
  · apply mul_lt_mul_of_pos_right _ hV
    change NatOrdinal.of B.residualFactor < NatOrdinal.of B.val
    rw [← B.naturalResidual_mul_naturalPrincipal]
    simpa only [mul_one] using
      mul_lt_mul_of_pos_left
        (show (1 : NatOrdinal) < NatOrdinal.of B.principalFactor from B.one_lt_principalFactor) hρ
  · exact accumulatingSeries.eventually_cantorBendixsonValue_leibnizRemainder_lt
      accumulatingSeries accumulating_support_nonpositive accumulating_support_nonpositive
      B B rfl rfl le_rfl

/-- The eventual qualifier is essential: negative monomials produce a value-one remainder
at an earlier negative cutoff, although both original values are zero. -/
theorem leibniz_not_all_negative_cutoffs :
    let b : HahnSeries ℝ ℚ := single (-1) 1
    (translate (2 : ℝ) (truncLE (-2) (b * b)) - translate 2 (truncLE (-2) b) * b -
      b * translate 2 (truncLE (-2) b)).cantorBendixsonValue = 1 := by
  dsimp only
  have hz : truncLE (-2 : ℝ) (single (-1) (1 : ℚ)) = 0 := by
    ext x
    by_cases hx : x = -1
    · subst x
      norm_num [HahnSeries.coeff_truncLE]
    · simp [HahnSeries.coeff_truncLE, hx]
  have hprod : (single (-1 : ℝ) (1 : ℚ) * single (-1) 1) = single (-2) 1 := by
    rw [single_mul_single]
    norm_num
  have htr : translate (2 : ℝ) (truncLE (-2) (single (-2) (1 : ℚ))) = single 0 1 := by
    ext x
    by_cases hx : x = 0
    · subst x
      norm_num [HahnSeries.coeff_truncLE]
    · have hx' : x - 2 ≠ -2 := by simpa using hx
      simp [HahnSeries.coeff_truncLE, hx, hx']
  rw [hz, hprod, htr, map_zero, zero_mul, mul_zero, sub_zero, sub_zero]
  exact value_boundary_cases.2.2

/-- Zero-input API smoke test; this does not distinguish the multiplicities. -/
theorem power_remainder_zero_inputs (b : HahnSeries ℝ ℚ) (m : ℕ) (γ : ℝ) :
    leibnizPowerRemainder 0 b m γ = 0 ∧ leibnizPowerRemainder b 0 m γ = 0 := by
  simp [leibnizPowerRemainder_eq]

/-- The ordinary coefficient distinguishes the square rule from the wrong coefficient-one rule. -/
theorem power_remainder_multiplicity :
    let b : HahnSeries ℝ ℚ := 1 + single (-1) 1
    (leibnizPowerRemainder b 1 1 (-1)).coeff 0 = 0 ∧
      (translate 1 (truncLE (-1) (b ^ 2)) -
        translate 1 (truncLE (-1) b) * b).coeff 0 = 1 := by
  let b : HahnSeries ℝ ℚ := 1 + single (-1) 1
  change (leibnizPowerRemainder b 1 1 (-1)).coeff 0 = 0 ∧ _
  have hs : (single (-1 : ℝ) (1 : ℚ)) ^ 2 = single (-2) 1 := by
    rw [pow_two, single_mul_single]
    norm_num
  have hp : b ^ 2 = 1 + 2 * single (-1) 1 + single (-2) 1 := by
    dsimp only [b]
    rw [add_sq, one_pow, mul_one, hs]
  have ht : translate (1 : ℝ) (truncLE (-1) b) = 1 := by
    ext x
    by_cases hx : x = 0
    · subst x
      norm_num [HahnSeries.coeff_truncLE, b]
    · have hn : x - 1 ≠ -1 := by simpa using hx
      suffices x ≤ 0 → x - 1 ≠ 0 by
        simpa [HahnSeries.coeff_truncLE, b, hx, hn] using this
      intro hle he
      linarith
  have h1 : truncLE (-1 : ℝ) (1 : HahnSeries ℝ ℚ) = 0 := by
    ext x
    by_cases hx : x = 0
    · subst x
      norm_num [HahnSeries.coeff_truncLE]
    · simp [HahnSeries.coeff_truncLE, hx]
  constructor
  · rw [leibnizPowerRemainder_eq]
    norm_num only [neg_neg, one_add_one_eq_two, pow_one, mul_one, h1, map_zero,
      mul_zero, sub_zero, ht, one_mul]
    rw [hp]
    norm_num [HahnSeries.coeff_truncLE, b, coeff_nsmul, two_mul,
      show (2 : HahnSeries ℝ ℚ) = 1 + 1 by norm_num]
    have htwo : (2 : HahnSeries ℝ ℚ) = 1 + 1 := by norm_num
    rw [htwo, coeff_add]
    norm_num
  · change (translate (1 : ℝ) (truncLE (-1) (b ^ 2)) -
      translate 1 (truncLE (-1) b) * b).coeff 0 = 1
    rw [ht, one_mul, hp]
    norm_num [HahnSeries.coeff_truncLE, b, two_mul]

/-- The power estimate on an actual accumulating support, for every exponent including zero.
The positive Cantor–Bendixson rank excludes a finite-support or ordinary-constant substitute. -/
theorem power_remainder_infinite_support (m : ℕ) :
    ∃ ρ : NatOrdinal, 0 < ρ ∧
      ρ < NatOrdinal.of accumulatingSeries.cantorBendixsonValue ^ (m + 1) ∧
      ∀ᶠ γ in 𝓝[<] (0 : ℝ),
        NatOrdinal.of (translate (-γ) (truncLE γ (accumulatingSeries ^ (m + 1))) -
          (m + 1) • (translate (-γ) (truncLE γ accumulatingSeries) *
            accumulatingSeries ^ m)).cantorBendixsonValue < ρ := by
  have hc : 0 ∈ closure accumulatingSeries.support := by
    rw [accumulatingSeries_support]
    exact isClosed_closure.closure_subset (derivedSet_subset_closure _ accumulation)
  let B : Ordinal.AdditivePrincipalAboveOne :=
    ⟨accumulatingSeries.cantorBendixsonValue, by
      rw [accumulatingSeries.cantorBendixsonValue_of_mem hc]
      exact Ordinal.isAdditivelyPrincipal_omega0_opow _,
      Ordinal.one_lt_omega0.trans_le accumulatingSeries_positive_rank.2⟩
  have hρ : 0 < NatOrdinal.of B.residualFactor :=
    pos_iff_ne_zero.mpr B.residualFactor_isAdditivelyPrincipal.ne_zero
  have hV : 0 < NatOrdinal.of B.val := pos_iff_ne_zero.mpr B.2.1.ne_zero
  have hlt : NatOrdinal.of B.residualFactor < NatOrdinal.of B.val := by
    rw [← B.naturalResidual_mul_naturalPrincipal]
    simpa only [mul_one] using mul_lt_mul_of_pos_left
      (show (1 : NatOrdinal) < NatOrdinal.of B.principalFactor from B.one_lt_principalFactor) hρ
  refine ⟨NatOrdinal.of B.val ^ m * NatOrdinal.of B.residualFactor,
    mul_pos (pow_pos hV m) hρ, ?_, ?_⟩
  · change NatOrdinal.of B.val ^ m * NatOrdinal.of B.residualFactor <
      NatOrdinal.of B.val ^ (m + 1)
    rw [pow_succ]
    exact mul_lt_mul_of_pos_left hlt (pow_pos hV m)
  · exact accumulatingSeries.eventually_cantorBendixsonValue_powerRemainder_lt
      accumulating_support_nonpositive B rfl m

private theorem finite_strict_cut {y : ℝ} (hy : y < 0) :
    (truncLE y accumulatingSeries).support.Finite := by
  obtain ⟨N, hN⟩ := eventually_atTop.mp (negRecip_tendsto (Ioi_mem_nhds hy))
  apply ((Finset.range N).finite_toSet.image negRecip).subset
  intro x hx
  rw [support_truncLE, accumulatingSeries_support] at hx
  obtain ⟨⟨n, rfl⟩, hn⟩ := hx
  refine ⟨n, ?_, rfl⟩
  simp only [Finset.mem_coe, Finset.mem_range]
  exact lt_of_not_ge fun hge ↦ (not_lt_of_ge hn) (hN n hge)

/-- The accumulating fixture has rank exactly one in value, not merely a positive lower bound. -/
theorem accumulatingSeries_value :
    accumulatingSeries.cantorBendixsonValue = Ordinal.omega0 := by
  have hstage : (accumulatingSeries.closedSupport.cantorBendixson (1 : Ordinal) : Set ℝ) ⊆ {0} := by
    intro y hy
    obtain ⟨hys, hyr⟩ := (accumulatingSeries.mem_support_derivative_iff y 1).mp hy
    have hy0 : y ≤ 0 := closure_minimal accumulating_support_nonpositive isClosed_Iic hys
    by_contra hne
    have hylt : y < 0 := lt_of_le_of_ne hy0 hne
    have hz : accumulatingSeries.cantorBendixsonRank y = 0 := by
      rw [← cantorBendixsonRank_truncLE _ y]
      exact cantorBendixsonRank_of_finite _ (finite_strict_cut hylt) y
    rw [hz] at hyr
    exact not_le_of_gt zero_lt_one hyr
  have hnot : (0 : ℝ) ∉ (accumulatingSeries.closedSupport.cantorBendixson
      ((1 : Ordinal) + 1) : Set ℝ) := by
    rw [TopologicalSpace.Closeds.cantorBendixson_add_one, TopologicalSpace.Closeds.coe_derived]
    intro h
    exact (finite_singleton (0 : ℝ)).not_infinite
      (Set.Infinite.of_accPt (mem_derivedSet.mp (derivedSet_mono _ _ hstage h)))
  have hr : accumulatingSeries.cantorBendixsonRank 0 ≤ 1 := by
    rw [cantorBendixsonRank_eq]
    exact accumulatingSeries.closedSupport.cantorBendixsonRank_le_of_notMem
      accumulatingSeries.closedSupport_isPWO 0 hnot
  have he := hr.antisymm accumulatingSeries_positive_rank.1
  have hm : (0 : ℝ) ∈ closure accumulatingSeries.support := by
    rw [accumulatingSeries_support]
    exact isClosed_closure.closure_subset (derivedSet_subset_closure _ accumulation)
  rw [cantorBendixsonValue_of_mem _ hm, he, Ordinal.opow_one]

private def omegaValue : Ordinal.AdditivePrincipalAboveOne :=
  ⟨Ordinal.omega0, Ordinal.isAdditivelyPrincipal_iff.mpr ⟨1, by simp⟩, Ordinal.one_lt_omega0⟩

private theorem omegaValue_residual : omegaValue.residualFactor = 1 := by
  apply omegaValue.residualFactor_eq_one_of_isInfiniteMultiplicativelyPrincipal
  apply Ordinal.isInfiniteMultiplicativelyPrincipal_iff.mpr
  exact ⟨0, by simp [omegaValue]⟩

/-- The pure-power cancellation theorem proves every power value on an actual infinite support.
Residual cutoffs have value one, so value-one multiplication closes the smaller-product
hypothesis. -/
theorem accumulatingSeries_pow_value (n : ℕ) :
    NatOrdinal.of (accumulatingSeries ^ n).cantorBendixsonValue =
      NatOrdinal.of Ordinal.omega0 ^ n := by
  induction n with
  | zero =>
    simp only [pow_zero]
    apply congrArg NatOrdinal.of
    exact cantorBendixsonValue_of_finite_of_coeff_ne_zero _
      (by rw [support_one]; exact finite_singleton _) (by simp)
  | succ n ih =>
    apply cantorBendixsonValue_pow_eq_of_eventually accumulatingSeries
      accumulating_support_nonpositive omegaValue accumulatingSeries_value n
    apply Filter.Eventually.of_forall
    intro γ hγ
    have hv : (translate (-γ) (truncLE γ accumulatingSeries)).cantorBendixsonValue = 1 := by
      rw [omegaValue_residual] at hγ
      exact NatOrdinal.of.injective hγ
    rw [cantorBendixsonValue_mul_of_left_eq_one _ _ (support_translated_truncLE _ _)
      ((nonpositiveSubring ℝ ℚ).pow_mem accumulating_support_nonpositive _) hv]
    rw [omegaValue_residual]
    simpa only [NatOrdinal.of_one, mul_one, omegaValue] using ih



/-- The two-factor cancellation theorem also closes on the opposite-sign infinite factors.
Its residual-point hypothesis uses the independently proved pure-square value. -/
theorem accumulatingSeries_negative_product_value :
    NatOrdinal.of (accumulatingSeries * -accumulatingSeries).cantorBendixsonValue =
      NatOrdinal.of Ordinal.omega0 ^ 2 := by
  have hc : (-accumulatingSeries).support ⊆ Iic 0 := by
    simpa only [support_neg] using accumulating_support_nonpositive
  have hv : (-accumulatingSeries).cantorBendixsonValue = omegaValue.val := by
    rw [cantorBendixsonValue_neg, accumulatingSeries_value]
    rfl
  have h := cantorBendixsonValue_pow_mul_eq_of_eventually accumulatingSeries
    (-accumulatingSeries) accumulating_support_nonpositive hc omegaValue omegaValue
    accumulatingSeries_value hv le_rfl 0 (by
      apply Filter.Eventually.of_forall
      intro γ hγ
      have ht : (translate (-γ) (truncLE γ accumulatingSeries)).cantorBendixsonValue = 1 := by
        rw [omegaValue_residual] at hγ
        exact NatOrdinal.of.injective hγ
      rw [pow_zero, one_mul, cantorBendixsonValue_mul_of_left_eq_one _ _
        (support_translated_truncLE _ _) ((nonpositiveSubring ℝ ℚ).pow_mem hc 2) ht,
        neg_sq, omegaValue_residual]
      simpa only [NatOrdinal.of_one, mul_one, one_mul, omegaValue, pow_two, pow_zero] using
        accumulatingSeries_pow_value 2)
  simpa only [zero_add, pow_one, omegaValue, pow_two] using h


/-- Unequal positive ranks, mixed signs, and a nonzero constant term are all retained. -/
theorem accumulatingSeries_mixed_rank_product :
    NatOrdinal.of (accumulatingSeries ^ 2 * (1 - accumulatingSeries)).cantorBendixsonValue =
      NatOrdinal.of Ordinal.omega0 ^ 3 := by
  have hb : accumulatingSeries.support ⊆ Iic 0 := by
    rw [accumulatingSeries_support]
    rintro x ⟨n, rfl⟩
    change negRecip n ≤ 0
    rw [negRecip_apply]
    exact neg_nonpos.mpr (by positivity)
  have hc : (1 - accumulatingSeries).support ⊆ Iic 0 :=
    (nonpositiveSubring ℝ ℚ).sub_mem (nonpositiveSubring ℝ ℚ).one_mem hb
  have h1 : (1 : HahnSeries ℝ ℚ).cantorBendixsonValue = 1 :=
    cantorBendixsonValue_of_finite_of_coeff_ne_zero _
      (by rw [support_one]; exact finite_singleton _) (by simp)
  have hv : (1 - accumulatingSeries).cantorBendixsonValue = Ordinal.omega0 := by
    rw [sub_eq_add_neg, cantorBendixsonValue_add_eq_max_of_ne, cantorBendixsonValue_neg,
      accumulatingSeries_value, h1, max_eq_right Ordinal.one_lt_omega0.le]
    rw [cantorBendixsonValue_neg, accumulatingSeries_value, h1]
    exact Ordinal.one_lt_omega0.ne
  rw [cantorBendixsonValue_mul _ _ ((nonpositiveSubring ℝ ℚ).pow_mem hb 2) hc,
    accumulatingSeries_pow_value, hv]
  rfl

open HahnSeries.Nonpositive in
/-- The germ quotient is not the ordinary-coefficient quotient: this series has coefficient
zero at zero and still gives a nonzero germ. -/
theorem accumulatingSeries_survives_germ :
    ∃ b : Nonpositive ℝ ℚ, (b : HahnSeries ℝ ℚ) = accumulatingSeries ∧
      (b : HahnSeries ℝ ℚ).coeff 0 = 0 ∧
      Ideal.Quotient.mk (cantorBendixsonValuation (G := ℝ) (R := ℚ)).supp b ≠ 0 := by
  have hb : accumulatingSeries.support ⊆ Iic 0 := by
    rw [accumulatingSeries_support]
    rintro x ⟨n, rfl⟩
    change negRecip n ≤ 0
    rw [negRecip_apply]
    exact neg_nonpos.mpr (by positivity)
  refine ⟨⟨accumulatingSeries, hb⟩, rfl, ?_, ?_⟩
  · rw [accumulatingSeries_coeff, if_neg]
    rintro ⟨n, hn⟩
    rw [negRecip_apply] at hn
    exact (neg_ne_zero.mpr (one_div_ne_zero (by positivity))) hn
  · rw [ne_eq, Ideal.Quotient.eq_zero_iff_mem, Valuation.mem_supp_iff,
      cantorBendixsonValuation_apply]
    change NatOrdinal.of accumulatingSeries.cantorBendixsonValue ≠ 0
    rw [accumulatingSeries_value]
    exact Ordinal.omega0_ne_zero


open HahnSeries.Nonpositive in
/-- A nonzero negative monomial vanishes in the germ quotient, excluding the zero ideal. -/
theorem negative_monomial_vanishes_germ :
    ∃ b : Nonpositive ℝ ℚ, b ≠ 0 ∧
      Ideal.Quotient.mk (cantorBendixsonValuation (G := ℝ) (R := ℚ)).supp b = 0 := by
  have hb : (HahnSeries.single (-1 : ℝ) (1 : ℚ)).support ⊆ Iic 0 := by
    intro x hx
    have hx' : x = -1 := support_single_subset hx
    simpa only [mem_Iic, hx'] using (show (-1 : ℝ) ≤ 0 by norm_num)
  refine ⟨⟨HahnSeries.single (-1) 1, hb⟩, ?_, ?_⟩
  · intro h
    have h' := congrArg (fun x : Nonpositive ℝ ℚ ↦ (x : HahnSeries ℝ ℚ).coeff (-1)) h
    simp at h'
  · rw [Ideal.Quotient.eq_zero_iff_mem, Valuation.mem_supp_iff,
      cantorBendixsonValuation_apply]
    exact congrArg NatOrdinal.of value_boundary_cases.2.1


open HahnSeries.Nonpositive in
/-- The accumulating series gives a genuine degree-one class whose square is nonzero. -/
theorem accumulatingSeries_graded_class :
    ∃ b : Nonpositive ℝ ℚ, (b : HahnSeries ℝ ℚ) = accumulatingSeries ∧
      cantorBendixsonDegreeValuation b = (1 : WithBot NatOrdinal) ∧
      (cantorBendixsonDegreeValuation (G := ℝ) (R := ℚ)).initialForm b ^ 2 ≠ 0 := by
  obtain ⟨b, hb, -, -⟩ := accumulatingSeries_survives_germ
  have hd : cantorBendixsonDegreeValuation b = (1 : WithBot NatOrdinal) := by
    rw [cantorBendixsonDegreeValuation_apply, cantorBendixsonValuation_apply, hb,
      accumulatingSeries_value]
    simp
  refine ⟨b, hb, hd, ?_⟩
  letI := cantorBendixson_associatedGraded_isDomain (G := ℝ) (R := ℚ)
  exact pow_ne_zero 2
    ((cantorBendixsonDegreeValuation (G := ℝ) (R := ℚ)).initialForm_ne_zero_of_ne_bot
      (by rw [hd]; exact WithBot.coe_ne_bot))

section Derivative

open HahnSeries.Nonpositive

local notation "ν" => (cantorBendixsonDegreeValuation (G := ℝ) (R := ℚ))

/-- The accumulating degree-one class has nonzero derivative, excluding the zero-map substitute. -/
theorem accumulatingSeries_derivative_nonzero :
    ∃ b : (ν).filtrationLE 1, ((b : Nonpositive ℝ ℚ) : HahnSeries ℝ ℚ) =
      accumulatingSeries ∧
      cantorBendixsonGradedDerivation ((ν).homogeneousMk 1 b) ≠ 0 := by
  obtain ⟨b, hb, hd, -⟩ := accumulatingSeries_graded_class
  let a : (ν).filtrationLE 1 := ⟨b, ((ν).mem_filtrationLE_iff _ _).mpr hd.le⟩
  refine ⟨a, hb, ?_⟩
  have ha : (ν).componentMk 1 a ≠ 0 := by
    rw [ne_eq, (ν).componentMk_eq_zero_iff]
    change ¬ ν b < (1 : NatOrdinal)
    rw [hd]
    exact lt_irrefl _
  intro hzero
  apply ha
  have hi := cantorBendixsonGradedDerivation_injective_on_successor
    (G := ℝ) (R := ℚ) 0
  rw [zero_add] at hi
  apply hi
  simpa only [(ν).homogeneousMk_apply, map_zero] using hzero

/-- The additive derivative sends zero to zero. -/
theorem graded_derivative_zero : cantorBendixsonGradedDerivation
    (0 : (ν).AssociatedGraded) = 0 := map_zero _

/-- Every grade-zero class has zero derivative. -/
theorem graded_derivative_constant_grade (a : (ν).Component 0) :
    cantorBendixsonGradedDerivation (DirectSum.of (ν).Component 0 a) = 0 := by
  rw [cantorBendixsonGradedDerivation_of,
    cantorBendixsonHomogeneousDerivation_limit 0 NatOrdinal.constantCoeff_zero,
    AddMonoidHom.zero_apply]

/-- The grade-zero scalar map is an actual coefficient-field equivalence. -/
theorem graded_zero_component_coefficients :
    Function.Bijective (cantorBendixsonLayerScalarHom (G := ℝ) (K := ℚ)) :=
  ⟨cantorBendixsonLayerScalarHom_injective, cantorBendixsonLayerScalarHom_surjective⟩

/-- The standard derivation and additive truncation map agree. -/
theorem graded_derivation_apply
    (x : (ν).AssociatedGraded) :
    cantorBendixsonDerivation x = cantorBendixsonGradedDerivation x :=
  cantorBendixsonDerivation_apply x

/-- The accumulating series exercises both terms of the graded product rule. -/
theorem accumulatingSeries_graded_square_rule :
    ∃ b : (ν).filtrationLE 1, ((b : Nonpositive ℝ ℚ) : HahnSeries ℝ ℚ) =
      accumulatingSeries ∧
      cantorBendixsonGradedDerivation ((ν).homogeneousMk 1 b ^ 2) =
        2 • (cantorBendixsonGradedDerivation ((ν).homogeneousMk 1 b) *
          ((ν).homogeneousMk 1 b : Filter.Germ (𝓝[<] (0 : ℝ)) (ν).AssociatedGraded)) := by
  obtain ⟨b, hb, -⟩ := accumulatingSeries_derivative_nonzero
  refine ⟨b, hb, ?_⟩
  rw [pow_two, cantorBendixsonGradedDerivation_mul, two_smul]
  congr 1
  exact mul_comm _ _

/-- Dropping one of the two square-rule terms is false for the actual accumulating series. -/
theorem accumulatingSeries_graded_square_not_single_copy :
    ∃ b : (ν).filtrationLE 1, ((b : Nonpositive ℝ ℚ) : HahnSeries ℝ ℚ) =
      accumulatingSeries ∧
      cantorBendixsonGradedDerivation ((ν).homogeneousMk 1 b ^ 2) ≠
        cantorBendixsonGradedDerivation ((ν).homogeneousMk 1 b) *
          ((ν).homogeneousMk 1 b : Filter.Germ (𝓝[<] (0 : ℝ)) (ν).AssociatedGraded) := by
  obtain ⟨b, hb, hD⟩ := accumulatingSeries_derivative_nonzero
  refine ⟨b, hb, ?_⟩
  let x := (ν).homogeneousMk 1 b
  have hx : x ≠ 0 := by
    intro hx
    exact hD (by change cantorBendixsonGradedDerivation x = 0; rw [hx, map_zero])
  letI := cantorBendixson_associatedGraded_isDomain (G := ℝ) (R := ℚ)
  have hp : cantorBendixsonGradedDerivation x *
      (x : Filter.Germ (𝓝[<] (0 : ℝ)) (ν).AssociatedGraded) ≠ 0 := by
    intro he
    apply hD
    generalize cantorBendixsonGradedDerivation x = f at he ⊢
    induction f using Filter.Germ.inductionOn with
    | h f =>
      change ((fun γ ↦ f γ * x) : Filter.Germ (𝓝[<] (0 : ℝ)) (ν).AssociatedGraded) = 0 at he
      rw [← Filter.Germ.coe_zero, Filter.Germ.coe_eq] at he ⊢
      filter_upwards [he] with γ hγ
      exact (mul_eq_zero.mp hγ).resolve_right hx
  intro he
  have hs := cantorBendixsonGradedDerivation_mul x x
  rw [← pow_two, he] at hs
  have hc := mul_comm
    (x : Filter.Germ (𝓝[<] (0 : ℝ)) (ν).AssociatedGraded) (cantorBendixsonGradedDerivation x)
  rw [hc] at hs
  exact hp (add_left_cancel (hs.symm.trans (add_zero _).symm))

end Derivative

section GlobalCofactors

open HahnSeries.Nonpositive

local notation "ν" => (cantorBendixsonDegreeValuation (G := ℝ) (R := ℚ))

private theorem accumulating_neg_rank {y : ℝ} (hy : y < 0) :
    accumulatingSeries.cantorBendixsonRank y = 0 := by
  rw [← cantorBendixsonRank_truncLE _ y]
  exact cantorBendixsonRank_of_finite _ (finite_strict_cut hy) y

/-- The literal pointwise assembly conclusion is unsatisfiable at an accumulating rank level:
prescribing the constant one at every rank-zero point of the accumulating support forces a
coefficient one at cutoffs arbitrarily close to zero, while the required bound at the
nonpositive noncenter zero forces the support strictly below zero. The pointwise degree
hypothesis of the top-rank assembly therefore cannot be dropped. -/
theorem no_literal_assembly_at_accumulating_level :
    ∃ u : Nonpositive ℝ ℚ, (u : HahnSeries ℝ ℚ) = accumulatingSeries ∧
      ¬ ∃ c : Nonpositive ℝ ℚ,
        (∀ i : {x // x ∈ (u : HahnSeries ℝ ℚ).closedSupport ∧
            (u : HahnSeries ℝ ℚ).closedSupport.cantorBendixsonRank
              (u : HahnSeries ℝ ℚ).closedSupport_isPWO x = (0 : Ordinal)},
          ν (translatedTruncLE (i : ℝ) c - 1) = ⊥) ∧
        ∀ y : ℝ, y ≤ 0 →
          ¬(y ∈ (u : HahnSeries ℝ ℚ).closedSupport ∧
            (u : HahnSeries ℝ ℚ).closedSupport.cantorBendixsonRank
              (u : HahnSeries ℝ ℚ).closedSupport_isPWO y = (0 : Ordinal)) →
          ν (translatedTruncLE y c) < ((0 : NatOrdinal) : WithBot NatOrdinal) := by
  refine ⟨⟨accumulatingSeries, accumulating_support_nonpositive⟩, rfl, ?_⟩
  set u : Nonpositive ℝ ℚ := ⟨accumulatingSeries, accumulating_support_nonpositive⟩
  rintro ⟨c, hc1, hc2⟩
  have hm0 : (0 : ℝ) ∈ closure accumulatingSeries.support := by
    rw [accumulatingSeries_support]
    exact isClosed_closure.closure_subset (derivedSet_subset_closure _ accumulation)
  have h0rank : (u : HahnSeries ℝ ℚ).cantorBendixsonRank 0 ≠ 0 :=
    Order.one_le_iff_ne_zero.mp accumulatingSeries_positive_rank.1
  have hnc : ¬((0 : ℝ) ∈ (u : HahnSeries ℝ ℚ).closedSupport ∧
      (u : HahnSeries ℝ ℚ).closedSupport.cantorBendixsonRank
        (u : HahnSeries ℝ ℚ).closedSupport_isPWO 0 = (0 : Ordinal)) := by
    rintro ⟨-, hr⟩
    exact h0rank (((u : HahnSeries ℝ ℚ).cantorBendixsonRank_eq 0).trans hr)
  have hcbot : ν c = ⊥ := by
    have hbot := hc2 0 le_rfl hnc
    rw [translatedTruncLE_zero] at hbot
    cases hν : ν c with
    | bot => rfl
    | coe a =>
        rw [hν, WithBot.coe_lt_coe] at hbot
        exact absurd hbot (not_lt_of_ge (zero_le (a := a)))
  obtain ⟨e, he0, hsupp⟩ := (cantorBendixsonDegreeValuation_eq_bot_iff c).mp hcbot
  obtain ⟨n, hn⟩ := eventually_atTop.mp (negRecip_tendsto (Ioi_mem_nhds he0))
  have hen : e < negRecip n := hn n le_rfl
  have hneg : negRecip n < 0 := by
    rw [negRecip_apply]
    simp only [one_div, Left.neg_neg_iff, inv_pos]
    positivity
  have hxsupp : negRecip n ∈ accumulatingSeries.support := by
    rw [accumulatingSeries_support]
    exact ⟨n, rfl⟩
  have hxmem : negRecip n ∈ (u : HahnSeries ℝ ℚ).closedSupport :=
    (HahnSeries.mem_closedSupport _ _).mpr (subset_closure hxsupp)
  have hxrank : (u : HahnSeries ℝ ℚ).closedSupport.cantorBendixsonRank
      (u : HahnSeries ℝ ℚ).closedSupport_isPWO (negRecip n) = (0 : Ordinal) := by
    rw [← (u : HahnSeries ℝ ℚ).cantorBendixsonRank_eq]
    exact accumulating_neg_rank hneg
  have hcen := hc1 ⟨negRecip n, hxmem, hxrank⟩
  obtain ⟨e', he'0, hsupp'⟩ := (cantorBendixsonDegreeValuation_eq_bot_iff _).mp hcen
  have h0diff : (0 : ℝ) ∉
      ((translatedTruncLE (negRecip n) c - 1 : Nonpositive ℝ ℚ) : HahnSeries ℝ ℚ).support := by
    intro h
    exact absurd (hsupp' h) (not_le.mpr he'0)
  have hcoeff : (c : HahnSeries ℝ ℚ).coeff (negRecip n) = 1 := by
    have hzero : ((translatedTruncLE (negRecip n) c - 1 : Nonpositive ℝ ℚ) :
        HahnSeries ℝ ℚ).coeff 0 = 0 := by
      by_contra hne
      exact h0diff ((HahnSeries.mem_support _ _).mpr hne)
    rw [AddSubgroupClass.coe_sub, HahnSeries.coeff_sub, coe_translatedTruncLE,
      coeff_translate, zero_sub, neg_neg, HahnSeries.coeff_truncLE, if_pos le_rfl,
      OneMemClass.coe_one, HahnSeries.coeff_one, if_pos rfl, sub_eq_zero] at hzero
    exact hzero
  have hxin : negRecip n ∈ (c : HahnSeries ℝ ℚ).support :=
    (HahnSeries.mem_support _ _).mpr (by rw [hcoeff]; exact one_ne_zero)
  exact absurd (hsupp hxin) (not_le.mpr hen)

/-- On the accumulating fixture, a degree-zero cofactor of the series itself makes every
translated truncation have degree strictly below one. The zero cofactor is not a substitute,
because the original series keeps degree one at cutoff zero. -/
theorem accumulating_global_cofactor :
    ∃ u c : Nonpositive ℝ ℚ, (u : HahnSeries ℝ ℚ) = accumulatingSeries ∧
      (∀ x : ℝ, x ≤ 0 → ν (translatedTruncLE x c) ≤ (0 : NatOrdinal)) ∧
      (∀ x : ℝ, x ≤ 0 →
        ν (translatedTruncLE x (u - c * u)) < ((1 : NatOrdinal) : WithBot NatOrdinal)) ∧
      c ≠ 0 := by
  classical
  set u : Nonpositive ℝ ℚ := ⟨accumulatingSeries, accumulating_support_nonpositive⟩ with hu_def
  have hν1 : ν u = ((1 : NatOrdinal) : WithBot NatOrdinal) := by
    rw [cantorBendixsonDegreeValuation_apply, cantorBendixsonValuation_apply]
    have hval : (u : HahnSeries ℝ ℚ).cantorBendixsonValue = Ordinal.omega0 :=
      accumulatingSeries_value
    rw [hval]
    simp
  have huneg : ∀ {y : ℝ}, y < 0 → (u : HahnSeries ℝ ℚ).cantorBendixsonRank y = 0 :=
    fun hy ↦ accumulating_neg_rank hy
  have hcut0 : ∀ x : ℝ, x < 0 →
      ν (translatedTruncLE x u) < ((1 : NatOrdinal) : WithBot NatOrdinal) := by
    intro x hx
    rw [degree_translatedTruncLE_eq]
    by_cases hxm : x ∈ (u : HahnSeries ℝ ℚ).closedSupport
    · rw [if_pos hxm, huneg hx, NatOrdinal.of_zero, WithBot.coe_lt_coe]
      exact zero_lt_one
    · rw [if_neg hxm]
      exact WithBot.bot_lt_coe 1
  have hu : ∀ x : ℝ, x ≤ 0 →
      ν (translatedTruncLE x u) ≤ ((1 : NatOrdinal) : WithBot NatOrdinal) := by
    intro x hx
    rcases eq_or_lt_of_le hx with hx0 | hxneg
    · subst hx0
      rw [translatedTruncLE_zero]
      exact hν1.le
    · exact (hcut0 x hxneg).le
  have hlevel0 : ∀ i : {x // x ∈ (u : HahnSeries ℝ ℚ).closedSupport ∧
      (u : HahnSeries ℝ ℚ).closedSupport.cantorBendixsonRank
        (u : HahnSeries ℝ ℚ).closedSupport_isPWO x = (1 : NatOrdinal).val},
      (i : ℝ) = 0 := by
    rintro ⟨x, hxm, hxr⟩
    by_contra hne
    have hx0 : x ≤ 0 := closure_minimal u.property isClosed_Iic
      ((HahnSeries.mem_closedSupport _ _).mp hxm)
    have hxneg : x < 0 := lt_of_le_of_ne hx0 hne
    have h0 : (u : HahnSeries ℝ ℚ).closedSupport.cantorBendixsonRank
        (u : HahnSeries ℝ ℚ).closedSupport_isPWO x = 0 := by
      rw [← (u : HahnSeries ℝ ℚ).cantorBendixsonRank_eq]
      exact huneg hxneg
    rw [h0] at hxr
    have : (1 : NatOrdinal).val = (1 : Ordinal) := NatOrdinal.val_one
    rw [this] at hxr
    exact zero_ne_one hxr
  obtain ⟨c, hcb, hres⟩ := exists_forall_degree_translatedTruncLE_sub_sum_mul_lt
    (G := ℝ) (R := ℚ) 1 (ι := Unit) (fun _ ↦ u) (fun _ ↦ 0) (fun _ ↦ 1)
    (fun _ ↦ (zero_add 1).le) (fun _ ↦ hν1.le) (fun _ ↦ hcut0) u hu (fun _ _ ↦ 1)
    (fun _ _ ↦ (ν).map_one_le_zero) (fun i ↦ by
      rw [hlevel0 i, translatedTruncLE_zero]
      have hsum : (∑ _j : Unit, (1 : Nonpositive ℝ ℚ) * u) = u := by
        rw [Fintype.sum_unique, one_mul]
      rw [hsum, sub_self, (ν).map_zero]
      exact WithBot.bot_lt_coe 1)
  have hsum : (∑ j : Unit, c j * u) = c () * u := by
    rw [Fintype.sum_unique]
  refine ⟨u, c (), rfl, fun x hx ↦ ?_, fun x hx ↦ ?_, ?_⟩
  · exact hcb () x hx
  · have := hres x hx
    rwa [hsum] at this
  · intro hzero
    have := hres 0 le_rfl
    rw [hsum, hzero, zero_mul, sub_zero, translatedTruncLE_zero, hν1] at this
    exact lt_irrefl _ this

end GlobalCofactors

section Lifts

open HahnSeries.Nonpositive MvPolynomial

local notation "ν" => (cantorBendixsonDegreeValuation (G := ℝ) (R := ℚ))

/-- Two distinct series lift one nonzero degree-one class; their difference has bottom degree.
Lifting detects the class, not the series. -/
theorem distinct_lifts_of_one_class :
    ∃ u u' : Nonpositive ℝ ℚ, u ≠ u' ∧
      ∃ e : (ν).AssociatedGraded, e ≠ 0 ∧
        Represents u 1 e ∧ Represents u' 1 e ∧ ν (u - u') = ⊥ := by
  classical
  obtain ⟨u, hu, hd, -⟩ := accumulatingSeries_graded_class
  have hle : ν u ≤ (1 : NatOrdinal) := hd.le
  have hs : (HahnSeries.single (-1 : ℝ) (1 : ℚ)).support ⊆ Iic 0 := by
    intro x hx
    have hx' : x = -1 := support_single_subset hx
    simp only [mem_Iic, hx']
    norm_num
  set s : Nonpositive ℝ ℚ := ⟨HahnSeries.single (-1) 1, hs⟩ with hs_def
  have hsbot : ν s = ⊥ := by
    apply (cantorBendixsonDegreeValuation_eq_bot_iff s).mpr
    refine ⟨-1, by norm_num, ?_⟩
    intro x hx
    have hx' : x = -1 := support_single_subset hx
    simp only [mem_Iic, hx', le_refl]
  set e : (ν).AssociatedGraded :=
    (ν).homogeneousMk 1 ⟨u, ((ν).mem_filtrationLE_iff 1 u).mpr hle⟩ with he_def
  have hrepu : Represents u 1 e := represents_iff.mpr ⟨hle, rfl⟩
  have hrepu' : Represents (u + s) 1 e := by
    have h := hrepu.add (represents_of_degree_lt (m := 1)
      (by rw [hsbot]; exact WithBot.bot_lt_coe 1))
    rwa [add_zero] at h
  refine ⟨u, u + s, ?_, e, ?_, hrepu, hrepu', ?_⟩
  · intro huu
    have hc := congrArg (fun z : Nonpositive ℝ ℚ ↦ (z : HahnSeries ℝ ℚ).coeff (-1)) huu
    have hadd : ((u + s : Nonpositive ℝ ℚ) : HahnSeries ℝ ℚ).coeff (-1) =
        (u : HahnSeries ℝ ℚ).coeff (-1) + 1 := by
      have hcoe : ((u + s : Nonpositive ℝ ℚ) : HahnSeries ℝ ℚ) =
          (u : HahnSeries ℝ ℚ) + HahnSeries.single (-1) 1 := rfl
      rw [hcoe, HahnSeries.coeff_add, HahnSeries.coeff_single_same]
    change (u : HahnSeries ℝ ℚ).coeff (-1) =
      ((u + s : Nonpositive ℝ ℚ) : HahnSeries ℝ ℚ).coeff (-1) at hc
    rw [hadd] at hc
    nth_rewrite 1 [← add_zero ((u : HahnSeries ℝ ℚ).coeff (-1))] at hc
    exact zero_ne_one (add_left_cancel hc)
  · rw [he_def, ne_eq, (ν).homogeneousMk_eq_zero_iff]
    rw [hd]
    exact lt_irrefl _
  · rw [show u - (u + s) = -s by ring, (ν).map_neg, hsbot]

/-- Without independence of the lifted classes, a nonzero polynomial with small weights can
evaluate to bottom degree: the injectivity hypothesis of the uniqueness clause is not
removable. -/
theorem pol_uniqueness_needs_independence :
    ¬ ∀ (wt : Bool → NatOrdinal.{0}) (V : Bool → Nonpositive ℝ ℚ) (F : MvPolynomial Bool ℚ),
        (∀ d ∈ F.support, (Finsupp.weight wt) d < 2) → ν (aeval V F) = ⊥ → F = 0 := by
  classical
  intro h
  obtain ⟨u, u', hne, -, -, -, -, hbot⟩ := distinct_lifts_of_one_class
  have hF : (MvPolynomial.X true - MvPolynomial.X false : MvPolynomial Bool ℚ) = 0 := by
    apply h (fun _ ↦ 1) (fun b ↦ bif b then u else u')
    · intro d hd
      have hd' := MvPolynomial.support_sub Bool (MvPolynomial.X true) (MvPolynomial.X false) hd
      have hw : (Finsupp.weight (fun _ : Bool ↦ (1 : NatOrdinal.{0}))) d = 1 := by
        rcases Finset.mem_union.mp hd' with hd'' | hd'' <;>
          · rw [MvPolynomial.support_X] at hd''
            rw [Finset.mem_singleton.mp hd'', Finsupp.weight_single, one_nsmul]
      rw [hw]
      exact one_lt_two
    · rw [map_sub, aeval_X, aeval_X]
      simpa only [Bool.cond_true, Bool.cond_false] using hbot
  have hXX := sub_eq_zero.mp hF
  exact absurd (MvPolynomial.X_injective hXX) (by decide)

/-- The polynomial of a series modulo bounded series, run below degree one with no generators:
the machinery extracts the constant term, and only the correct constant works. -/
theorem degree_lt_one_constant_extraction :
    ∃ u : Nonpositive ℝ ℚ,
      (u : HahnSeries ℝ ℚ) = 1 + HahnSeries.single (-1 : ℝ) (1 : ℚ) ∧
      (∃ c : ℚ, ν (u - algebraMap ℚ (Nonpositive ℝ ℚ) c) = ⊥) ∧
      ∀ c : ℚ, ν (u - algebraMap ℚ (Nonpositive ℝ ℚ) c) = ⊥ → c = 1 := by
  classical
  have hs : (1 + HahnSeries.single (-1 : ℝ) (1 : ℚ)).support ⊆ Iic 0 := by
    intro x hx
    rcases HahnSeries.support_add_subset _ _ hx with hx' | hx'
    · rw [HahnSeries.support_one] at hx'
      simp only [mem_singleton_iff] at hx'
      simp [hx']
    · have hx'' : x = -1 := support_single_subset hx'
      simp only [mem_Iic, hx'']
      norm_num
  set u : Nonpositive ℝ ℚ := ⟨1 + HahnSeries.single (-1) 1, hs⟩ with hu_def
  have hcoeff0 : (u : HahnSeries ℝ ℚ).coeff 0 = 1 := by
    change (1 + HahnSeries.single (-1 : ℝ) (1 : ℚ)).coeff 0 = 1
    rw [HahnSeries.coeff_add, HahnSeries.coeff_one, if_pos rfl,
      HahnSeries.coeff_single_of_ne (by norm_num : (0 : ℝ) ≠ -1), add_zero]
  have hufin : (u : HahnSeries ℝ ℚ).support.Finite := by
    apply Set.Finite.subset ((Set.finite_singleton (-1 : ℝ)).insert 0)
    intro x hx
    rcases HahnSeries.support_add_subset _ _ hx with hx' | hx'
    · rw [HahnSeries.support_one] at hx'
      exact Set.mem_insert_iff.mpr (Or.inl (mem_singleton_iff.mp hx'))
    · exact Set.mem_insert_iff.mpr (Or.inr (support_single_subset hx'))
  have hu0 : ν u ≤ (0 : NatOrdinal) := by
    rw [cantorBendixsonDegreeValuation_apply, cantorBendixsonValuation_apply,
      cantorBendixsonValue_of_finite_of_coeff_ne_zero _ hufin
        (by rw [hcoeff0]; exact one_ne_zero),
      NatOrdinal.of_one, NatOrdinal.cantorDegree_eq_ordinalCantorDegree,
      NatOrdinal.val_one, Ordinal.cantorDegree_one, WithBot.coe_zero]
  have hgen : ∀ β : NatOrdinal.{0}, β < 1 →
      ∀ y ∈ DirectSum.rangeLof ℚ (ν).Component β,
        ∃ F : MvPolynomial Empty ℚ, IsWeightedHomogeneous (fun _ ↦ 1) F β ∧
          aeval (fun _ ↦ (0 : (ν).AssociatedGraded)) F = y := by
    intro β hβ y hy
    have hβ0 : β = 0 := by
      have h01 : β < 0 + 1 := by rwa [zero_add]
      exact le_antisymm (Order.lt_add_one_iff.mp h01) (zero_le (a := β))
    subst hβ0
    obtain ⟨a, rfl⟩ := (DirectSum.mem_rangeLof_iff ℚ (ν).Component 0 y).mp hy
    obtain ⟨k, hk⟩ := cantorBendixsonLayerScalarHom_surjective (G := ℝ) (K := ℚ) a
    refine ⟨C k, isWeightedHomogeneous_C _ k, ?_⟩
    rw [aeval_C, cantorBendixson_algebraMap_apply, hk, DirectSum.lof_eq_of]
  obtain ⟨F, -, -, hFbot⟩ := exists_forall_weight_lt_and_degree_sub_aeval_eq_bot
    (V := fun _ ↦ 0) (fun _ ↦ (0 : (ν).AssociatedGraded))
    (fun i ↦ i.elim) 1 hgen u (hu0.trans_lt (WithBot.coe_lt_coe.mpr zero_lt_one))
  obtain ⟨c, hc⟩ := MvPolynomial.C_surjective Empty F
  refine ⟨u, rfl, ⟨c, ?_⟩, ?_⟩
  · rw [← hc, aeval_C] at hFbot
    exact hFbot
  · intro c hc'
    obtain ⟨e, he0, hesupp⟩ := (cantorBendixsonDegreeValuation_eq_bot_iff _).mp hc'
    have h0notin : (0 : ℝ) ∉
        ((u - algebraMap ℚ (Nonpositive ℝ ℚ) c : Nonpositive ℝ ℚ) : HahnSeries ℝ ℚ).support :=
      fun h ↦ absurd (hesupp h) (not_le.mpr he0)
    have hz : ((u - algebraMap ℚ (Nonpositive ℝ ℚ) c : Nonpositive ℝ ℚ) :
        HahnSeries ℝ ℚ).coeff 0 = 0 := by
      by_contra hnz
      exact h0notin ((HahnSeries.mem_support _ _).mpr hnz)
    rw [AddSubgroupClass.coe_sub, HahnSeries.coeff_sub, hcoeff0,
      HahnSeries.Nonpositive.algebraMap_apply, coe_C, HahnSeries.C_apply,
      HahnSeries.coeff_single_same, sub_eq_zero] at hz
    exact hz.symm

end Lifts

end Tests.PWOAddition
