/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

import ConwayRefinement.Blueprint
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.LimitOrdinalRelationAtCutoff
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.TruncationExpansion

/-!
# Linear occurrence of a maximal variable

The differentiated truncation expansion makes all sufficiently high components of the maximal
partial derivative vanish. If that variable occurred at least twice, ordinal separation would
put the cutoff strictly below the derivative's degree. A sufficiently late translated truncation
then has degree above the cutoff, contradicting the vanishing.
-/

universe u v w

open scoped NatOrdinal Topology

open Filter MvPolynomial HahnSeries HahnSeries.Nonpositive

public noncomputable section

namespace HahnSeries.Germ

variable {G : Type u} {K : Type v}
variable [AddCommGroup G] [LinearOrder G] [IsOrderedAddMonoid G]
  [UniformSpace G] [IsUniformAddGroup G] [OrderTopology G] [Nontrivial G] [CompleteSpace G]
  [Field K] [CharZero K]

local notation "ν" => (cantorBendixsonDegreeValuation (G := G) (R := K))

variable {ι : Type w} {wt : ι → NatOrdinal.{u}}
  {xg : ι → (cantorBendixsonDegreeValuation (G := G) (R := K)).AssociatedGraded}
variable {σ : LiftFamily wt xg} {α : NatOrdinal.{u}}

namespace LimitOrdinalRelationAtCutoff

variable (S : LimitOrdinalRelationAtCutoff σ α)
variable (hx : OrdinalGraded.IsMinimalSystem
  (DirectSum.rangeLof K (cantorBendixsonDegreeValuation (G := G) (R := K)).Component) wt xg)

include hx in
/-- Under the cutoff bounds used when the degree is a limit ordinal, a maximal variable occurs
linearly. -/
@[blueprint "lem:linear-occurrence"
  (phase := "Algebraic independence in graded rings")
  (title := "Maximal-variable linearity for the Cantor--Bendixson degree")
  (statement := /--
    Let $K$ be a field of characteristic zero and $G$ a nontrivial complete
    ordered abelian group with compatible additive uniformity and order
    topology. Let $x_i$ be a minimal homogeneous generating system for the
    associated graded ring of the degree filtration, of weights $w_i$. Choose
    series $b_i$ representing $x_i$ such that
    \[
      \deg(b_i)\le w_i,
      \qquad \deg(b_i^{\vert y})<w_i\quad\text{for every }y<0.
    \]
    Assume
    evaluation at $x_i$ is injective in every degree below $\alpha$.

    Let $0\ne F\in K[X_i:i\in I]$ be weighted homogeneous of degree $\alpha$
    with $F(x)=0$. Suppose every variable of $F$ has weight below $\alpha$
    and zero constant Cantor coefficient. Choose $X_{B_0}$ of maximal weight
    among the variables of $F$, and put $D=\deg_{X_{B_0}}F$. Suppose there
    are ordinals $\beta,\Delta,\lambda_0,\alpha_1$ such that
    \[
      \Delta+D w_{B_0}=\alpha,
      \qquad \Delta\ne0,
      \qquad \lambda_0<\alpha_{<\beta},
    \]
    every Cantor term of $\Delta$ is at least $\omega^\beta$, and the last
    Cantor term of $w_{B_0}$ is below $\omega^\beta$. Assume also
    \[
      \alpha_1\le\alpha_{\ge\beta}\oplus\lambda_0,
      \qquad \alpha_1\le\alpha,
    \]
    that near $0$ every translated truncation of $F(b)$ has degree below
    $\alpha_1$, and that every convolution term $\rho$ using at least two
    translated truncations satisfies
    $\rho<\alpha_{\ge\beta}\oplus\lambda_0$.

    Then $D=1$.
  -/)
  (proof := /--
  Suppose $D\ge2$ and put $\Theta=\partial_{B_0}F$. Then $\Theta\ne0$ is
  homogeneous of degree
  $h=\Delta\oplus(D-1)w_{B_0}<\alpha$. Injectivity below $\alpha$ makes
  $\Theta(b)$ have degree exactly $h$.

  Put $t=(w_{B_0})_{<\beta}$. The hypotheses give
  $\alpha_{<\beta}=Dt$ and
  $\lambda_0\oplus1<(D-1)t\oplus t$. By
  \ref{lem:natural-sum-approach}, choose $s<(D-1)t$ with
  $\lambda_0\oplus1\le s\oplus t$, and set
  $\tau=h_{\ge\beta}\oplus s<h$.

  By \ref{lem:local-jacobian-ideal-membership}, every component of a
  sufficiently late polynomial representative of $\Theta(b)^{\vert\gamma}$
  of degree at least $\tau$ lies in the ideal generated by variables of $F$ whose
  weights are strictly larger than $w_{B_0}$. Maximality of $B_0$ makes this
  ideal zero. But the translated truncation of the degree-$h$ series
  $\Theta(b)$ has degree at least $\tau$, so its representative has a nonzero
  component in that range, a contradiction.
  -/)]
theorem degreeOf_eq_one
    (hσ : LiftFamily.HasLowerTruncationDegrees σ)
    (hinj : ∀ β < α, OrdinalGraded.InjectiveAt K wt xg β) :
    degreeOf S.B₀ S.F = 1 := by
  classical
  set D := degreeOf S.B₀ S.F with hDdef
  have hD1 : 1 ≤ D := Nat.one_le_iff_ne_zero.mpr
    (mem_vars_iff_degreeOf_ne_zero.mp S.mem)
  by_contra hne
  have hD2 : 2 ≤ D := by omega
  set g := wt S.B₀ with hgdef
  set t := S.degLT S.B₀ with htdef
  have ht0 : t ≠ 0 := by simpa only [htdef] using S.degLT_B₀_ne_zero hx
  have hg0 : g ≠ 0 := by simpa only [hgdef] using hx.ne_zero S.B₀
  have hμ : S.αLT = D • t := by
    rw [S.αLT_eq_nsmul_degLT, ← hDdef, ← htdef]
  have hμcc : S.αLT.constantCoeff = 0 := S.αLT_constantCoeff hx
  set h : NatOrdinal := S.degHD + (D - 1) • g with hhdef
  have hhg : h + g = α := by
    rw [hhdef, add_assoc, ← succ_nsmul, Nat.sub_add_cancel hD1, hgdef]
    simpa only [← hDdef] using S.hdegHD
  have hhα : h < α := by
    rw [← hhg]
    exact lt_add_of_pos_right _ (pos_iff_ne_zero.mpr hg0)
  have hhLT : NatOrdinal.partLT S.β h = (D - 1) • t := by
    rw [hhdef, NatOrdinal.partLT_add, S.partLT_degHD, zero_add,
      NatOrdinal.partLT_nsmul, hgdef, ← S.degLT_def, ← htdef]
  set Θ := pderiv S.B₀ S.F with hΘdef
  have hΘhom : IsWeightedHomogeneous wt Θ h := by
    rw [hΘdef]
    exact isWeightedHomogeneous_pderiv wt S.hom S.B₀ hhg
  have hΘ0 : Θ ≠ 0 := pderiv_ne_zero_of_mem_vars S.mem
  have hdegree : ν (aeval σ.lift Θ) = (h : WithBot NatOrdinal) := by
    have hrep := σ.represents_aeval hΘhom
    have hgrade : aeval xg Θ ≠ 0 := by
      intro hzero
      exact hΘ0 (((OrdinalGraded.injectiveAt_iff h).mp (hinj h hhα)) Θ hΘhom hzero)
    exact hrep.degree_eq hgrade
  have hlam : (D - 1) • t ≠ 0 :=
    NatOrdinal.nsmul_ne_zero_of_ne_zero ht0 (by omega)
  have hsig : t = 0 ∨
      NatOrdinal.leastTerm ((D - 1) • t) ≤ NatOrdinal.leastTerm t :=
    Or.inr (le_of_eq (NatOrdinal.leastTerm_nsmul ht0 (by omega)))
  have htau : S.lam₀ + 1 < (D - 1) • t + t := by
    rw [← succ_nsmul, Nat.sub_add_cancel hD1, ← hμ]
    refine lt_of_le_of_ne (Order.add_one_le_of_lt (S.αLT_def ▸ S.lam₀_lt)) fun heq ↦ ?_
    have hcc := congrArg NatOrdinal.constantCoeff heq
    rw [hμcc, show S.lam₀ + 1 = S.lam₀ + ((1 : ℕ) : NatOrdinal) by rw [Nat.cast_one],
      NatOrdinal.constantCoeff_add_natCast] at hcc
    omega
  obtain ⟨s, hslt, hs⟩ := NatOrdinal.exists_lt_le_add_of_lastCantorTerm_le hlam hsig htau
  set τ : NatOrdinal := NatOrdinal.partGE S.β h + s with hτdef
  have hτh : τ < h := by
    conv_rhs => rw [← NatOrdinal.partGE_add_partLT S.β h]
    rw [hhLT]
    exact add_lt_add_right hslt _
  have hτα : S.αGE + S.lam₀ ≤ τ + g := by
    have htpart : t = NatOrdinal.partLT S.β g := by
      rw [htdef, S.degLT_def, hgdef]
    have hpart : S.αGE = NatOrdinal.partGE S.β h + NatOrdinal.partGE S.β g := by
      have hcongr := congrArg (NatOrdinal.partGE S.β) hhg
      rw [NatOrdinal.partGE_add] at hcongr
      exact S.αGE_def.trans hcongr.symm
    have heq : τ + g = S.αGE + (s + t) := by
      calc
        τ + g = (NatOrdinal.partGE S.β h + s) +
            (NatOrdinal.partGE S.β g + NatOrdinal.partLT S.β g) := by
          rw [hτdef, NatOrdinal.partGE_add_partLT]
        _ = S.αGE + (s + t) := by rw [hpart, htpart]; abel
    rw [heq]
    exact add_le_add_right ((lt_add_one S.lam₀).le.trans hs) _
  obtain ⟨l, hl, htrunc⟩ := eventually_nhdsLT_iff_exists.mp S.truncation_lt
  have hzero : ∀ γ : G, l < γ → γ < 0 →
      componentsGE wt τ (σ.pol hx α
        (translatedTruncLE γ (aeval σ.lift Θ))) = 0 := by
    intro γ hγ hγ0
    have hτα' : NatOrdinal.partGE S.β α + S.lam₀ ≤ τ + wt S.B₀ := by
      rwa [← S.αGE_def, ← hgdef]
    have hmem := σ.componentsGE_pol_translatedTruncLE_aeval_pderiv_mem hx hσ hinj S.hom
      S.vars_lt S.α₁_le S.α₁_le_α hγ0 (htrunc γ hγ hγ0) S.remainder_lt S.B₀
        (τ := τ) hτα'
    rw [← hΘdef] at hmem
    have hempty : IsEmpty {j : ι // j ∈ S.F.vars ∧ wt S.B₀ < wt j} :=
      ⟨fun j ↦ absurd j.2.2 (not_lt.mpr (S.max j.1 j.2.1))⟩
    rwa [Set.range_eq_empty, Ideal.span_empty, Ideal.mem_bot] at hmem
  have hbound : τ < h + 0 := by simpa only [add_zero] using hτh
  have hh0 : h ≠ 0 := ne_of_gt (zero_le.trans_lt hτh)
  apply σ.false_of_forall_weightedTotalDegree_pol_add_lt hx hdegree hh0
    (Or.inl rfl) hbound hl
  · intro γ hγ hγ0 hp0
    have hdeglt : weightedTotalDegree wt
        (σ.pol hx α (translatedTruncLE γ (aeval σ.lift Θ))) < τ := by
      obtain ⟨d, hd, hsup⟩ := Finset.exists_mem_eq_sup _ (support_nonempty.mpr hp0)
        (Finsupp.weight wt)
      rw [weightedTotalDegree, hsup]
      by_contra hnot
      have hle : τ ≤ Finsupp.weight wt d := not_lt.mp hnot
      have hcoeff := congrArg (MvPolynomial.coeff d) (hzero γ hγ hγ0)
      rw [coeff_componentsGE, if_pos hle, MvPolynomial.coeff_zero] at hcoeff
      exact mem_support_iff.mp hd hcoeff
    simpa only [add_zero] using hdeglt
  · exact hhα

end LimitOrdinalRelationAtCutoff

end HahnSeries.Germ

end
