/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.PartialDerivativeIndices
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.TruncationExpansion
public import ConwayRefinement.HahnSeries.Germ.AlgebraicIndependence.CofactorInduction

import ConwayRefinement.Blueprint

/-!
# Partial-derivative identities when the degree is a limit ordinal

When the Cantor terms below a cutoff in one variable's weight add to the chosen ordinal bound, its
partial derivative is generated by partial derivatives at explicitly determined variables. The
differentiated truncation expansion gives ideal membership near zero. A decreasing neighbourhood
basis of open convex subgroups turns that eventual condition into a polynomial identity, and strong
induction on the finite set of larger variables eliminates intervening partial derivatives.
-/

universe u v w x

open scoped NatOrdinal Topology

open Filter MvPolynomial HahnSeries HahnSeries.Nonpositive

public noncomputable section

namespace HahnSeries.Germ

variable {G : Type u} {K : Type v}
variable [AddCommGroup G] [LinearOrder G] [IsOrderedAddMonoid G]
  [UniformSpace G] [IsUniformAddGroup G] [OrderTopology G] [Nontrivial G] [CompleteSpace G]
  [Field K] [CharZero K] [DenselyOrdered G] [NoMinOrder G] [NoMaxOrder G]

local notation "ν" => (cantorBendixsonDegreeValuation (G := G) (R := K))

variable {κ : Type x} [LinearOrder κ] [WellFoundedLT κ]
variable (Ubase : κ → AddSubgroup G)
variable (hUmono : ∀ {i j : κ}, i ≤ j → (Ubase j : Set G) ⊆ (Ubase i : Set G))
variable (hUopen : ∀ i, IsOpen (Ubase i : Set G))
variable (hUconv : ∀ i, (Ubase i : Set G).OrdConnected)
variable (hUbase : ∀ ε : G, 0 < ε → ∃ i, (Ubase i : Set G) ⊆ Set.Ioo (-ε) ε)

variable {ι : Type w} {wt : ι → NatOrdinal.{u}}
  {xg : ι → (cantorBendixsonDegreeValuation (G := G) (R := K)).AssociatedGraded}
variable {σ : LiftFamily wt xg} {α : NatOrdinal.{u}} (S : LimitOrdinalRelationAtCutoff σ α)
variable (hx : OrdinalGraded.IsMinimalSystem
  (DirectSum.rangeLof K (cantorBendixsonDegreeValuation (G := G) (R := K)).Component) wt xg)
variable (hinj : ∀ β < α, OrdinalGraded.InjectiveAt K wt xg β)
variable (hσ : LiftFamily.HasLowerTruncationDegrees σ)

namespace LimitOrdinalRelationAtCutoff

include Ubase hUmono hUopen hUconv hUbase S hx hinj hσ

/-- A partial derivative satisfying the cutoff equation is a finite combination of the designated
partial derivatives, with every cofactor independent of the maximal variable. -/
@[blueprint "lem:limit-ordinal-partial-derivative-decomposition"
  (phase := "Algebraic independence in graded rings")
  (title := "Partial-derivative decomposition when the degree is a limit ordinal")
  (statement := /--
    Let $K$ be a field of characteristic zero and let $G$ be a nontrivial,
    densely ordered abelian group without endpoints, equipped with a compatible
    additive uniformity and order topology.  Assume that $G$ is Cauchy
    complete.  Let
    $(U_i)_{i\in J}$ be a decreasing family of open convex additive subgroups,
    indexed by a well-founded linear order, such that for every $\varepsilon>0$
    some $U_i$ is contained in $(-\varepsilon,\varepsilon)$.

    Let $x_i$ be a minimal homogeneous generating system for the associated
    graded ring of the degree filtration, of weights $w_i$. Choose series
    $b_i$ representing $x_i$ such that
    \[
      \deg(b_i)\le w_i,
      \qquad \deg(b_i^{\vert y})<w_i\quad\text{for every }y<0.
    \]
    Assume
    evaluation at $x_i$ is injective in every degree below $\alpha$.

    Let $0\ne F\in K[X_i:i\in I]$ be weighted homogeneous of degree $\alpha$
    with $F(x)=0$. Suppose every variable of $F$ has weight below $\alpha$ and
    zero constant Cantor coefficient. Choose $X_{B_0}$ of maximal weight and
    put $D=\deg_{X_{B_0}}F$. Suppose there are ordinals
    $\beta,\Delta,\lambda_0,\alpha_1$ such that
    \[
      \Delta+D w_{B_0}=\alpha,
      \quad \Delta\ne0,
      \quad \lambda_0<\alpha_{<\beta},
      \quad \alpha_1\le\alpha,
      \quad \alpha_1\le\alpha_{\ge\beta}\oplus\lambda_0,
    \]
    every Cantor term of $\Delta$ is at least $\omega^\beta$, and the last
    Cantor term of $w_{B_0}$ is below $\omega^\beta$. Assume that near $0$
    every translated truncation of $F(b)$ has degree below $\alpha_1$, and
    every convolution term $\rho$ using at least two translated truncations
    satisfies $\rho<\alpha_{\ge\beta}\oplus\lambda_0$.

    If $X_{B'}$ occurs in $F$ and
    $(w_{B'})_{<\beta}\oplus\eta=\lambda_0$ for some ordinal $\eta$, then
    there are a finite set $S$ and polynomials $U_B$ such that
    \[
      \partial_{B'}F=\sum_{B\in S}(\partial_BF)U_B,
      \qquad \partial_{B_0}U_B=0\quad(B\in S).
    \]
    Every $B\in S$ occurs in $F$ and satisfies either
    $(w_B)_{<\beta}=\alpha_{<\beta}$, or
    \[
      0\ne(w_B)_{<\beta}\ne\alpha_{<\beta},\qquad
      \nexists\xi,\ (w_B)_{<\beta}\oplus\xi=\lambda_0,
      \qquad w_{B'}<w_B.
    \]
  -/)
  (proof := /--
  Use strong induction on the number of variables of $F$ with weight strictly
  larger than $w_{B'}$. Put $\Theta=\partial_{B'}F$. If $\Theta=0$ there is
  nothing to prove. Otherwise $\Theta$ is homogeneous of a degree $h$ with
  $h\oplus w_{B'}=\alpha$. Write
  $(w_{B'})_{<\beta}\oplus\eta=\lambda_0$ and set
  $\tau=h_{\ge\beta}\oplus\eta$.

  By \ref{lem:local-jacobian-ideal-membership}, the components in degrees at
  least $\tau$ of sufficiently late translated truncations of $\Theta(b)$ lie in
  the ideal generated by the partial derivatives at heavier variables. By
  the induction hypothesis,
  every such intervening derivative is already generated by the required
  ones.

  The ordinal window needed by the local-to-global step follows from
  \ref{lem:equal-last-terms-hessenberg-decomposition} and
  \ref{lem:unequal-last-terms-hessenberg-decomposition}. In the
  unequal-last-term case, the Hessenberg-sum decomposition first identifies
  the upper Cantor terms, which supplies the required upper-term equality.

  By \ref{lem:eventual-local-ideal-membership-gives-syzygy}, the eventual
  componentwise membership becomes an exact polynomial identity with cofactors
  of the complementary weighted degrees. The coefficient of $\partial_BF$
  has weighted degree strictly below $w_{B_0}$, so it is independent of
  $X_{B_0}$. This gives $\partial_{B_0}U_B=0$ and completes the induction.
  -/)]
theorem exists_finset_pderiv_eq_sum_of_lowDegreePartAlgebraicLE {v' : ι} (hv' : v' ∈ S.F.vars)
    (hdiff : S.LowDegreePartAlgebraicLE v') :
    ∃ (s : Finset ι) (C : ι → MvPolynomial ι K),
      (∀ v ∈ s, S.ContributesToPartialDerivativeAt v' v) ∧
      (∀ v ∈ s, pderiv S.B₀ (C v) = 0) ∧
      pderiv v' S.F = ∑ v ∈ s, pderiv v S.F * C v := by
  classical
  suffices H : ∀ n : ℕ, ∀ v' ∈ S.F.vars,
      (S.F.vars.filter fun v ↦ wt v' < wt v).card = n → S.LowDegreePartAlgebraicLE v' →
      ∃ (s : Finset ι) (C : ι → MvPolynomial ι K),
        (∀ v ∈ s, S.ContributesToPartialDerivativeAt v' v) ∧
        (∀ v ∈ s, pderiv S.B₀ (C v) = 0) ∧
        pderiv v' S.F = ∑ v ∈ s, pderiv v S.F * C v from
    H _ v' hv' rfl hdiff
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  intro v' hv' hn hdiff
  set Θ := pderiv v' S.F with hΘdef
  rcases eq_or_ne Θ 0 with hΘ0 | hΘ0
  · exact ⟨∅, fun _ ↦ 0, fun v hv ↦ absurd hv (Finset.notMem_empty v),
      fun v hv ↦ absurd hv (Finset.notMem_empty v), by rw [hΘ0, Finset.sum_empty]⟩
  obtain ⟨h, hh⟩ := exists_add_wt_eq_of_mem_vars S.hom hv'
  have hhα : h < α := by
    rw [← hh]
    exact lt_add_of_pos_right _ (pos_iff_ne_zero.mpr (hx.ne_zero v'))
  have hΘhom : IsWeightedHomogeneous wt Θ h := by
    rw [hΘdef]
    exact S.pderiv_hom hh
  obtain ⟨lam',
    hlam'⟩ := NatOrdinal.algebraicLE_iff.mp ((S.lowDegreePartAlgebraicLE_iff v').mp hdiff)
  set τ := NatOrdinal.partGE S.β h + lam' with hτdef
  have hτ : NatOrdinal.partGE S.β α + S.lam₀ ≤ τ + wt v' := by
    have heq := S.αGE_add_lam₀_eq hh hlam'
    rw [S.αGE_def, ← hτdef] at heq
    exact heq.le
  have habove : ∀ j ∈ S.F.vars, wt v' < wt j →
      pderiv j S.F ∈
        Ideal.span (Set.range fun v : {v // S.ContributesToPartialDerivativeAt v' v} ↦
          pderiv v.1 S.F) := by
    intro j hj hlt
    by_cases htop : S.LowDegreePartEq j
    · exact Ideal.subset_span
        ⟨⟨j, (S.contributesToPartialDerivativeAt_iff v' j).mpr ⟨hj, Or.inl htop⟩⟩, rfl⟩
    by_cases hL : S.HasProperLowDegreePartNotAlgebraicLE j
    · exact Ideal.subset_span
        ⟨⟨j, (S.contributesToPartialDerivativeAt_iff v' j).mpr ⟨hj, Or.inr ⟨hL, hlt⟩⟩⟩, rfl⟩
    have hdj : S.LowDegreePartAlgebraicLE j := by
      by_contra hnd
      rcases eq_or_ne (S.degLT j) 0 with ht | ht
      · exact hnd ((S.lowDegreePartAlgebraicLE_iff j).mpr (by
          rw [ht]
          exact NatOrdinal.algebraicLE_zero _))
      · exact hL ((S.hasProperLowDegreePartNotAlgebraicLE_iff j).mpr ⟨hj, ht, htop, hnd⟩)
    have hcard : (S.F.vars.filter fun v ↦ wt j < wt v).card < n := by
      rw [← hn]
      refine Finset.card_lt_card
        (Finset.ssubset_iff_subset_ne.mpr ⟨fun v hv ↦ ?_, fun heq ↦ ?_⟩)
      · obtain ⟨hv1, hv2⟩ := Finset.mem_filter.mp hv
        exact Finset.mem_filter.mpr ⟨hv1, hlt.trans hv2⟩
      · have hjmem : j ∈ S.F.vars.filter fun v ↦ wt v' < wt v :=
          Finset.mem_filter.mpr ⟨hj, hlt⟩
        rw [← heq, Finset.mem_filter] at hjmem
        exact lt_irrefl _ hjmem.2
    obtain ⟨s, C, hs, -, heq⟩ := ih _ hcard j hj rfl hdj
    rw [heq]
    refine Ideal.sum_mem _ fun v hv ↦
      Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨⟨v, ?_⟩, rfl⟩)
    obtain ⟨hvF, hvkind⟩ := (S.contributesToPartialDerivativeAt_iff j v).mp (hs v hv)
    exact (S.contributesToPartialDerivativeAt_iff v' v).mpr
      ⟨hvF, hvkind.elim Or.inl fun h' ↦ Or.inr ⟨h'.1, hlt.trans h'.2⟩⟩
  have hlocalAbove : ∀ᶠ γ in 𝓝[<] (0 : G),
      componentsGE wt τ (σ.pol hx α
        (translatedTruncLE γ (aeval σ.lift Θ))) ∈
        Ideal.span (Set.range fun v : {v // S.ContributesToPartialDerivativeAt v' v} ↦
          pderiv v.1 S.F) := by
    filter_upwards [S.truncation_lt, self_mem_nhdsWithin] with γ hrel hγ
    have hmem := σ.componentsGE_pol_translatedTruncLE_aeval_pderiv_mem hx hσ hinj S.hom
      S.vars_lt S.α₁_le S.α₁_le_α hγ hrel S.remainder_lt v' hτ
    rw [← hΘdef] at hmem
    refine Ideal.span_le.mpr ?_ hmem
    rintro _ ⟨j, rfl⟩
    exact habove j.1 j.2.1 j.2.2
  haveI : Finite {v // S.ContributesToPartialDerivativeAt v' v} :=
    S.finite_setOf_contributesToPartialDerivativeAt v'
  have hcd : ∀ v : {v // S.ContributesToPartialDerivativeAt v' v}, ∃ c, c + wt v.1 = α :=
    fun v ↦ exists_add_wt_eq_of_mem_vars S.hom
      ((S.contributesToPartialDerivativeAt_iff v' v).mp v.2).1
  choose cd hcd using hcd
  have hqG : ∀ v : {v // S.ContributesToPartialDerivativeAt v' v},
      IsWeightedHomogeneous wt (pderiv v.1 S.F) (cd v) :=
    fun v ↦ S.pderiv_hom (hcd v)
  let A : {v // S.ContributesToPartialDerivativeAt v' v} → Prop :=
    fun v ↦ NatOrdinal.AlgebraicLE (wt v') (wt v.1)
  have hAiff : ∀ v, A v ↔ NatOrdinal.AlgebraicLE (wt v') (wt v.1) := fun _ ↦ Iff.rfl
  haveI : Finite {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v} :=
    Finite.of_injective (fun v ↦ v.1) Subtype.val_injective
  have hbA : ∀ v : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v},
      ∃ b, b + wt v' = wt v.1.1 := fun v ↦ by
    obtain ⟨c, hc⟩ := NatOrdinal.algebraicLE_iff.mp ((hAiff v.1).mp v.2)
    exact ⟨c, by rw [add_comm]; exact hc⟩
  choose b hb using hbA
  have hbc : ∀ v : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v},
      b v + cd v.1 = h := by
    intro v
    have h1 : b v + cd v.1 + wt v' = h + wt v' := by
      rw [add_right_comm, hb v, add_comm, hcd v.1, hh]
    exact add_right_cancel h1
  have hnotA : ∀ v : {v // S.ContributesToPartialDerivativeAt v' v}, ¬ A v →
      ¬ NatOrdinal.AlgebraicLE (cd v) h := by
    intro v hA hce
    obtain ⟨b', hb'⟩ := NatOrdinal.algebraicLE_iff.mp hce
    refine hA ((hAiff v).mpr (NatOrdinal.algebraicLE_iff.mpr ⟨b', ?_⟩))
    have h1 : cd v + (b' + wt v') = cd v + wt v.1 := by
      rw [← add_assoc, hb', hh, hcd v]
    rw [add_comm]
    exact add_left_cancel h1
  have hlocal : ∀ᶠ γ in 𝓝[<] (0 : G),
      componentsGE wt τ (σ.pol hx α
        (translatedTruncLE γ (aeval σ.lift Θ))) ∈
        Ideal.span (Set.range fun v :
          {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v} ↦ pderiv v.1.1 S.F) := by
    filter_upwards [hlocalAbove, self_mem_nhdsWithin] with γ hmem hγ
    refine componentsGE_mem_span_subtype wt hqG (h := h) hmem ?_ A
      (fun v hA e hτe heh ⟨β', hβ'⟩ ↦ ?_)
    · exact σ.pol_weight_lt_of_degree_lt hx hhα.le
        ((σ.hasLowerTruncationDegree_aeval hσ hΘhom).degree_translatedTruncLE_lt hγ)
    · have hce : NatOrdinal.AlgebraicLE (cd v) e :=
        NatOrdinal.algebraicLE_iff.mpr ⟨β', by rw [add_comm]; exact hβ'⟩
      rw [hτdef] at hτe
      rcases ((S.contributesToPartialDerivativeAt_iff v' v).mp v.2).2 with htop | ⟨hL, -⟩
      · exact S.not_algebraicLE_of_lowDegreePartEq_of_not (hcd v) hlam' htop
          (hnotA v hA) hτe heh hce
      · exact S.not_algebraicLE_of_hasProperLowDegreePartNotAlgebraicLE_of_not
          hx (hcd v) hh hlam' hL (hnotA v hA) hτe heh hce
  have hτh : τ + 1 < h := hτdef ▸ S.τ_add_one_lt hx hh hlam'
  have hwin : ∀ v : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v},
      ∀ ε : NatOrdinal, NatOrdinal.leastTerm (cd v.1) = ω^ ε →
        NatOrdinal.partGE ε h ≤ τ := by
    intro v ε hε
    rw [hτdef]
    obtain ⟨hvF, hvkind⟩ := (S.contributesToPartialDerivativeAt_iff v' v.1).mp v.1.2
    rcases hvkind with htop | ⟨hL, -⟩
    · exact S.partGE_le_τ_of_lowDegreePartEq hvF (hcd v.1) htop hε h
    · have hne := S.partLT_cdeg_ne_zero (hcd v.1)
        ((S.hasProperLowDegreePartNotAlgebraicLE_iff _).mp hL).2.2.1
      rw [NatOrdinal.leastTerm_eq_leastTerm_partLT hne] at hε
      exact S.partGE_le_τ_of_hasProperLowDegreePartNotAlgebraicLE hx (hcd v.1) hh hlam' hL hε
  have hp : ∀ᶠ γ in 𝓝[<] (0 : G), ∃ P : MvPolynomial ι K,
      (∀ d ∈ P.support, Finsupp.weight wt d < α) ∧
      ν (translatedTruncLE γ (aeval σ.lift Θ) - aeval σ.lift P) = ⊥ ∧
      componentsGE wt τ P ∈
        Ideal.span (Set.range fun v :
          {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v} ↦ pderiv v.1.1 S.F) := by
    filter_upwards [hlocal, self_mem_nhdsWithin] with γ hmem hγ
    have hdeg := (σ.hasLowerTruncationDegree_aeval hσ hΘhom).degree_translatedTruncLE_lt hγ
    refine ⟨σ.pol hx α (translatedTruncLE γ (aeval σ.lift Θ)),
      σ.pol_weight_lt hx _ _, ?_, hmem⟩
    exact σ.degree_sub_aeval_pol_eq_bot hx (hdeg.trans (WithBot.coe_lt_coe.mpr hhα))
  have hgen : ∀ β : NatOrdinal.{u}, β < α →
      ∀ z ∈ DirectSum.rangeLof K (ν).Component β,
        ∃ P : MvPolynomial ι K, IsWeightedHomogeneous wt P β ∧ aeval xg P = z :=
    fun β _ ↦ hx.exists_aeval_eq cantorBendixson_gradeZeroScalars β
  have hinj' : ∀ (β : NatOrdinal.{u}) (P : MvPolynomial ι K), β < α →
      IsWeightedHomogeneous wt P β → aeval xg P = 0 → P = 0 := by
    intro β P hβα
    exact ((OrdinalGraded.injectiveAt_iff β).mp (hinj β hβα)) P
  cases nonempty_fintype {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v}
  obtain ⟨C, hChom, hΘeq⟩ :=
    exists_eq_sum_mul_of_eventually_componentsGE_mem_of_windows Ubase hUmono hUopen hUconv
      hUbase xg σ.represents ((σ.hasLowerTruncationDegrees_iff).mp hσ) α hgen hinj'
      (fun v : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v} ↦ pderiv v.1.1 S.F)
      (fun v ↦ cd v.1) b (fun v ↦ hqG v.1) τ h hτh hhα
      (fun v ↦ S.cdeg_ne_zero
        ((S.contributesToPartialDerivativeAt_iff v' v.1.1).mp v.1.2).1 (hcd v.1))
      hbc hwin hΘhom
      (σ.hasLowerTruncationDegree_aeval hσ hΘhom) hp
  have hCB₀ : ∀ v : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v},
      pderiv S.B₀ (C v) = 0 := by
    intro v
    have hbg : b v < wt S.B₀ := by
      have h1 : b v < wt v.1.1 := by
        rw [← hb v]
        exact lt_add_of_pos_right _ (pos_iff_ne_zero.mpr (hx.ne_zero v'))
      exact h1.trans_le (S.max _ ((S.contributesToPartialDerivativeAt_iff v' v.1.1).mp v.1.2).1)
    exact LiftFamily.pderiv_eq_zero_of_degreeLT_le
      ((LiftFamily.degreeLT_iff).mpr
        (fun d hd ↦ (hChom v (b v) (hbc v)) (mem_support_iff.mp hd) ▸ hbg)) le_rfl
  have hindex : Function.Injective
      (fun v : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v} ↦ v.1.1) :=
    fun v w hvw ↦ Subtype.ext (Subtype.ext hvw)
  refine ⟨Finset.univ.image
      (fun v : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v} ↦ v.1.1),
    fun i ↦ if hi : ∃ v :
        {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v}, v.1.1 = i then
      C (Classical.choose hi) else 0, ?_, ?_, ?_⟩
  · intro i hi
    obtain ⟨v, -, rfl⟩ := Finset.mem_image.mp hi
    exact v.1.2
  · intro i hi
    obtain ⟨v, -, rfl⟩ := Finset.mem_image.mp hi
    beta_reduce
    rw [dif_pos (⟨v, rfl⟩ :
      ∃ w : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v}, w.1.1 = v.1.1)]
    exact hCB₀ _
  · rw [hΘeq, Finset.sum_image fun v _ w _ h ↦ hindex h]
    refine Finset.sum_congr rfl fun v _ ↦ ?_
    beta_reduce
    rw [dif_pos (⟨v, rfl⟩ :
      ∃ w : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v}, w.1.1 = v.1.1)]
    have hchoice : Classical.choose
        (⟨v, rfl⟩ : ∃ w : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v},
          w.1.1 = v.1.1) = v := hindex (Classical.choose_spec
      (⟨v, rfl⟩ : ∃ w : {v : {v // S.ContributesToPartialDerivativeAt v' v} // A v},
        w.1.1 = v.1.1))
    rw [hchoice, mul_comm]

end LimitOrdinalRelationAtCutoff

end HahnSeries.Germ

end
