#!/usr/bin/env python3
"""Shared immutable source revision for every generated proof-guide artifact."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
METADATA = ROOT / "blueprint/source-revision.json"
TEX = ROOT / "blueprint/src/revision.tex"
DEFAULT_REPOSITORY = "https://github.com/gaearon/conway-refinement"
REVISION_RE = re.compile(r"[0-9a-f]{40}")


def validate_revision(revision: str) -> str:
    if REVISION_RE.fullmatch(revision) is None:
        raise SystemExit("blueprint: source revision must be a full 40-character Git SHA")
    return revision


def metadata(revision: str, published: bool, repository: str) -> dict[str, object]:
    return {
        "repository": repository.rstrip("/"),
        "revision": validate_revision(revision),
        "published": published,
    }


def read_metadata() -> dict[str, object]:
    if not METADATA.exists():
        raise SystemExit("blueprint: missing blueprint/source-revision.json")
    value = json.loads(METADATA.read_text())
    if set(value) != {"repository", "revision", "published"}:
        raise SystemExit("blueprint: malformed blueprint/source-revision.json")
    if not isinstance(value["repository"], str) or not value["repository"]:
        raise SystemExit("blueprint: source repository must be a nonempty URL")
    validate_revision(str(value["revision"]))
    if not isinstance(value["published"], bool):
        raise SystemExit("blueprint: published must be a Boolean")
    return value


def render_tex(value: dict[str, object]) -> str:
    revision = str(value["revision"])
    repository = str(value["repository"])
    published = bool(value["published"])
    if published:
        provenance = (
            "Generated from AI-written annotations in the Lean source at commit "
            rf"\href{{{repository}/commit/{revision}}}{{\texttt{{{revision[:12]}}}}}."
        )
    else:
        provenance = (
            "Generated from AI-written annotations in the working tree near commit "
            rf"\href{{{repository}/commit/{revision}}}{{\texttt{{{revision[:12]}}}}}."
        )
    return "\n".join(
        [
            "% Generated by scripts/blueprint.sh; do not edit.",
            rf"\renewcommand{{\blueprintrepository}}{{{repository}}}",
            rf"\renewcommand{{\blueprintrevision}}{{{revision}}}",
            rf"\renewcommand{{\blueprintshortrevision}}{{{revision[:12]}}}",
            rf"\renewcommand{{\blueprintprovenance}}{{{provenance}}}",
            "",
        ]
    )


def write_metadata(value: dict[str, object]) -> None:
    METADATA.write_text(json.dumps(value, indent=2) + "\n")
    TEX.write_text(render_tex(value))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--revision")
    parser.add_argument("--repository", default=DEFAULT_REPOSITORY)
    parser.add_argument("--published", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        value = read_metadata()
        if TEX.read_text() != render_tex(value):
            raise SystemExit("blueprint: generated file is stale: blueprint/src/revision.tex")
        print(f"blueprint: source revision {value['revision']}")
        return
    if args.revision is None:
        parser.error("--revision is required unless --check is used")
    write_metadata(metadata(args.revision, args.published, args.repository))


if __name__ == "__main__":
    main()
