/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.Algebra.DirectSum.GermChainRule
public import ConwayRefinement.Algebra.GradedRing.HomogeneousSpan
public import ConwayRefinement.Algebra.MvPolynomial.FinitePartVars

/-!
# The ideal of the partial derivatives carrying the finite part, for germ derivations

Let `F` be a relation of degree `δ` whose finite part is `n ≥ 1`, under evaluation injective in
every degree below `δ`. The variables of `F` whose own degree has finite part `n` generate an ideal

`I = (∂F/∂X_B : X_B carries the finite part)`,

and the claim is that every partial derivative of `F` at a variable of successor degree lies in `I`.

This file carries the inductive step of that claim from the real line to an arbitrary filter. The
argument is unchanged: the chain rule expresses the derivative of `(∂F/∂X_j)(x)` through the
partial derivatives at variables of strictly larger degree, which lie in `I` by hypothesis, so the
derivative germ takes values in the evaluated ideal; ideal membership from the derivative pulls
`(∂F/∂X_j)(x)` into that ideal; and injectivity below `δ` lifts the resulting relation back to a
polynomial identity.

The one input not available from the abstract lowering-derivation interface is the passage from a
derivative germ with values in an ideal to membership of the class itself. That is an integration
statement, proved separately in each setting, so it is taken here as the hypothesis
`HasIdealIntegration`.
-/

universe u v w z q

open Filter GermPolynomial MvPolynomial OrdinalGraded

public noncomputable section

namespace OrdinalGraded

variable {K : Type u} {R : Type v} {T : Type q}
variable [Field K] [CommRing R] [Algebra K R]
variable {l : Filter T}
variable (A : NatOrdinal.{z} → Submodule K R) [GradedAlgebra A]
variable {ι : Type w} {wt : ι → NatOrdinal.{z}} {x : ι → R}

namespace DerivativeRep

variable {A}
variable {Δ : Derivation K R (Germ l R)}
variable {g : ι → T → MvPolynomial ι K}
variable (hx : OrdinalGraded.IsMinimalSystem A wt x)
variable (hg : DerivativeRep (l := l) wt x Δ g)
variable (hΔ : GermPolynomial.IsLoweringDerivation A Δ)
include hx hg hΔ

omit [GradedAlgebra A] hx hg hΔ in
/-- Evaluation carries the ideal of the partial derivatives into the ideal generated by their
values. -/
theorem aeval_mem_span_of_mem_span {δ : NatOrdinal.{z}} {F : MvPolynomial ι K}
    {q : ↥(varsOfFinitePart wt F δ) → R} (hqdef : ∀ t, q t = aeval x (pderiv (t : ι) F))
    {G : MvPolynomial ι K}
    (hG : G ∈ Ideal.span ((fun t ↦ pderiv t F) '' (varsOfFinitePart wt F δ : Set ι))) :
    aeval x G ∈ Ideal.span (Set.range q) := by
  have hmap := Ideal.mem_map_of_mem (aeval x : MvPolynomial ι K →ₐ[K] R).toRingHom hG
  rw [Ideal.map_span, Set.image_image, Set.image_eq_range] at hmap
  simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe] at hmap
  have hq_eq : q = fun t : ↥(varsOfFinitePart wt F δ) ↦ aeval x (pderiv (t : ι) F) :=
    funext hqdef
  rw [hq_eq]
  exact hmap

omit [GradedAlgebra A] hx hΔ in
/-- The chain-rule representative of the derivative takes values in the evaluated ideal. -/
theorem mem_span_of_mkDerivation {δ : NatOrdinal.{z}} {F : MvPolynomial ι K} {j : ι}
    {q : ↥(varsOfFinitePart wt F δ) → R} (hqdef : ∀ t, q t = aeval x (pderiv (t : ι) F))
    (ih : ∀ i ∈ F.vars, 0 < (wt i).constantCoeff → wt j < wt i →
      pderiv i F ∈ Ideal.span ((fun t ↦ pderiv t F) '' (varsOfFinitePart wt F δ : Set ι)))
    {t : T}
    (ht : mkDerivation K (fun i ↦ g i t) (pderiv j F) =
      -mkDerivation K (fun i ↦ pderiv j (g i t)) F) :
    aeval x (mkDerivation K (fun i ↦ g i t) (pderiv j F)) ∈ Ideal.span (Set.range q) := by
  rw [ht, map_neg, mkDerivation_eq_sum (fun i ↦ pderiv j (g i t)) (S := F.vars) fun _ h ↦ h,
    map_sum]
  refine (Ideal.neg_mem_iff _).mpr (Ideal.sum_mem _ fun i hi ↦ ?_)
  rw [map_mul]
  by_cases hz : pderiv j (g i t) = 0
  · rw [hz, map_zero, zero_mul]
    exact Ideal.zero_mem _
  · obtain hlt := hg.wt_lt_of_pderiv_ne_zero hz
    have his : 0 < (wt i).constantCoeff := by
      by_contra hc0
      exact hz (by rw [hg.eq_zero i t (Nat.eq_zero_of_not_pos hc0), map_zero])
    exact Ideal.mul_mem_left _ _
      (aeval_mem_span_of_mem_span hqdef (ih i hi his hlt))

omit [GradedAlgebra A] hg hΔ in
/-- A homogeneous value of the decomposition is the evaluation of a homogeneous polynomial, and is
zero when its degree does not precede the target degree in the algebraic order. -/
theorem exists_polynomial_of_mem (h0 : GradeZeroScalars A) {lamt beta : NatOrdinal.{z}}
    {ut : R} (hu : ∀ b, b + lamt = beta → ut ∈ A b) (hu0 : (¬ ∃ b, b + lamt = beta) → ut = 0) :
    ∃ U : MvPolynomial ι K, (∀ b, b + lamt = beta → IsWeightedHomogeneous wt U b) ∧
      ((¬ ∃ b, b + lamt = beta) → U = 0) ∧ aeval x U = ut := by
  by_cases h : ∃ b, b + lamt = beta
  · obtain ⟨b, hb⟩ := h
    obtain ⟨U, hU, hUu⟩ := hx.exists_aeval_eq h0 b ut (hu b hb)
    refine ⟨U, fun b' hb' ↦ ?_, fun h' ↦ absurd ⟨b, hb⟩ h', hUu⟩
    rwa [add_right_cancel (hb'.trans hb.symm)]
  · exact ⟨0, fun b hb ↦ absurd ⟨b, hb⟩ h, fun _ ↦ rfl, by rw [map_zero, hu0 h]⟩

open Classical in
/-- **The inductive step.** If `∂F/∂X_i` lies in the ideal generated by the partial derivatives at
the variables carrying the finite part, for every variable `i` of `F` of successor degree with
`wt j < wt i`, then so does `∂F/∂X_j`. -/
theorem pderiv_mem_span_varsOfFinitePart_of_forall_lt
    (h0 : GradeZeroScalars A)
    (hint : ∀ {ι' : Type w} [Finite ι'] {q : ι' → R} {c : ι' → NatOrdinal.{z}},
      (∀ j, q j ∈ A (c j)) → (∀ j, (c j).constantCoeff = 0) →
      ∀ {b : NatOrdinal.{z}}, 0 < b.constantCoeff → ∀ {y : R}, y ∈ A b →
        ∀ {f : T → R}, (∀ t, f t ∈ Ideal.span (Set.range q)) →
          Δ y = (f : Germ l R) → y ∈ Ideal.span (Set.range q))
    {δ : NatOrdinal.{z}} (hinj : ∀ β < δ, InjectiveAt K wt x β) (hδ : 0 < δ.constantCoeff)
    {F : MvPolynomial ι K} (hF : IsWeightedHomogeneous wt F δ) (hF0 : aeval x F = 0)
    {j : ι} (hj : j ∈ F.vars)
    (ih : ∀ i ∈ F.vars, 0 < (wt i).constantCoeff → wt j < wt i →
      pderiv i F ∈ Ideal.span ((fun t ↦ pderiv t F) '' (varsOfFinitePart wt F δ : Set ι))) :
    pderiv j F ∈ Ideal.span ((fun t ↦ pderiv t F) '' (varsOfFinitePart wt F δ : Set ι)) := by
  classical
  by_cases htop : (wt j).constantCoeff = δ.constantCoeff
  · exact Ideal.subset_span ⟨j, mem_varsOfFinitePart_iff.mpr ⟨hj, htop⟩, rfl⟩
  -- the evaluated partial derivatives at the variables carrying the finite part
  obtain ⟨lam, hlam⟩ : ∃ lam : ↥(varsOfFinitePart wt F δ) → NatOrdinal.{z},
      ∀ t, lam t + wt t = δ :=
    ⟨_, fun t ↦ (exists_add_wt_eq_of_mem_vars hF (mem_varsOfFinitePart_iff.mp t.2).1).choose_spec⟩
  obtain ⟨q, hqdef⟩ : ∃ q : ↥(varsOfFinitePart wt F δ) → R,
      ∀ t, q t = aeval x (pderiv (t : ι) F) := ⟨_, fun _ ↦ rfl⟩
  have hq : ∀ t, q t ∈ A (lam t) := fun t ↦ by
    rw [hqdef]
    exact aeval_mem_of_forall_mem hx.mem (isWeightedHomogeneous_pderiv_of_add_wt_eq hF (hlam t))
  have hc : ∀ t, (lam t).constantCoeff = 0 := fun t ↦
    NatOrdinal.constantCoeff_eq_zero_of_add_eq (mem_varsOfFinitePart_iff.mp t.2).2 (hlam t)
  -- the degree of `∂F/∂X_j`: a successor below `δ`
  obtain ⟨β, hβ⟩ := exists_add_wt_eq_of_mem_vars hF hj
  have hΘ : IsWeightedHomogeneous wt (pderiv j F) β := isWeightedHomogeneous_pderiv wt hF j hβ
  have hβpos : 0 < β.constantCoeff := by
    have h1 := congrArg NatOrdinal.constantCoeff hβ
    rw [NatOrdinal.constantCoeff_add] at h1
    obtain h2 := constantCoeff_wt_le_of_mem_vars hF hj
    omega
  have hβlt : β < δ := by
    rw [← hβ]
    exact lt_add_of_pos_right β (pos_iff_ne_zero.mpr (hx.ne_zero j))
  have hΘmem : aeval x (pderiv j F) ∈ A β := aeval_mem_of_forall_mem hx.mem hΘ
  -- the chain rule holds on a set of the filter; cut the representative down to it
  obtain ⟨s, hs, hsdef⟩ : ∃ s : Set T, s ∈ l ∧ ∀ t ∈ s,
      mkDerivation K (fun i ↦ g i t) (pderiv j F) =
        -mkDerivation K (fun i ↦ pderiv j (g i t)) F :=
    ⟨_, hg.eventually_mkDerivation_pderiv_eq hΔ hinj hδ hF hF0 j, fun _ h ↦ h⟩
  obtain ⟨f, hfmem, hfeq⟩ : ∃ f : T → R, (∀ t, f t ∈ Ideal.span (Set.range q)) ∧
      ∀ t ∈ s, f t = aeval x (mkDerivation K (fun i ↦ g i t) (pderiv j F)) := by
    refine ⟨fun t ↦ if ht : t ∈ s then
      aeval x (mkDerivation K (fun i ↦ g i t) (pderiv j F)) else 0, fun t ↦ ?_,
      fun t ht ↦ dif_pos ht⟩
    beta_reduce
    by_cases ht : t ∈ s
    · rw [dif_pos ht]
      exact mem_span_of_mkDerivation hg hqdef ih (hsdef t ht)
    · rw [dif_neg ht]
      exact Ideal.zero_mem _
  have hΔf : Δ (aeval x (pderiv j F)) = (f : Germ l R) := by
    rw [hg.map_aeval hΔ]
    refine Germ.coe_eq.mpr ?_
    filter_upwards [hs] with t ht
    exact (hfeq t ht).symm
  -- ideal membership from the derivative, then decompose homogeneously
  obtain hmem := hint (ι' := ↥(varsOfFinitePart wt F δ)) (q := q) (c := lam) hq hc
    (b := β) hβpos (y := aeval x (pderiv j F)) hΘmem (f := f) hfmem hΔf
  obtain ⟨u, hu, hu0, hsum⟩ := exists_eq_sum_mul_of_mem_span (𝒜 := A) hq hΘmem hmem
  obtain ⟨U, hU, hU0, hUu⟩ : ∃ U : ↥(varsOfFinitePart wt F δ) → MvPolynomial ι K,
      (∀ t β', β' + lam t = β → IsWeightedHomogeneous wt (U t) β') ∧
      (∀ t, (¬ ∃ β', β' + lam t = β) → U t = 0) ∧ ∀ t, aeval x (U t) = u t := by
    choose U hU hU0 hUu using fun t ↦
      exists_polynomial_of_mem hx h0 (hu t) (hu0 t)
    exact ⟨U, hU, hU0, hUu⟩
  -- the difference is a relation of degree `β < δ`, hence zero
  have hsum' : IsWeightedHomogeneous wt
      (∑ t : ↥(varsOfFinitePart wt F δ), pderiv (t : ι) F * U t) β := by
    refine IsWeightedHomogeneous.sum _ _ _ fun t _ ↦ ?_
    by_cases h : ∃ β', β' + lam t = β
    · obtain ⟨β', hβ'⟩ := h
      obtain hmul := (isWeightedHomogeneous_pderiv_of_add_wt_eq hF (hlam t)).mul (hU t β' hβ')
      rwa [add_comm, hβ'] at hmul
    · rw [hU0 t h, mul_zero]
      exact isWeightedHomogeneous_zero K wt β
  have hG : IsWeightedHomogeneous wt
      (pderiv j F - ∑ t : ↥(varsOfFinitePart wt F δ), pderiv (t : ι) F * U t) β :=
    (mem_weightedHomogeneousSubmodule K wt β _).mp
      (sub_mem ((mem_weightedHomogeneousSubmodule K wt β _).mpr hΘ)
        ((mem_weightedHomogeneousSubmodule K wt β _).mpr hsum'))
  have hG0 :
      aeval x (pderiv j F - ∑ t : ↥(varsOfFinitePart wt F δ), pderiv (t : ι) F * U t) = 0 := by
    rw [map_sub, map_sum, hsum, sub_eq_zero]
    exact Finset.sum_congr rfl fun t _ ↦ by rw [map_mul, hUu, hqdef]
  obtain hzero := (injectiveAt_iff _).mp (hinj β hβlt) _ hG hG0
  rw [sub_eq_zero] at hzero
  rw [hzero]
  exact Ideal.sum_mem _ fun t _ ↦ Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨t, t.2, rfl⟩)

open Classical in
/-- Under evaluation injective below `δ`, every partial derivative of a relation at a variable of
successor degree lies in the ideal generated by the partial derivatives at the variables carrying
the finite part.

The induction is downward through the variables of successor degree: a variable with none above it
is handled by the step directly, and otherwise the variables above it are strictly fewer. -/
theorem pderiv_mem_span_varsOfFinitePart
    (h0 : GradeZeroScalars A)
    (hint : ∀ {ι' : Type w} [Finite ι'] {q : ι' → R} {c : ι' → NatOrdinal.{z}},
      (∀ j, q j ∈ A (c j)) → (∀ j, (c j).constantCoeff = 0) →
      ∀ {b : NatOrdinal.{z}}, 0 < b.constantCoeff → ∀ {y : R}, y ∈ A b →
        ∀ {f : T → R}, (∀ t, f t ∈ Ideal.span (Set.range q)) →
          Δ y = (f : Germ l R) → y ∈ Ideal.span (Set.range q))
    {δ : NatOrdinal.{z}} (hinj : ∀ β < δ, InjectiveAt K wt x β) (hδ : 0 < δ.constantCoeff)
    {F : MvPolynomial ι K} (hF : IsWeightedHomogeneous wt F δ) (hF0 : aeval x F = 0)
    {j : ι} (hj : j ∈ F.vars) (hjs : 0 < (wt j).constantCoeff) :
    pderiv j F ∈ Ideal.span ((fun t ↦ pderiv t F) '' (varsOfFinitePart wt F δ : Set ι)) := by
  classical
  set S : Finset ι := F.vars.filter fun i ↦ 0 < (wt i).constantCoeff with hSdef
  suffices h : ∀ n : ℕ, ∀ j ∈ S, (S.filter fun i ↦ wt j < wt i).card ≤ n →
      pderiv j F ∈ Ideal.span ((fun t ↦ pderiv t F) '' (varsOfFinitePart wt F δ : Set ι)) from
    h _ j (Finset.mem_filter.mpr ⟨hj, hjs⟩) le_rfl
  intro n
  induction n with
  | zero =>
    intro j hj hcard
    rw [Nat.le_zero, Finset.card_eq_zero, Finset.filter_eq_empty_iff] at hcard
    refine pderiv_mem_span_varsOfFinitePart_of_forall_lt hx hg hΔ h0 hint hinj hδ hF hF0
      (Finset.mem_filter.mp hj).1 fun i hi his hlt ↦ ?_
    exact absurd hlt (hcard (Finset.mem_filter.mpr ⟨hi, his⟩))
  | succ n ihn =>
    intro j hj hcard
    refine pderiv_mem_span_varsOfFinitePart_of_forall_lt hx hg hΔ h0 hint hinj hδ hF hF0
      (Finset.mem_filter.mp hj).1 fun i hi his hlt ↦ ?_
    refine ihn i (Finset.mem_filter.mpr ⟨hi, his⟩) ?_
    have hsub : (S.filter fun t ↦ wt i < wt t) ⊂ S.filter fun t ↦ wt j < wt t := by
      rw [Finset.ssubset_def]
      refine ⟨fun t ht ↦ ?_, fun hcon ↦ ?_⟩
      · rw [Finset.mem_filter] at ht ⊢
        exact ⟨ht.1, hlt.trans ht.2⟩
      · have hmem := hcon (Finset.mem_filter.mpr ⟨Finset.mem_filter.mpr ⟨hi, his⟩, hlt⟩)
        exact lt_irrefl _ (Finset.mem_filter.mp hmem).2
    have hcards := Finset.card_lt_card hsub
    omega

open Classical in
/-- **The relation lies in the ideal of its own partial derivatives.** In characteristic zero,
Euler's identity writes the relation as a combination of the partial derivatives at its variables,
each of which lies in the ideal, and the finite part of the degree is an invertible scalar. -/
theorem mem_span_varsOfFinitePart [CharZero K]
    (h0 : GradeZeroScalars A)
    (hint : ∀ {ι' : Type w} [Finite ι'] {q : ι' → R} {c : ι' → NatOrdinal.{z}},
      (∀ j, q j ∈ A (c j)) → (∀ j, (c j).constantCoeff = 0) →
      ∀ {b : NatOrdinal.{z}}, 0 < b.constantCoeff → ∀ {y : R}, y ∈ A b →
        ∀ {f : T → R}, (∀ t, f t ∈ Ideal.span (Set.range q)) →
          Δ y = (f : Germ l R) → y ∈ Ideal.span (Set.range q))
    {δ : NatOrdinal.{z}} (hinj : ∀ β < δ, InjectiveAt K wt x β) (hδ : 0 < δ.constantCoeff)
    {F : MvPolynomial ι K} (hF : IsWeightedHomogeneous wt F δ) (hF0 : aeval x F = 0) :
    F ∈ Ideal.span ((fun t ↦ pderiv t F) '' (varsOfFinitePart wt F δ : Set ι)) := by
  classical
  -- naming the ideal keeps the final rewrite of `F` from reaching inside it
  set I : Ideal (MvPolynomial ι K) :=
    Ideal.span ((fun t ↦ pderiv t F) '' (varsOfFinitePart wt F δ : Set ι)) with hIdef
  have heuler := hF.sum_constantCoeff_X_mul_pderiv wt (S := F.vars) fun _ h ↦ h
  have hk : δ.constantCoeff • F ∈ I := by
    rw [← heuler]
    refine Ideal.sum_mem _ fun i hi ↦ ?_
    by_cases hpos : 0 < (wt i).constantCoeff
    · exact nsmul_mem (Ideal.mul_mem_left _ _
        (pderiv_mem_span_varsOfFinitePart hx hg hΔ h0 hint hinj hδ hF hF0 hi hpos)) _
    · rw [Nat.eq_zero_of_not_pos hpos, zero_smul]
      exact zero_mem _
  have hk0 : (δ.constantCoeff : K) ≠ 0 := Nat.cast_ne_zero.mpr hδ.ne'
  have hsmul : F = (δ.constantCoeff : K)⁻¹ • (δ.constantCoeff • F) := by
    rw [← Nat.cast_smul_eq_nsmul K, smul_smul, inv_mul_cancel₀ hk0, one_smul]
  rw [hsmul]
  exact I.smul_of_tower_mem _ hk

end DerivativeRep

end OrdinalGraded

end
