/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.Algebra.DirectSum.GermFinitePartIdeal
public import ConwayRefinement.Algebra.GradedRing.FinitePartSubstitution
public import ConwayRefinement.Algebra.DirectSum.GermSyzygy
public import ConwayRefinement.Algebra.MvPolynomial.Syzygy

/-!
# The successor step over an arbitrary filter

Evaluation at a minimal system of homogeneous generators is injective in a degree whose finite part
is at least one, given that it is injective in every smaller degree.

The argument is by contradiction. A nonzero relation of that degree lies in the ideal generated by
its partial derivatives at the variables carrying the finite part; choosing a minimal generating
subset of those derivatives and writing the relation against it produces an evaluated syzygy, which
the syzygy induction places in the span of the derivation-annihilated syzygies. Every entry of that
syzygy then evaluates into the square of the ideal of positive degree, and so does the linear part
of the corresponding cofactor — contradicting the independence of the generators modulo that square.

The two inputs not supplied by the abstract interface are the integration statements: ideal
membership from a derivative germ, and prescribed values on a set carrying a derivative
representative. Both are proved by their own construction in each setting.
-/

universe u v w z q

open Filter GermPolynomial MvPolynomial OrdinalGraded DirectSum

public noncomputable section

namespace OrdinalGraded

variable {K : Type u} {R : Type v} {T : Type q}
variable [Field K] [CommRing R] [Algebra K R]
variable {l : Filter T}
variable {A : NatOrdinal.{z} → Submodule K R} [GradedAlgebra A]
variable {ι : Type w} {wt : ι → NatOrdinal.{z}} {x : ι → R}
variable {Δ : Derivation K R (Germ l R)}
variable (hx : OrdinalGraded.IsMinimalSystem A wt x)
variable (hΔ : GermPolynomial.IsLoweringDerivation A Δ)
include hx hΔ

open Classical in
/-- **The successor step.** Evaluation is injective in a degree of positive finite part when it is
injective in every smaller degree. -/
theorem injectiveAt_of_forall_lt [CharZero K] (hgz : GradeZeroScalars A)
    (hint : ∀ {ι' : Type w} [Finite ι'] {q : ι' → R} {c : ι' → NatOrdinal.{z}},
      (∀ j, q j ∈ A (c j)) → (∀ j, (c j).constantCoeff = 0) →
      ∀ {b : NatOrdinal.{z}}, 0 < b.constantCoeff → ∀ {y : R}, y ∈ A b →
        ∀ {f : T → R}, (∀ t, f t ∈ Ideal.span (Set.range q)) →
          Δ y = (f : Germ l R) → y ∈ Ideal.span (Set.range q))
    (hsyzint : ∀ {B' : Type w} [Fintype B'] (lam' : B' → NatOrdinal.{z}),
      HasSyzygyIntegration A Δ lam' (T := T))
    {δ : NatOrdinal.{z}} (hδ : 0 < δ.constantCoeff)
    (hinj : ∀ β < δ, InjectiveAt K wt x β) : InjectiveAt K wt x δ := by
  classical
  rw [injectiveAt_iff]
  intro F hF hF0
  obtain ⟨grep, hg⟩ := OrdinalGraded.IsMinimalSystem.exists_derivativeRep hx hΔ hgz
  have hδ0 : δ ≠ 0 := by
    rintro rfl
    rw [NatOrdinal.constantCoeff_zero] at hδ
    exact lt_irrefl _ hδ
  obtain ⟨T, hT⟩ : ∃ T : Finset ι, T = varsOfFinitePart wt F δ := ⟨_, rfl⟩
  obtain ⟨c, hc⟩ : ∃ c : ι → MvPolynomial ι K, ∀ t, c t = pderiv t F := ⟨_, fun _ ↦ rfl⟩
  have hcfun : (fun t ↦ pderiv t F) = c := funext fun t ↦ (hc t).symm
  have hFI : F ∈ Ideal.span (c '' (T : Set ι)) := by
    rw [hT, ← hcfun]
    exact DerivativeRep.mem_span_varsOfFinitePart hx hg hΔ hgz hint hinj hδ hF hF0
  -- a minimal generating subset `B ⊆ T`
  obtain ⟨B, hBmem, hBmin⟩ := Finset.exists_min_image
    (T.powerset.filter fun S : Finset ι ↦
      Ideal.span (c '' (S : Set ι)) = Ideal.span (c '' (T : Set ι)))
    Finset.card ⟨T, Finset.mem_filter.mpr ⟨Finset.mem_powerset_self T, rfl⟩⟩
  rw [Finset.mem_filter, Finset.mem_powerset] at hBmem
  obtain ⟨hBT, hBspan⟩ := hBmem
  rcases B.eq_empty_or_nonempty with hBe | hBne
  · -- no generators: `F ∈ (0)`
    rw [hBe, Finset.coe_empty, Set.image_empty, Ideal.span_empty] at hBspan
    rw [← hBspan] at hFI
    exact (Ideal.mem_bot).mp hFI
  exfalso
  -- the variables of finite part `n` and the partial derivatives at them
  have hmemT : ∀ t ∈ T, t ∈ F.vars ∧ (wt t).constantCoeff = δ.constantCoeff := fun t ht ↦
    mem_varsOfFinitePart_iff.mp (hT ▸ ht)
  have hlam : ∀ t ∈ T, ∃ β, β + wt t = δ := fun t ht ↦
    exists_add_wt_eq_of_mem_vars hF (hmemT t ht).1
  choose! lam hlam using hlam
  have hlamc : ∀ t ∈ T, (lam t).constantCoeff = 0 := fun t ht ↦
    NatOrdinal.constantCoeff_eq_zero_of_add_eq (hmemT t ht).2 (hlam t ht)
  have hchom : ∀ t ∈ T, IsWeightedHomogeneous wt (c t) (lam t) := fun t ht ↦ by
    rw [hc]
    exact isWeightedHomogeneous_pderiv_of_add_wt_eq hF (hlam t ht)
  have hcvars : ∀ t ∈ T, ∀ i ∈ (c t).vars, (wt i).constantCoeff = 0 := fun t ht i hi ↦
    constantCoeff_wt_eq_zero_of_mem_vars (hchom t ht) (hlamc t ht) hi
  have hlamlt : ∀ t ∈ T, lam t < δ := fun t ht ↦ by
    rw [← hlam t ht]
    exact lt_add_of_pos_right _ (pos_iff_ne_zero.mpr (hx.ne_zero t))
  -- minimality: no `c_b` lies in the ideal of the others
  have hBmin' : ∀ b ∈ B, c b ∉ Ideal.span (c '' ((B.erase b : Finset ι) : Set ι)) := by
    intro b hb hmem
    have hspan' : Ideal.span (c '' ((B.erase b : Finset ι) : Set ι)) =
        Ideal.span (c '' (T : Set ι)) := by
      refine le_antisymm ?_ ?_
      · rw [← hBspan]
        exact Ideal.span_mono (Set.image_mono (Finset.coe_subset.mpr (Finset.erase_subset b B)))
      · rw [← hBspan, Ideal.span_le]
        rintro _ ⟨t, ht, rfl⟩
        by_cases htb : t = b
        · subst htb
          exact hmem
        · exact Ideal.subset_span ⟨t, Finset.mem_erase.mpr ⟨htb, ht⟩, rfl⟩
    have := hBmin (B.erase b) (Finset.mem_filter.mpr
      ⟨Finset.mem_powerset.mpr ((Finset.erase_subset b B).trans hBT), hspan'⟩)
    rw [Finset.card_erase_of_mem hb] at this
    have hpos : 0 < B.card := Finset.card_pos.mpr hBne
    omega
  -- `F = ∑_t c_t (X_t + V_t)`
  obtain ⟨V, hV, hFV⟩ := exists_eq_sum_pderiv_mul_X_add_of_mem_span hδ hF
    (DerivativeRep.mem_span_varsOfFinitePart hx hg hΔ hgz hint hinj hδ hF hF0)
  rw [← hT] at hV hFV
  simp only [← hc] at hFV
  -- homogeneous coefficients `c_t = ∑_b c_b a_{tb}`
  have hct : ∀ t ∈ T, c t ∈ Ideal.span (Set.range fun b : ↥B ↦ c b) := fun t ht ↦ by
    have h1 : c t ∈ Ideal.span (c '' (B : Set ι)) := by
      rw [hBspan]
      exact Ideal.subset_span ⟨t, ht, rfl⟩
    refine Ideal.span_mono ?_ h1
    rintro _ ⟨t', ht', rfl⟩
    exact ⟨⟨t', ht'⟩, rfl⟩
  have hdec : ∀ t ∈ T, ∃ a : ↥B → MvPolynomial ι K,
      (∀ b : ↥B, ∀ β, β + lam b = lam t → IsWeightedHomogeneous wt (a b) β) ∧
      (∀ b : ↥B, (¬ ∃ β, β + lam b = lam t) → a b = 0) ∧ c t = ∑ b : ↥B, c b * a b := by
    intro t ht
    letI := weightedGradedAlgebra K wt
    obtain ⟨a, ha, ha0, hsum⟩ := exists_eq_sum_mul_of_mem_span
      (𝒜 := weightedHomogeneousSubmodule K wt) (q := fun b : ↥B ↦ c b) (c := fun b : ↥B ↦ lam b)
      (fun b ↦ (mem_weightedHomogeneousSubmodule _ _ _ _).mpr (hchom b (hBT b.2)))
      ((mem_weightedHomogeneousSubmodule _ _ _ _).mpr (hchom t ht)) (hct t ht)
    exact ⟨a, fun b β hβ ↦ (mem_weightedHomogeneousSubmodule _ _ _ _).mp (ha b β hβ), ha0, hsum⟩
  choose! a ha ha0 hsum using hdec
  -- Kronecker coefficients for `t ∈ B`
  obtain ⟨a', ha'⟩ : ∃ a' : ι → ↥B → MvPolynomial ι K,
      ∀ t b, a' t b = if t ∈ B then (if (b : ι) = t then 1 else 0) else a t b :=
    ⟨_, fun _ _ ↦ rfl⟩
  have ha'hom : ∀ t ∈ T, ∀ b : ↥B, ∀ β, β + lam b = lam t →
      IsWeightedHomogeneous wt (a' t b) β := by
    intro t ht b β hβ
    rw [ha']
    split_ifs with htB hbt
    · have h0 : β = 0 := by
        rw [hbt] at hβ
        exact add_right_cancel (hβ.trans (zero_add _).symm)
      rw [h0]
      exact isWeightedHomogeneous_one K wt
    · exact isWeightedHomogeneous_zero K wt β
    · exact ha t ht b β hβ
  have ha'0 : ∀ t ∈ T, ∀ b : ↥B, (¬ ∃ β, β + lam b = lam t) → a' t b = 0 := by
    intro t ht b hn
    rw [ha']
    split_ifs with htB hbt
    · exact absurd ⟨0, by rw [hbt, zero_add]⟩ hn
    · rfl
    · exact ha0 t ht b hn
  have hsum' : ∀ t ∈ T, c t = ∑ b : ↥B, c b * a' t b := by
    intro t ht
    by_cases htB : t ∈ B
    · rw [Finset.sum_eq_single ⟨t, htB⟩]
      · rw [ha', if_pos htB, if_pos rfl, mul_one]
      · intro b _ hb
        rw [ha', if_pos htB, if_neg fun h ↦ hb (Subtype.ext h), mul_zero]
      · intro h
        exact absurd (Finset.mem_univ _) h
    · rw [hsum t ht]
      exact Finset.sum_congr rfl fun b _ ↦ by rw [ha', if_neg htB]
  -- `F = ∑_b c_b W_b`
  obtain ⟨W, hW⟩ : ∃ W : ↥B → MvPolynomial ι K, ∀ b, W b = ∑ t ∈ T, a' t b * (X t + V t) :=
    ⟨_, fun _ ↦ rfl⟩
  have hFW : F = ∑ b : ↥B, c b * W b := by
    conv_lhs => rw [hFV]
    simp only [hW, Finset.mul_sum]
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun t ht ↦ ?_
    rw [hsum' t ht, Finset.sum_mul]
    exact Finset.sum_congr rfl fun b _ ↦ by ring
  -- the evaluated syzygy, homogeneous of degree `δ`
  obtain ⟨u, hu'⟩ : ∃ u : ↥B → R, ∀ b, u b = aeval x (W b) := ⟨_, fun _ ↦ rfl⟩
  have hsyz : ∑ b : ↥B, aeval x (c b) * u b = 0 := by
    simp only [hu']
    rw [← hF0]
    conv_rhs => rw [hFW]
    rw [map_sum]
    exact Finset.sum_congr rfl fun b _ ↦ (map_mul _ _ _).symm
  have hWhom : ∀ b : ↥B, IsWeightedHomogeneous wt (W b) (wt b) := by
    intro b
    rw [hW]
    refine IsWeightedHomogeneous.sum _ _ _ fun t ht ↦ ?_
    by_cases h : ∃ β, β + lam b = lam t
    · obtain ⟨β, hβ⟩ := h
      have hXV : IsWeightedHomogeneous wt (X t + V t) (wt t) :=
        (isWeightedHomogeneous_X K wt t).add (hV t ht).1
      have hdeg : β + wt t = wt b := by
        apply add_right_cancel (b := lam b)
        rw [add_right_comm, hβ, hlam t ht, add_comm, hlam b (hBT b.2)]
      rw [← hdeg]
      exact (ha'hom t ht b β hβ).mul hXV
    · rw [ha'0 t ht b h, zero_mul]
      exact isWeightedHomogeneous_zero K wt _
  have hu : IsHomogeneousTuple A (fun b : ↥B ↦ lam b) u δ := by
    rw [isHomogeneousTuple_iff]
    intro b
    have hwl : wt b + lam b = δ := by rw [add_comm]; exact hlam b (hBT b.2)
    refine ⟨fun β hβ ↦ ?_, fun h ↦ absurd ⟨wt b, hwl⟩ h⟩
    have hβ' : β = wt b := add_right_cancel (hβ.trans hwl.symm)
    rw [hβ', hu']
    exact aeval_mem_of_forall_mem hx.mem (hWhom b)
  -- the variables of the `c_t`, all with degree `0` or a limit ordinal, and the polynomial syzygies
  -- of `(c_b)`
  set Λ : Set ι := ↑(T.biUnion fun t ↦ (c t).vars) with hΛdef
  have hΛ : ∀ i ∈ Λ, (wt i).constantCoeff = 0 := by
    intro i hi
    obtain ⟨t, ht, hit⟩ := Finset.mem_biUnion.mp (Finset.mem_coe.mp hi)
    exact hcvars t ht i hit
  have hcΛ : ∀ b : ↥B, c b ∈ supported K Λ := fun b ↦ mem_supported.mpr fun i hi ↦
    Finset.mem_coe.mpr (Finset.mem_biUnion.mpr ⟨b, hBT b.2, hi⟩)
  obtain ⟨L, hL, hLspan⟩ := exists_finset_syzygy_span_supported Λ (fun b : ↥B ↦ c b) hcΛ
  -- evaluations of the generators and their homogeneous components
  obtain ⟨ev, hev⟩ : ∃ ev : (↥B → MvPolynomial ι K) → (↥B → R),
      ∀ σ b, ev σ b = aeval x (σ b) := ⟨fun σ b ↦ aeval x (σ b), fun _ _ ↦ rfl⟩
  obtain ⟨comp, hcomp⟩ : ∃ comp : (↥B → R) → NatOrdinal → (↥B → R),
      ∀ w e b, comp w e b = if h : ∃ β, β + lam b = e then
        (decompose (A) (w b) (Classical.choose h) : R) else 0 :=
    ⟨fun w e b ↦ if h : ∃ β, β + lam b = e then
        (decompose (A) (w b) (Classical.choose h) : R) else 0,
      fun _ _ _ ↦ rfl⟩
  have hcomp_hom : ∀ w e, IsHomogeneousTuple A (fun b : ↥B ↦ lam b) (comp w e) e := by
    intro w e
    rw [isHomogeneousTuple_iff]
    intro b
    refine ⟨fun β hβ ↦ ?_, fun h ↦ ?_⟩
    · have h : ∃ β, β + lam b = e := ⟨β, hβ⟩
      have hch : ∀ h' : ∃ β, β + lam b = e, Classical.choose h' = β := fun h' ↦
        add_right_cancel ((Classical.choose_spec h').trans hβ.symm)
      rw [hcomp, dif_pos h, hch]
      exact (decompose (A) (w b) β).2
    · rw [hcomp, dif_neg h]
  have hcomp_syz : ∀ σ ∈ L, ∀ e, ∑ b : ↥B, aeval x (c b) * comp (ev σ) e b = 0 := by
    intro σ hσ e
    have h1 : ∀ b : ↥B, aeval x (c b) * comp (ev σ) e b =
        GradedRing.proj (A) e (aeval x (c b) * aeval x (σ b)) := by
      intro b
      rw [GradedRing.proj_apply, coe_decompose_mul_of_left_mem (𝒜 := A)
        (aeval_mem_of_forall_mem hx.mem (hchom b (hBT b.2))) (aeval x (σ b)) e, hcomp, hev]
      by_cases h : ∃ β, β + lam b = e
      · rw [dif_pos h, dif_pos h]
      · rw [dif_neg h, dif_neg h, mul_zero]
    have h2 : ∑ b : ↥B, aeval x (c b) * aeval x (σ b) = 0 := by
      have := congrArg (aeval x) (hL σ hσ).2
      rw [map_sum, map_zero] at this
      simpa only [map_mul] using this
    rw [Finset.sum_congr rfl fun b _ ↦ h1 b, ← map_sum, h2, map_zero]
  have hcomp_lim : ∀ σ ∈ L, ∀ e (b : ↥B) β, comp (ev σ) e b ∈ A β →
      comp (ev σ) e b ≠ 0 → β.constantCoeff = 0 := by
    intro σ hσ e b β hmem hne
    by_contra hβ
    apply hne
    by_cases h : ∃ β', β' + lam b = e
    · rw [hcomp, hev, dif_pos h] at hmem hne ⊢
      -- a nonzero element of `P_β` and of `P_{β'}` forces `β = β'`
      have hβ' : β = Classical.choose h := by
        by_contra hne'
        have h0 := decompose_of_mem_ne (A) hmem hne'
        rw [decompose_of_mem_same (A)
          (decompose (A) (aeval x (σ b)) (Classical.choose h)).2] at h0
        exact hne h0
      rw [hβ'] at hβ
      rw [decompose_aeval hx.mem, weightedHomogeneousComponent_eq_zero_of_forall_vars
        (fun i hi ↦ hΛ i (mem_supported.mp ((hL σ hσ).1 b) hi)) hβ, map_zero]
    · rw [hcomp, dif_neg h] at hne
      exact absurd rfl hne
  -- the degrees occurring, and the sum of the components
  set E : Finset NatOrdinal := L.biUnion fun σ ↦ Finset.univ.biUnion fun b : ↥B ↦
    (decompose (A) (ev σ b)).support.image (· + lam b) with hEdef
  have hev_sum : ∀ σ ∈ L, ev σ = ∑ e ∈ E, comp (ev σ) e := by
    intro σ hσ
    funext b
    rw [Finset.sum_apply]
    have himg : (decompose (A) (ev σ b)).support.image (· + lam b) ⊆ E := by
      intro e he
      rw [hEdef]
      exact Finset.mem_biUnion.mpr ⟨σ, hσ, Finset.mem_biUnion.mpr ⟨b, Finset.mem_univ b, he⟩⟩
    rw [← Finset.sum_subset himg, Finset.sum_image fun β₁ _ β₂ _ h ↦ add_right_cancel h]
    · conv_lhs => rw [← sum_support_decompose (A) (ev σ b)]
      refine Finset.sum_congr rfl fun β _ ↦ ?_
      have h : ∃ β', β' + lam b = β + lam b := ⟨β, rfl⟩
      have hch : ∀ h' : ∃ β', β' + lam b = β + lam b, Classical.choose h' = β := fun h' ↦
        add_right_cancel (Classical.choose_spec h')
      rw [hcomp, dif_pos h, hch]
    · intro e _ he
      rw [hcomp]
      split_ifs with h
      · have hnot : Classical.choose h ∉ (decompose (A) (ev σ b)).support :=
          fun hmem ↦ he (Finset.mem_image.mpr ⟨_, hmem, Classical.choose_spec h⟩)
        rw [DFinsupp.notMem_support_iff.mp hnot]
        rfl
      · rfl
  -- the finite set `𝒯` of homogeneous ∂-annihilated syzygies
  set TP : Finset (↥B → R) := (L ×ˢ E).image fun p ↦ comp (ev p.1) p.2 with hTPdef
  set eT : (↥B → R) → NatOrdinal := fun w ↦
    if h : ∃ e, IsHomogeneousTuple A (fun b : ↥B ↦ lam b) w e then Classical.choose h else 0
    with heTdef
  have hTPmem : ∀ w ∈ TP, ∃ σ ∈ L, ∃ e, w = comp (ev σ) e := by
    intro w hw
    obtain ⟨⟨σ, e⟩, hp, rfl⟩ := Finset.mem_image.mp hw
    exact ⟨σ, (Finset.mem_product.mp hp).1, e, rfl⟩
  have hTPhom : ∀ w ∈ TP, IsHomogeneousTuple A (fun b : ↥B ↦ lam b) w (eT w) := by
    intro w hw
    obtain ⟨σ, _, e, rfl⟩ := hTPmem w hw
    have h : ∃ e', IsHomogeneousTuple A (fun b : ↥B ↦ lam b) (comp (ev σ) e) e' :=
      ⟨e, hcomp_hom _ _⟩
    have heT : eT (comp (ev σ) e) = Classical.choose h := by
      simp only [heTdef]
      rw [dif_pos h]
    rw [heT]
    exact Classical.choose_spec h
  have hTPlim : ∀ w ∈ TP, ∀ (b : ↥B) β, w b ∈ A β → w b ≠ 0 →
      β.constantCoeff = 0 := by
    intro w hw b β hmem hne
    obtain ⟨σ, hσ, e, rfl⟩ := hTPmem w hw
    exact hcomp_lim σ hσ e b β hmem hne
  have hTPd : ∀ w ∈ TP, ∀ b, Δ (w b) = 0 := by
    intro w hw b
    by_cases h0 : w b = 0
    · rw [h0, map_zero]
    · have hhom := (isHomogeneousTuple_iff.mp (hTPhom w hw)) b
      have hex : ∃ β, β + lam b = eT w := by
        by_contra hn
        exact h0 (hhom.2 hn)
      obtain ⟨β, hβ⟩ := hex
      exact hΔ.eq_zero
        (hTPlim w hw b β (hhom.1 β hβ) h0) (hhom.1 β hβ)
  have hTPsyz : ∀ w ∈ TP, ∑ b : ↥B, aeval x (c b) * w b = 0 := by
    intro w hw
    obtain ⟨σ, hσ, e, rfl⟩ := hTPmem w hw
    exact hcomp_syz σ hσ e
  -- the hypothesis in the degrees below `δ`: evaluation injective below `δ`
  have hbase : ∀ d < δ, d.constantCoeff = 0 → ∀ u' : ↥B → R,
      IsHomogeneousTuple A (fun b : ↥B ↦ lam b) u' d → ∑ b : ↥B, aeval x (c b) * u' b = 0 →
      u' ∈ Submodule.span (R) (TP : Set (↥B → R)) := by
    intro d hd _ u' hu' hsyz'
    -- polynomial representatives of the entries
    have hU : ∀ b : ↥B, ∃ U : MvPolynomial ι K,
        (∀ β, β + lam b = d → IsWeightedHomogeneous wt U β) ∧
        ((¬ ∃ β, β + lam b = d) → U = 0) ∧ aeval x U = u' b := by
      intro b
      have hhom := (isHomogeneousTuple_iff.mp hu') b
      by_cases h : ∃ β, β + lam b = d
      · obtain ⟨β, hβ⟩ := h
        obtain ⟨U, hUhom, hUu⟩ := hx.exists_aeval_eq hgz β
          (u' b) (hhom.1 β hβ)
        refine ⟨U, fun β' hβ' ↦ ?_, fun hn ↦ absurd ⟨β, hβ⟩ hn, hUu⟩
        rwa [add_right_cancel (hβ'.trans hβ.symm)]
      · exact ⟨0, fun β hβ ↦ absurd ⟨β, hβ⟩ h, fun _ ↦ rfl, by rw [map_zero, hhom.2 h]⟩
    choose U hUhom hU0 hUu using hU
    -- `∑ c_b U_b` is a relation of degree `d < δ`, hence zero
    have hG : IsWeightedHomogeneous wt (∑ b : ↥B, c b * U b) d := by
      refine IsWeightedHomogeneous.sum _ _ _ fun b _ ↦ ?_
      by_cases h : ∃ β, β + lam b = d
      · obtain ⟨β, hβ⟩ := h
        have := (hchom b (hBT b.2)).mul (hUhom b β hβ)
        rwa [add_comm, hβ] at this
      · rw [hU0 b h, mul_zero]
        exact isWeightedHomogeneous_zero K wt d
    have hG0 : aeval x (∑ b : ↥B, c b * U b) = 0 := by
      rw [map_sum, ← hsyz']
      exact Finset.sum_congr rfl fun b _ ↦ by rw [map_mul, hUu]
    have hGz := (injectiveAt_iff _).mp (hinj d hd) _ hG hG0
    -- so `U` is a polynomial syzygy, a combination of the generators
    obtain ⟨r, _, hr⟩ := Submodule.mem_span_finset.mp (hLspan U hGz)
    have hu'eq : u' = ∑ σ ∈ L, aeval x (r σ) • ev σ := by
      funext b
      rw [Finset.sum_apply]
      have hrb := congrFun hr b
      rw [Finset.sum_apply] at hrb
      simp only [Pi.smul_apply, smul_eq_mul] at hrb ⊢
      rw [← hUu b, ← hrb, map_sum]
      exact Finset.sum_congr rfl fun σ _ ↦ by rw [map_mul, hev]
    rw [hu'eq]
    refine Submodule.sum_mem _ fun σ hσ ↦ Submodule.smul_mem _ _ ?_
    rw [hev_sum σ hσ]
    exact Submodule.sum_mem _ fun e he ↦ Submodule.subset_span
      (Finset.mem_image.mpr ⟨(σ, e), Finset.mem_product.mpr ⟨hσ, he⟩, rfl⟩)
  -- the induction on syzygies
  have huN := mem_span_of_isHomogeneousTuple_of_sum_eq_zero (c := fun b : ↥B ↦ aeval x (c b))
    (lam := fun b : ↥B ↦ lam b) hΔ (fun b ↦ aeval_mem_of_forall_mem hx.mem (hchom b (hBT b.2)))
    (fun b ↦ hlamc b (hBT b.2)) (hsyzint (fun b : ↥B ↦ lam b)) TP eT hTPhom hTPd hδ hbase
    δ le_rfl u hu hsyz
  obtain ⟨a₂, ha₂, hu_eq⟩ := exists_eq_sum_smul_of_mem_span hTPhom hu huN
  -- every `u_b` lies in `(P̂_+)² ∩ P_{deg b}`
  have hudec : ∀ b : ↥B, u b ∈ decomposableAt (A) (wt b) := by
    intro b
    have hub := congrFun hu_eq b
    rw [Finset.sum_apply] at hub
    simp only [Pi.smul_apply, smul_eq_mul] at hub
    rw [hub]
    refine sum_mem fun w hw ↦ ?_
    by_cases hwb : w b = 0
    · rw [hwb, mul_zero]
      exact zero_mem _
    by_cases ha0 : a₂ w = 0
    · rw [ha0, zero_mul]
      exact zero_mem _
    have hhom := (isHomogeneousTuple_iff.mp (hTPhom w hw)) b
    obtain ⟨β, hβ⟩ : ∃ β, β + lam b = eT w := by
      by_contra hn
      exact hwb (hhom.2 hn)
    have hwβ : w b ∈ A β := hhom.1 β hβ
    obtain ⟨ρ, hρ⟩ : ∃ ρ, ρ + eT w = δ := by
      by_contra hn
      exact ha0 ((ha₂ w hw).2 hn)
    have haρ : a₂ w ∈ A ρ := (ha₂ w hw).1 ρ hρ
    have hρβ : ρ + β = wt b := by
      apply add_right_cancel (b := lam b)
      rw [add_assoc, hβ, hρ, add_comm]
      exact (hlam b (hBT b.2)).symm
    -- `ρ ≠ 0`: its finite part is that of `δ`, `n ≥ 1`
    have hβc : β.constantCoeff = 0 := hTPlim w hw b β hwβ hwb
    have hρ0 : ρ ≠ 0 := by
      intro h0
      have h1 := congrArg NatOrdinal.constantCoeff hρ
      rw [NatOrdinal.constantCoeff_add, ← hβ, NatOrdinal.constantCoeff_add, hβc,
        hlamc b (hBT b.2), h0, NatOrdinal.constantCoeff_zero] at h1
      omega
    -- `β ≠ 0`: a scalar entry would put `c_b` in the ideal of the other `c_{b'}`
    have hβ0 : β ≠ 0 := by
      intro h0
      rw [h0, zero_add] at hβ
      rw [h0] at hwβ
      obtain ⟨κ, hκ⟩ := (gradeZeroScalars_iff A).mp hgz (w b) hwβ
      have hκ0 : κ ≠ 0 := by
        rintro rfl
        exact hwb (by rw [hκ, map_zero])
      have hP : ∀ b' : ↥B, ∃ P : MvPolynomial ι K,
          (∀ β', β' + lam b' = lam b → IsWeightedHomogeneous wt P β') ∧
          ((¬ ∃ β', β' + lam b' = lam b) → P = 0) ∧ aeval x P = w b' := by
        intro b'
        have hhom' := (isHomogeneousTuple_iff.mp (hTPhom w hw)) b'
        rw [← hβ] at hhom'
        by_cases h : ∃ β', β' + lam b' = lam b
        · obtain ⟨β', hβ'⟩ := h
          obtain ⟨P, hPhom, hPw⟩ := hx.exists_aeval_eq hgz β'
            (w b') (hhom'.1 β' hβ')
          refine ⟨P, fun β'' hβ'' ↦ ?_, fun hn ↦ absurd ⟨β', hβ'⟩ hn, hPw⟩
          rwa [add_right_cancel (hβ''.trans hβ'.symm)]
        · exact ⟨0, fun β' hβ' ↦ absurd ⟨β', hβ'⟩ h, fun _ ↦ rfl, by rw [map_zero, hhom'.2 h]⟩
      choose P hPhom hP0 hPw using hP
      -- the relation `κ c_b + ∑_{b' ≠ b} c_{b'} P_{b'}` of degree `lam b < δ`
      have hG'hom : IsWeightedHomogeneous wt
          (C κ * c b + ∑ b' ∈ Finset.univ.erase b, c b' * P b') (lam b) := by
        refine ((hchom b (hBT b.2)).C_mul κ).add (IsWeightedHomogeneous.sum _ _ _ fun b' _ ↦ ?_)
        by_cases h : ∃ β', β' + lam b' = lam b
        · obtain ⟨β', hβ'⟩ := h
          have := (hchom b' (hBT b'.2)).mul (hPhom b' β' hβ')
          rwa [add_comm, hβ'] at this
        · rw [hP0 b' h, mul_zero]
          exact isWeightedHomogeneous_zero K wt _
      have hG'0 : aeval x (C κ * c b + ∑ b' ∈ Finset.univ.erase b, c b' * P b') = 0 := by
        have hsyzw := hTPsyz w hw
        rw [← Finset.add_sum_erase _ _ (Finset.mem_univ b), hκ] at hsyzw
        rw [map_add, map_mul, map_sum, ← algebraMap_eq, AlgHom.commutes, Algebra.commutes,
          Finset.sum_congr rfl fun b' _ ↦ by rw [map_mul, hPw]]
        exact hsyzw
      have hG'z := (injectiveAt_iff _).mp (hinj (lam b) (hlamlt b (hBT b.2))) _ hG'hom hG'0
      have h2 : C κ * c b = -∑ b' ∈ Finset.univ.erase b, c b' * P b' :=
        eq_neg_of_add_eq_zero_left hG'z
      have h3 : c b = C κ⁻¹ * (C κ * c b) := by
        rw [← mul_assoc, ← C_mul, inv_mul_cancel₀ hκ0, C_1, one_mul]
      refine hBmin' b b.2 ?_
      rw [h3, h2]
      refine Ideal.mul_mem_left _ _ ((Ideal.neg_mem_iff _).mpr (Ideal.sum_mem _ fun b' hb' ↦ ?_))
      refine Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨b', ?_, rfl⟩)
      exact Finset.mem_coe.mpr (Finset.mem_erase.mpr
        ⟨fun h ↦ (Finset.mem_erase.mp hb').1 (Subtype.ext h), b'.2⟩)
    rw [← hρβ]
    exact mul_mem_decomposableAt (A) hρ0 hβ0 haρ hwβ
  -- the linear part `ℓ_b` of `W_b` then lies in `(P̂_+)² ∩ P_{deg b}`, contradicting the linear
  -- independence of the generators modulo `(P̂_+)² ∩ P_{deg b}`
  obtain ⟨b₀, hb₀⟩ := hBne
  obtain ⟨b, hb⟩ : ∃ b : ↥B, (b : ι) = b₀ := ⟨⟨b₀, hb₀⟩, rfl⟩
  obtain ⟨κ', hκ'⟩ : ∃ κ' : ι → K, ∀ t, κ' t = coeff 0 (a' t b) := ⟨_, fun _ ↦ rfl⟩
  obtain ⟨ℓ, hℓ⟩ : ∃ ℓ : MvPolynomial ι K, ℓ = ∑ t ∈ T, C (κ' t) * X t := ⟨_, rfl⟩
  have hdiff : aeval x (W b) - aeval x ℓ ∈ decomposableAt (A) (wt b) := by
    rw [hW, hℓ, map_sum, map_sum, ← Finset.sum_sub_distrib]
    refine sum_mem fun t ht ↦ ?_
    rw [map_mul, map_mul, map_add, aeval_X, ← algebraMap_eq, AlgHom.commutes]
    have hVt : aeval x (V t) ∈ decomposableAt (A) (wt t) := by
      refine aeval_mem_decomposableAt_of_mem_supported hx.mem hx.ne_zero ?_ (hV t ht).1 ?_
      · rw [(hmemT t ht).2]
        exact hδ
      · rw [(hmemT t ht).2]
        exact (hV t ht).2
    by_cases h : ∃ β, β + lam b = lam t
    · obtain ⟨β, hβ⟩ := h
      have hahom := ha'hom t ht b β hβ
      have hdeg : β + wt t = wt b := by
        apply add_right_cancel (b := lam b)
        rw [add_right_comm, hβ, hlam t ht, add_comm, hlam b (hBT b.2)]
      by_cases hβ0 : β = 0
      · -- a scalar coefficient: the difference is `κ' t • V_t(𝓑)`
        subst hβ0
        have hC : a' t b = C (κ' t) := by
          rw [hκ']
          exact eq_C_of_isWeightedHomogeneous_zero hx.ne_zero hahom
        rw [zero_add] at hdeg
        rw [hC]
        rw [← algebraMap_eq]
        rw [AlgHom.commutes]
        rw [mul_add]
        rw [add_sub_cancel_left]
        rw [mul_comm]
        rw [← hdeg]
        have := mul_mem_decomposableAt_of_mem_decomposableAt hVt
          (SetLike.algebraMap_mem_graded (A) (κ' t))
        rwa [add_zero] at this
      · have hκ0 : κ' t = 0 := by
          rw [hκ']
          exact coeff_zero_eq_zero_of_isWeightedHomogeneous hahom hβ0
        rw [hκ0, map_zero, zero_mul, sub_zero, mul_add, ← hdeg]
        refine add_mem (mul_mem_decomposableAt (A) hβ0 (hx.ne_zero t)
          (aeval_mem_of_forall_mem hx.mem hahom) (hx.mem t)) ?_
        rw [mul_comm, add_comm]
        exact mul_mem_decomposableAt_of_mem_decomposableAt hVt
          (aeval_mem_of_forall_mem hx.mem hahom)
    · have hκ0 : κ' t = 0 := by
        rw [hκ', ha'0 t ht b h, coeff_zero]
      rw [ha'0 t ht b h, hκ0]
      simp only [map_zero, zero_mul, sub_zero]
      exact zero_mem _
  have hℓmem : aeval x ℓ ∈ decomposableAt (A) (wt b) := by
    have hub : u b ∈ decomposableAt (A) (wt b) := hudec b
    rw [hu'] at hub
    have := sub_mem hub hdiff
    rwa [sub_sub_cancel] at this
  -- `ℓ(𝓑)` is a linear combination of the generators of degree `wt b` with coefficient `1` on
  -- `x_b`
  obtain ⟨f, hf⟩ : ∃ f : ι →₀ K, f = ∑ t ∈ T, Finsupp.single t (κ' t) := ⟨_, rfl⟩
  have hfapply : ∀ i, f i = if i ∈ T then κ' i else 0 := by
    intro i
    rw [hf, Finsupp.finsetSum_apply]
    simp only [Finsupp.single_apply]
    exact Finset.sum_ite_eq' T i κ'
  have hℓeq : Finsupp.linearCombination K x f = aeval x ℓ := by
    rw [hf, map_sum, hℓ, map_sum]
    exact Finset.sum_congr rfl fun t _ ↦ by
      rw [Finsupp.linearCombination_single, map_mul, aeval_X, ← algebraMap_eq, AlgHom.commutes,
        Algebra.smul_def]
  have hfsupp : ∀ i ∈ f.support, wt i = wt b := by
    intro i hi
    rw [Finsupp.mem_support_iff, hfapply] at hi
    split_ifs at hi with hiT
    · by_cases h : ∃ β, β + lam b = lam i
      · obtain ⟨β, hβ⟩ := h
        have hahom := ha'hom i hiT b β hβ
        by_cases hβ0 : β = 0
        · subst hβ0
          rw [zero_add] at hβ
          have := (hlam i hiT).trans (hlam b (hBT b.2)).symm
          rw [hβ] at this
          exact add_left_cancel this
        · refine absurd ?_ hi
          rw [hκ']
          exact coeff_zero_eq_zero_of_isWeightedHomogeneous hahom hβ0
      · refine absurd ?_ hi
        rw [hκ', ha'0 i hiT b h, coeff_zero]
    · exact absurd rfl hi
  have hfmem : Finsupp.linearCombination K x f ∈ decomposableAt (A) (wt b) := by
    rw [hℓeq]
    exact hℓmem
  have hf0 := hx.independent (wt b) f hfsupp hfmem
  have hfb := congrArg (fun g : ι →₀ K ↦ g b₀) hf0
  simp only [Finsupp.coe_zero, Pi.zero_apply] at hfb
  rw [hfapply, if_pos (hBT hb₀)] at hfb
  have hκ1 : κ' b₀ = 1 := by
    rw [hκ', ha' b₀ b, if_pos hb₀, if_pos hb, coeff_zero_one]
  rw [hκ1] at hfb
  exact one_ne_zero hfb

end OrdinalGraded

end
