/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.HahnSeries.TruncationIntegerPartPrimal
public import ConwayRefinement.HahnSeries.IntegerPart.ReducedCharacterization

/-!
# The LM24 split truncation

At an Archimedean class `c`, the closed truncation becomes an iterated Hahn series whose outer
exponent group is the chosen stratum and whose coefficient field is the Hahn field on the open
ball. Its outer support is nonpositive, and its outer constant coefficient is exactly the open
truncation. This packages the object denoted by `ισ(Tσ(x))` in LM24, Proposition 9.2.2.
-/

public noncomputable section

namespace HahnSeries.Nonpositive

open FiniteArchimedeanClass

variable {K G R : Type*}
variable [DivisionRing K] [LinearOrder K] [IsOrderedRing K] [Archimedean K]
variable [AddCommGroup G] [LinearOrder G] [IsOrderedAddMonoid G]
variable [Module K G] [IsOrderedModule K G]
variable [Field R]

/-- The split closed-class truncation as a nonpositive Hahn series in the stratum exponent. -/
def splitTruncation (u : HahnEmbedding.ArchimedeanStrata K G)
    (c : FiniteArchimedeanClass G) (x : Nonpositive G R) :
    Nonpositive (u.stratum c) R⟦ball K c⟧ :=
  ⟨HahnSeries.archimedeanSplitRingEquiv u c (TClosed c x),
    support_archimedeanSplitRingEquiv_TClosed_subset u c x⟩

@[simp]
theorem coe_splitTruncation (u : HahnEmbedding.ArchimedeanStrata K G)
    (c : FiniteArchimedeanClass G) (x : Nonpositive G R) :
    (splitTruncation u c x : (R⟦ball K c⟧)⟦u.stratum c⟧) =
      HahnSeries.archimedeanSplitRingEquiv u c (TClosed c x) :=
  (rfl)

/-- The constant coefficient of the split truncation is the open-class truncation. -/
theorem constantCoeff_splitTruncation
    (u : HahnEmbedding.ArchimedeanStrata K G) (c : FiniteArchimedeanClass G)
    (x : Nonpositive G R) :
    constantCoeff (splitTruncation u c x) = tauBall c x :=
  by
    rw [constantCoeff_apply, coe_splitTruncation]
    exact coeff_zero_archimedeanSplitRingEquiv_TClosed u c x

/-- The split truncation in the coefficient-subring integer part selected by its open
truncation. -/
def splitTruncationIntegerPart
    (u : HahnEmbedding.ArchimedeanStrata K G) (c : FiniteArchimedeanClass G)
    (S : Subring R⟦ball K c⟧) (x : Nonpositive G R) (htau : tauBall c x ∈ S) :
    truncationIntegerPart (u.stratum c) S :=
  ⟨splitTruncation u c x, by
    rw [mem_truncationIntegerPart, ← constantCoeff_apply, constantCoeff_splitTruncation]
    exact htau⟩

theorem coe_splitTruncationIntegerPart_hahn
    (u : HahnEmbedding.ArchimedeanStrata K G) (c : FiniteArchimedeanClass G)
    (S : Subring R⟦ball K c⟧) (x : Nonpositive G R) (htau : tauBall c x ∈ S) :
    ((splitTruncationIntegerPart u c S x htau :
      Nonpositive (u.stratum c) R⟦ball K c⟧) :
        (R⟦ball K c⟧)⟦u.stratum c⟧) =
      HahnSeries.archimedeanSplitRingEquiv u c (TClosed c x) :=
  (rfl)

@[simp]
theorem coe_splitTruncationIntegerPart
    (u : HahnEmbedding.ArchimedeanStrata K G) (c : FiniteArchimedeanClass G)
    (S : Subring R⟦ball K c⟧) (x : Nonpositive G R) (htau : tauBall c x ∈ S) :
    (splitTruncationIntegerPart u c S x htau :
      Nonpositive (u.stratum c) R⟦ball K c⟧) = splitTruncation u c x :=
  (rfl)

/-- If the open truncation is one, primality of the split truncation in the corresponding
coefficient-subring integer part is exactly its ambient primality. -/
theorem isPrimal_splitTruncationIntegerPart_iff_of_tau_eq_one
    (u : HahnEmbedding.ArchimedeanStrata K G) (c : FiniteArchimedeanClass G)
    (S : Subring R⟦ball K c⟧) (x : Nonpositive G R) (htau : tauBall c x = 1) :
    IsPrimal (splitTruncationIntegerPart u c S x (htau.symm ▸ S.one_mem)) ↔
      IsPrimal (splitTruncation u c x) := by
  apply isPrimal_truncationIntegerPart_iff_of_constantCoeff_eq_one
  rw [constantCoeffAlgHom_apply, coe_splitTruncationIntegerPart, ← constantCoeff_apply,
    constantCoeff_splitTruncation, htau]

/-- If the open truncation is zero and the fraction field generated by the coefficient subring
is the whole coefficient Hahn field, primality of the split truncation in the integer part is
exactly its ambient primality. -/
theorem isPrimal_splitTruncationIntegerPart_iff_of_tau_eq_zero
    (u : HahnEmbedding.ArchimedeanStrata K G) (c : FiniteArchimedeanClass G)
    (S : Subring R⟦ball K c⟧) (hfrac : Subring.fracSubring S = ⊤)
    (x : Nonpositive G R) (htau : tauBall c x = 0) :
    IsPrimal (splitTruncationIntegerPart u c S x (htau.symm ▸ S.zero_mem)) ↔
      IsPrimal (splitTruncation u c x) := by
  apply isPrimal_truncationIntegerPart_iff_of_constantCoeff_eq_zero S hfrac
  rw [constantCoeffAlgHom_apply, coe_splitTruncationIntegerPart, ← constantCoeff_apply,
    constantCoeff_splitTruncation, htau]

/-- For a reduced nonconstant series, the split truncation is primal in its
coefficient-subring integer part exactly when it is primal in the ambient split nonpositive Hahn
ring, provided the coefficient subring generates the whole coefficient field. This is the local
Lemma 9.2.1 step in LM24, Proposition 9.2.2. -/
theorem isPrimal_splitTruncationIntegerPart_iff_of_isReduced
    (u : HahnEmbedding.ArchimedeanStrata K G) (b : Nonpositive G R) (hb0 : b ≠ 0)
    (horder : (b : R⟦G⟧).order ≠ 0) (hbReduced : IsReduced b)
    (S : Subring R⟦ball K (leadingClass b horder)⟧)
    (hfrac : Subring.fracSubring S = ⊤)
    (htauMem : tauBall (leadingClass b horder) b ∈ S) :
    IsPrimal (splitTruncationIntegerPart u (leadingClass b horder) S b htauMem) ↔
      IsPrimal (splitTruncation u (leadingClass b horder) b) := by
  rcases (isReduced_iff_tau_leadingClass_eq_zero_or_one (K := K) b hb0 horder).mp
      hbReduced with
    htau | htau
  · have htauBall : tauBall (leadingClass b horder) b = 0 :=
      (tauBall_eq_zero_iff (leadingClass b horder) b).mpr htau
    convert isPrimal_splitTruncationIntegerPart_iff_of_tau_eq_zero
      u (leadingClass b horder) S hfrac b htauBall using 1
  · have htauBall : tauBall (K := K) (leadingClass b horder) b = 1 := by
      exact tauBall_eq_one_of_tau_eq_one (leadingClass b horder) b htau
    convert isPrimal_splitTruncationIntegerPart_iff_of_tau_eq_one
      u (leadingClass b horder) S b htauBall using 1

end HahnSeries.Nonpositive
