/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module

public import ConwayRefinement.Algebra.Valuation.DegreeAssociatedGradedQuotient
public import ConwayRefinement.Algebra.Valuation.Tests.Fixtures.PolynomialAssociatedGraded
public import ConwayRefinement.Algebra.Valuation.Tests.Fixtures.PolynomialQuotientDegree

import ConwayRefinement.Algebra.Valuation.DegreePrincipalInitialIdeal
import Mathlib.Algebra.Polynomial.Degree.Operations

/-!
# API checks for the associated graded ring of a quotient

For `ℚ[X] / (X - 1)`, the degree-one initial class of `X - 1` equals the initial class of `X`.
The canonical graded quotient map therefore kills that nonzero degree-one class, and the class lies
in the initial ideal. The degree-zero unit survives. Together these facts separate the canonical
map from both the identity map and the zero map, while checking that lower-degree terms disappear
from an initial form.
-/

open scoped MaxAddDegree

public noncomputable section

namespace Tests

open Polynomial

private def relationFiltrationOne : polynomialDegree.filtrationLE 1 :=
  ⟨X - C 1, (polynomialDegree.mem_filtrationLE_iff 1 _).mpr (by
    rw [polynomialDegree_apply]
    exact Polynomial.degree_X_sub_C_le 1)⟩

private theorem relation_mem_evaluationAtOneIdeal :
    (relationFiltrationOne : ℚ[X]) ∈ evaluationAtOneIdeal := by
  rw [relationFiltrationOne]
  exact Ideal.Quotient.eq_zero_iff_mem.mp quotientMk_X_sub_one_eq_zero

private theorem relation_component_eq_xInitial :
    polynomialDegree.componentMk 1 relationFiltrationOne = polynomialXInitial := by
  let x : polynomialDegree.filtrationLE 1 :=
    ⟨X, (polynomialDegree.mem_filtrationLE_iff 1 X).mpr (by
      rw [polynomialDegree_apply, Polynomial.degree_X]
      simp)⟩
  let c : polynomialDegree.filtrationLE 1 :=
    ⟨C 1, (polynomialDegree.mem_filtrationLE_iff 1 _).mpr (by
      rw [polynomialDegree_apply, Polynomial.degree_C one_ne_zero]
      simp)⟩
  have hc : polynomialDegree.componentMk 1 c = 0 := by
    rw [polynomialDegree.componentMk_eq_zero_iff, polynomialDegree_apply,
      Polynomial.degree_C one_ne_zero]
    simp
  have hrelation : relationFiltrationOne = x - c := Subtype.ext rfl
  rw [hrelation, map_sub, hc, sub_zero, polynomialXInitial_eq_componentMk]

/-- The degree-one initial class of `X` maps to zero modulo `X - 1`. -/
theorem polynomialGradedQuotientMap_X_eq_zero :
    polynomialDegree.associatedGradedQuotientMap evaluationAtOneIdeal
        polynomialDegree_isSeparated
        (DirectSum.of polynomialDegree.Component 1 polynomialXInitial) = 0 := by
  rw [polynomialDegree.associatedGradedQuotientMap_of]
  have hcomponent :
      polynomialDegree.quotientComponentMap evaluationAtOneIdeal
          polynomialDegree_isSeparated 1 polynomialXInitial = 0 :=
    (polynomialDegree.quotientComponentMap_eq_zero_iff evaluationAtOneIdeal
      polynomialDegree_isSeparated 1 polynomialXInitial).mpr
      ⟨relationFiltrationOne, relation_mem_evaluationAtOneIdeal,
        relation_component_eq_xInitial⟩
  rw [hcomponent,
    (DirectSum.of
      (polynomialDegree.quotient evaluationAtOneIdeal
        polynomialDegree_isSeparated).Component 1).map_zero]

/-- The degree-one initial class of `X` belongs to the initial ideal of `(X - 1)`. -/
theorem polynomialXInitial_mem_initialIdeal :
    DirectSum.of polynomialDegree.Component 1 polynomialXInitial ∈
      polynomialDegree.initialIdeal evaluationAtOneIdeal := by
  have hmem := polynomialDegree.homogeneousMk_mem_initialIdeal evaluationAtOneIdeal
    1 relationFiltrationOne relation_mem_evaluationAtOneIdeal
  rw [polynomialDegree.homogeneousMk_apply, relation_component_eq_xInitial] at hmem
  exact hmem

/-- The quotient-ring equivalence sends the class of the degree-one initial form to zero. -/
theorem polynomialAssociatedGradedQuotientEquiv_X_eq_zero :
    polynomialDegree.associatedGradedQuotientEquiv evaluationAtOneIdeal
        polynomialDegree_isSeparated
        (Ideal.Quotient.mk (polynomialDegree.initialIdeal evaluationAtOneIdeal)
          (DirectSum.of polynomialDegree.Component 1 polynomialXInitial)) = 0 := by
  rw [polynomialDegree.associatedGradedQuotientEquiv_mk,
    polynomialGradedQuotientMap_X_eq_zero]

/-- The initial ideal of `(X - 1)` is generated by the degree-one initial class of `X`. -/
theorem polynomialInitialIdeal_eq_span_XInitial :
    polynomialDegree.initialIdeal evaluationAtOneIdeal =
      Ideal.span {DirectSum.of polynomialDegree.Component 1 polynomialXInitial} := by
  rw [evaluationAtOneIdeal_eq_span,
    polynomialDegree.initialIdeal_span_singleton_eq_span_initialForm]
  have hcomponent :
      polynomialDegree.componentMk 1 relationFiltrationOne ≠ 0 := by
    rw [relation_component_eq_xInitial]
    exact polynomialXInitial_ne_zero
  have hinitial :=
    polynomialDegree.initialForm_eq_homogeneousMk_of_componentMk_ne_zero
      1 relationFiltrationOne hcomponent
  change polynomialDegree.initialForm (X - C 1) =
    polynomialDegree.homogeneousMk 1 relationFiltrationOne at hinitial
  rw [hinitial,
    polynomialDegree.homogeneousMk_apply, relation_component_eq_xInitial]

private theorem evaluationAtOneQuotient_one_ne_zero :
    (1 : ℚ[X] ⧸ evaluationAtOneIdeal) ≠ 0 := by
  simpa using quotientMk_one_ne_zero

private theorem evaluationAtOneQuotientDegree_one_eq_zero :
    (polynomialDegree.quotient evaluationAtOneIdeal polynomialDegree_isSeparated) 1 =
      (0 : ℕ) := by
  let νq := polynomialDegree.quotient evaluationAtOneIdeal polynomialDegree_isSeparated
  have hsep : νq.IsSeparated :=
    polynomialDegree.quotient_isSeparated evaluationAtOneIdeal
      polynomialDegree_isSeparated
  have hnebot : νq 1 ≠ ⊥ := by
    intro hbot
    exact evaluationAtOneQuotient_one_ne_zero
      (((νq.isSeparated_iff).mp hsep 1).mp hbot)
  have hle : νq 1 ≤ (0 : WithBot ℕ) := νq.map_one_le_zero
  obtain ⟨n, hn⟩ := WithBot.ne_bot_iff_exists.mp hnebot
  rw [← hn] at hle ⊢
  have hnzero : n = 0 := Nat.eq_zero_of_le_zero (WithBot.coe_le_coe.mp hle)
  simp [hnzero]

/-- The degree-zero unit survives the canonical graded quotient map. -/
theorem polynomialGradedQuotientMap_one_ne_zero :
    polynomialDegree.associatedGradedQuotientMap evaluationAtOneIdeal
        polynomialDegree_isSeparated 1 ≠ 0 := by
  let νq := polynomialDegree.quotient evaluationAtOneIdeal polynomialDegree_isSeparated
  have hcomponentOne : νq.componentOne ≠ 0 := by
    rw [νq.componentOne_eq_componentMk, ne_eq, νq.componentMk_eq_zero_iff]
    rw [evaluationAtOneQuotientDegree_one_eq_zero]
    exact lt_irrefl _
  have hgradedOne : (1 : νq.AssociatedGraded) ≠ 0 := by
    rw [DirectSum.one_def]
    intro hzero
    have hzero' : DirectSum.of νq.Component 0 νq.componentOne = 0 := by
      simpa only [show GradedMonoid.GOne.one = νq.componentOne from rfl] using hzero
    apply hcomponentOne
    apply DirectSum.of_injective 0
    simpa using hzero'
  rw [(polynomialDegree.associatedGradedQuotientMap evaluationAtOneIdeal
    polynomialDegree_isSeparated).map_one]
  exact hgradedOne

end Tests
