/-
Copyright (c) 2026 Dan Abramov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dan Abramov
-/
module


import ConwayRefinement.Blueprint
public import ConwayRefinement.Algebra.LoweringDerivation.Mu
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-!
# Homogeneous components of the ideal generated by homogeneous elements

Let `A` (Lean `R`) be an algebra graded by `NatOrdinal` and `q j ∈ A_{c j}` finitely many
homogeneous elements of degrees `c j`. The degree-`α` component of `(q j) r` is `(q j) r_β` for
the unique `β` with `β ⊕ c j = α`, that is `β = α ⊖ c j` when `c j ≼ α` in the algebraic order,
and `0` otherwise (the natural sum is cancellative, so `β` is unique when it exists, but unlike the
case of `ℕ` it need not exist: `β ⊕ 1 = ω` has no solution). Consequently a homogeneous element of
degree `α` of the ideal `(q j)` is `∑_j (q j) (u j)` with `u j ∈ A_{α ⊖ c j}` when `c j ≼ α`,
and `u j = 0` otherwise.
-/

universe u v w

open DirectSum

public noncomputable section

namespace OrdinalGraded

variable {E : Type u} {R : Type v} [Field E] [CommRing R] [Algebra E R]
variable {𝒜 : NatOrdinal → Submodule E R} [GradedAlgebra 𝒜]

open Classical in
/-- The degree-`α` component of `q * r` for `q ∈ 𝒜 c`: `q * r_β` if `β ⊕ c = α`, and `0` if
`c` does not precede `α` in the algebraic order. -/
theorem coe_decompose_mul_of_left_mem {q : R} {c : NatOrdinal} (hq : q ∈ 𝒜 c) (r : R)
    (α : NatOrdinal) :
    (decompose 𝒜 (q * r) α : R) =
      if h : ∃ β, β + c = α then q * (decompose 𝒜 r (Classical.choose h) : R) else 0 := by
  split_ifs with h
  · obtain ⟨β₀, hβ₀⟩ : ∃ β₀, Classical.choose h = β₀ := ⟨_, rfl⟩
    have hβ : β₀ + c = α := hβ₀ ▸ Classical.choose_spec h
    rw [hβ₀]
    subst hβ
    -- expand `r` into its components: only `q * r_β₀` has degree `β₀ + c`
    rw [← GradedRing.proj_apply]
    conv_lhs => rw [← sum_support_decompose 𝒜 r, Finset.mul_sum, map_sum]
    have hmem : ∀ β, q * (decompose 𝒜 r β : R) ∈ 𝒜 (c + β) := fun β ↦
      SetLike.mul_mem_graded hq (decompose 𝒜 r β).2
    rw [Finset.sum_eq_single β₀]
    · rw [GradedRing.proj_apply, add_comm]
      exact decompose_of_mem_same 𝒜 (hmem β₀)
    · intro β _ hβ
      rw [GradedRing.proj_apply]
      exact decompose_of_mem_ne 𝒜 (hmem β) fun heq ↦
        hβ (add_left_cancel (heq.trans (add_comm _ _)))
    · intro hnot
      rw [DFinsupp.notMem_support_iff.mp hnot, Submodule.coe_zero, mul_zero, map_zero]
  · -- expand `r` into its components: every `q * r_β` has degree `c + β ≠ α`
    rw [← GradedRing.proj_apply]
    conv_lhs => rw [← sum_support_decompose 𝒜 r, Finset.mul_sum, map_sum]
    refine Finset.sum_eq_zero fun β _ ↦ ?_
    have hmem : q * (decompose 𝒜 r β : R) ∈ 𝒜 (c + β) :=
      SetLike.mul_mem_graded hq (decompose 𝒜 r β).2
    rw [GradedRing.proj_apply]
    exact decompose_of_mem_ne 𝒜 hmem fun heq ↦ h ⟨β, by rw [add_comm]; exact heq⟩

/-- **The homogeneous components of an element of the ideal generated by homogeneous elements.**
If `q j ∈ 𝒜 (c j)` and `x` lies in the ideal `(q j)`, then the degree-`α` component of `x` is
`∑_j (q j) (u j)` with `u j ∈ 𝒜 β` for the `β` with `β ⊕ c j = α`, and `u j = 0` if `c j` is not a
below `α` in the algebraic order. -/
theorem exists_decompose_eq_sum_mul_of_mem_span {ι : Type w} [Fintype ι] {q : ι → R}
    {c : ι → NatOrdinal} (hq : ∀ j, q j ∈ 𝒜 (c j)) {x : R} (hxI : x ∈ Ideal.span (Set.range q))
    (α : NatOrdinal) :
    ∃ u : ι → R, (∀ j, ∀ β, β + c j = α → u j ∈ 𝒜 β) ∧ (∀ j, (¬ ∃ β, β + c j = α) → u j = 0) ∧
      (decompose 𝒜 x α : R) = ∑ j, q j * u j := by
  classical
  obtain ⟨r, hr⟩ := (Submodule.mem_span_range_iff_exists_fun R).mp hxI
  have hr' : ∑ j, q j * r j = x := by
    rw [← hr]
    exact Finset.sum_congr rfl fun j _ ↦ by rw [smul_eq_mul, mul_comm]
  refine ⟨fun j ↦ if h : ∃ β, β + c j = α then (decompose 𝒜 (r j) (Classical.choose h) : R) else 0,
    fun j β hβ ↦ ?_, fun j h ↦ dif_neg h, ?_⟩
  · have h : ∃ β, β + c j = α := ⟨β, hβ⟩
    have hβ' : ∀ h' : ∃ β, β + c j = α, Classical.choose h' = β := fun h' ↦
      add_right_cancel ((Classical.choose_spec h').trans hβ.symm)
    beta_reduce
    rw [dif_pos h, hβ']
    exact (decompose 𝒜 (r j) β).2
  · calc (decompose 𝒜 x α : R) = GradedRing.proj 𝒜 α (∑ j, q j * r j) := by
          rw [GradedRing.proj_apply, hr']
      _ = ∑ j, GradedRing.proj 𝒜 α (q j * r j) := map_sum _ _ _
      _ = _ := Finset.sum_congr rfl fun j _ ↦ by
          rw [GradedRing.proj_apply, coe_decompose_mul_of_left_mem (hq j) (r j) α, mul_dite,
            mul_zero]

/-- **Homogeneous elements of the ideal generated by homogeneous elements.** If `q j ∈ 𝒜 (c j)`
and `x ∈ 𝒜 α` lies in the ideal `(q j)`, then `x = ∑_j (q j) (u j)`, where `u j ∈ 𝒜 β`
whenever `β ⊕ c j = α`, and `u j = 0` if no such `β` exists. -/
@[blueprint "lem:homogeneous-element-of-generated-ideal"
  (phase := "Algebraic and ordinal preliminaries")
  (title := "Homogeneous decomposition in a finitely generated graded ideal")
  (statement := /--
    For a finite family of homogeneous elements $Q_j\in A_{c_j}$, if
    $x\in A_\alpha$ lies in the ideal generated by the $Q_j$, then there are
    $u_j$ such that $x=\sum_jQ_ju_j$, where $u_j\in A_\beta$ whenever
    $\beta\oplus c_j=\alpha$, and $u_j=0$ if no such $\beta$ exists.
  -/)
  (proof := /--
  Apply the componentwise ideal representation and use $x_\alpha=x$.
  -/)]
theorem exists_eq_sum_mul_of_mem_span {ι : Type w} [Fintype ι] {q : ι → R} {c : ι → NatOrdinal}
    (hq : ∀ j, q j ∈ 𝒜 (c j)) {x : R} {α : NatOrdinal} (hx : x ∈ 𝒜 α)
    (hxI : x ∈ Ideal.span (Set.range q)) :
    ∃ u : ι → R, (∀ j, ∀ β, β + c j = α → u j ∈ 𝒜 β) ∧ (∀ j, (¬ ∃ β, β + c j = α) → u j = 0) ∧
      x = ∑ j, q j * u j := by
  obtain ⟨u, hu, hu0, hsum⟩ := exists_decompose_eq_sum_mul_of_mem_span hq hxI α
  exact ⟨u, hu, hu0, by rw [← hsum, decompose_of_mem_same 𝒜 hx]⟩

end OrdinalGraded
